### PR TITLE
FINERACT-822 enable MissingOverride error

### PR DESCRIPTION
**Pull request by percyashu**
FINERACT-822

### CODE REVIEW

**Review by vorburger — CHANGES_REQUESTED** [review]
LGTM but @percyashu fix merge conflict?

**Comment by percyashu** [comment]
sure

**Comment by percyashu** [comment]
@vorburger merge this?

**Review by awasum — APPROVED** [review]
LGTM

**Comment by vorburger** [comment]
@percyashu Resolve conflict, again (sorry)

**Pull request merged**
