### PR TITLE
Block transfer between different currencies (FINERACT-1355)

### PR DESCRIPTION
**Pull request by eBouvard**
## Description
See https://issues.apache.org/jira/browse/FINERACT-1355

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by ptuomola** [comment]
Hi - thanks for the pull request! Looks good to me... but can you squash the commits to a single one please and write the commit message in line with https://github.com/apache/fineract/#pull-requests, I can then merge this.

**Comment by eBouvard** [comment]
Hi @ptuomola
Commits squashed and renamed, sorry for the delay.

**Comment by ptuomola** [comment]
Hi - looks like the build failed - can you retry or check what's wrong?

**Comment by eBouvard** [comment]
Hi @ptuomola I fixed the build

**Review by ptuomola — APPROVED** [review]
LGTM - thanks for the contribution! Will merge now.

**Pull request merged**
