### PR TITLE
FINERACT-1658:Fix Group Filter in Center

### PR DESCRIPTION
**Pull request by rrpawar96**
https://issues.apache.org/jira/browse/FINERACT-1658

### CODE REVIEW

**Comment by ikimbra** [comment]
@rrpawar96 Thanks for this fix. @francisguchie kindly test this as I also test to see if it works. 

I will update the team if it is fixed then close the issue.

**Review by galovics — CHANGES_REQUESTED** [review]
Can we add a test case for this bugfix? Thanks.

**Comment by rrpawar96** [comment]
> Can we add a test case for this bugfix? Thanks.

Thanks, @galovics for the review, Test case has been added.

**Review by galovics — APPROVED** [review]
LGTM

**Pull request merged**
