### PR TITLE
Fineract 1157:UnsupportedOperationException at InteropServiceImpl

### PR DESCRIPTION
**Pull request by Wandji69**
## Description

Details are present on the associated [Apache Fineract JIRA ticket](https://issues.apache.org/jira/browse/FINERACT-1157).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by vorburger** [comment]
@Wandji69 excited to see you contribute! But did you see that the Travis CI build failed for this PR? Do you require assistance to determine why? Please also read https://github.com/apache/fineract#pull-requests, and note that this PR will be ignored, and eventually (in 1-2 months) expire and be automatically closed.

**Comment by Wandji69** [comment]
Thanks @Vorburger for looking in to this. I really will need help on
looking into this error.

On my local it ran without any error that’s why I decided to submit the
first changes I had made even though I haven’t completed it yet.
-- 
Thanks
Collins C. Wandji
No: +237672965154
https://Wandji69.github.io

**Comment by awasum** [comment]
@vorburger , Do you want to continue reviewing this one?

**Comment by Sugihiru** [comment]
The server keeps throwing a HTTP 500 Internal Server Error even with the changes

```
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
org.springframework.web.client.HttpClientErrorException: 400 Not enough balance amount for requested amount plus fees!
at org.apache.fineract.interoperation.service.InteropServiceImpl.prepareTransfer(InteropServiceImpl.java:368)
```

Result from Postman : 
```
{
    "timestamp": 1609755895161,
    "status": 500,
    "error": "Internal Server Error",
    "message": "",
    "path": "/fineract-provider/api/v1/interoperation/transfers"
}
```

**Comment by Wandji69** [comment]
Thanks, @Sugihiru I have updated the file now

**Comment by vorburger** [comment]
@Wandji69 your build here failed due to FINERACT-887, please watch that issue for progress.

**Comment by Wandji69** [comment]
Thanks, @vorburger I will keep an eye.

**Comment by vorburger** [comment]
@Wandji69 FYI the FINERACT-887 problem is now fully resolved, so you can "git rebase" this PR, and the build failure should be solved. Do you know how to do a rebase?

**Review by vorburger — CHANGES_REQUESTED** [review]
@Wandji69 BTW there are still x2 uses of the `UnsupportedOperationException`, in line 561 and 569 - it would be ideal if you would like to remove those as well, while you're at it? Then you can (have to) remove the `import` as well.

**Comment by Wandji69** [comment]
Okay thanks, @vorburger will look into this now.

**Comment by vorburger** [comment]
@Wandji69 the `FixedDepositTest` build failure that you ran into here (which was unrelated to your change) has now been fixed, so you can rebase this now, do what we discussed above, and then we could merge this!

**Review by vorburger — APPROVED** [review]
LGTM!

**Pull request merged**
