### PR TITLE
broken links in README file on Github

### PR DESCRIPTION
**Pull request by HarimbolaSantatra**
## Description

This pull request fix more broken links in the README file in addition to the one made in https://github.com/apache/fineract/pull/3686.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by Zeyad2003** [comment]
Hi @HarimbolaSantatra 

Please refer to the [CONTRIBUTING.md](https://github.com/apache/fineract/blob/develop/CONTRIBUTING.md).
You need to mention the Jira ticket in your PR to be reviewed and track the changes.

> [!NOTE]
> Follow up with one of the commiters to make sure your changes can be applied, as I saw this PR #3765 that modified the README too 

Regards!

**Comment by vidakovic** [comment]
@HarimbolaSantatra please follow the conventions concerning formatting the pull request title ("FINERACT-1234: Title of the JIRA ticket")

**Comment by vidakovic** [comment]
@HarimbolaSantatra accidentally closed the PR... re-opened it.

**Comment by adamsaghy** [comment]
@HarimbolaSantatra Please follow the conventions on how to format the pull request title ("[FINERACT-1234](https://issues.apache.org/jira/browse/FINERACT-1234): Title of the JIRA ticket")

Same applies for the commit message as well

**Pull request closed without merging**
