### PR TITLE
FINERACT-1448 send-email-fix

### PR DESCRIPTION
**Pull request by fynmanoj**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by fynmanoj** [comment]
@ptuomola , Kindly review this.  please let me know if you suspect any other impact for this change.

**Comment by BLasan** [comment]
@ptuomola Could you please review this? With the `exclude` part, email sending was not getting executed (class not found error was throwing)

**Comment by ptuomola** [comment]
@BLasan the build seems to be still failing due to duplicate classes... 

The reason why the exclusion is exactly to resolve this duplication of classes: otherwise we have two versions of activation classes in the classpath: javax.activation and com.sun.activation. As com.sun.activation is out of date and obsolete, we should exclude this. 

Now with this change it seems to be that we are going back to the old com.sun version and excluding the newer javax one. I'm not sure this is a good idea... what's the reason for this?

**Comment by fynmanoj** [comment]
Hi @ptuomola , I have added the stack trace in this ticket https://issues.apache.org/jira/browse/FINERACT-1448

**Comment by ptuomola** [comment]
I created a PR that hopefully fixes this - see #1993. Let's see if that works...

**Comment by fynmanoj** [comment]
@ptuomola , Thank you very much. This should work.

**Comment by fynmanoj** [comment]
Fixed by : https://github.com/apache/fineract/pull/1993

**Pull request closed without merging**
