### PR TITLE
FINERACT-1776: Introduce Lombok to office module

### PR DESCRIPTION
**Pull request by meghnabajoria**
## Description

Introduced Lombok to office module

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@meghnabajoria Kindly asking you to run spotlessCheck before the commit!
` ./gradlew spotlessApply `

**Comment by vidakovic** [comment]
@meghnabajoria  Can't see that the build failures are related to your changes... just rerunning them again and we'll see. In general Adam's advice is the one to follow: trigger the automatic formatting before each commit... saves a lot of head-aches.

**Comment by vidakovic** [comment]
... one more: please follow the general pattern for naming the PRs... otherwise the automatic linking in Jira won't work. The correct title for this PR would be: "FINERACT-1776: Introduce Lombok to office module"... thanks again.

**Comment by vidakovic** [comment]
@meghnabajoria ... still failing... please can you check what the problem is and fix it? Thanks.

**Pull request closed without merging**
