### PR TITLE
FINERACT-1011 increase timeout for Gradle Cargo Plugin

### PR DESCRIPTION
**Pull request by awasum**
## Description
Increase timeout for Gradle Cargo Plugin to fix: https://issues.apache.org/jira/browse/FINERACT-1011

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by awasum** [comment]
I wonder why this passes without Travis catching this: https://jira.apache.org/jira/browse/FINERACT-1010 but i can see the failure locally. Could it be because an using Oracle JDK 11.0.7 ?

**Comment by awasum** [comment]
> I wonder why this passes without Travis catching this: https://jira.apache.org/jira/browse/FINERACT-1010 but i can see the failure locally. Could it be because an using Oracle JDK 11.0.7 ?

This is problem has disappeared. It seems the DB had not initialized properly.

**Comment by awasum** [comment]
@ptuomola ..see this PR related to my timeout issue. Looks good to you? @vorburger will you like to merge this?

**Comment by ptuomola** [comment]
Looks great to me!

**Review by vorburger — APPROVED** [review]
LGTM

**Pull request merged**
