### PR TITLE
FINERACT-1221 Fix Client SDK Broken Methods

### PR DESCRIPTION
**Pull request by henriquepaes1**
## Description
Retrofit does not allow HTTP Body in Delete operations. However, some Resources classes had an @RequestBody Swagger annotation, which added a body to retrofit interfaces, therefore the method threw the mentioned exception. Once I validated that the requests never used the body, I fixed the methods by removing the @RequestBody annotation.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@henriquepaes1 Please rebase and squash your commits!

**Comment by henriquepaes1** [comment]
Hey @adamsaghy! The last time I rebased my branch (I think I did something wrong) it added some commits and changed some files that aren't related to the PR fix. Would it be better to start a new cleaner branch?

**Comment by adamsaghy** [comment]
seems something went wrong. you can give a try with clean branch

**Comment by henriquepaes1** [comment]
Okay! I'll close this PR and open a new one with a clean branch.

**Pull request closed without merging**
