### PR TITLE
add First Interaction Greeting GitHub Action

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Review by xurror — APPROVED** [review]
LGTM

**Comment by vorburger** [comment]
@awasum merge this one? (Saw your reply on the mailing list re. this.)

**Comment by awasum** [comment]
@vorburger ...Ohhh... merged this but it failed with an error:
Invalid workflow file:
https://github.com/apache/fineract/actions/runs/101369009

Please...help to check it.

**Comment by vorburger** [comment]
@awasum #884 should (hopefully) fix it!

**Pull request merged**
