### PR TITLE
GSOC'17:swagger and swagger UI integration on fineract-provider

### PR DESCRIPTION
**Pull request by Sanyam96**
This Pull Request contains the Integration of Swagger on fineract-provider for dynamic documentation of REST API which can easily replace apiLive.htm (which is the current documentation of Apache/Fineract Rest API) and now the documentation can easily be in sync with the Rest API.

Developers can follow the "Instructions For Accessing Swagger Files" and "Developers Instruction for Contribution" in the Documentation Link ( https://goo.gl/S1jJuS ) on the integration of Swagger and Swagger UI on Fineract Rest API.

All the details related to Swagger Integration on Fineract can easily be found at:
PDF Link of Documentation: https://goo.gl/8RMMhN
Google Doc Link of Documentation: https://goo.gl/S1jJuS

@nazeer1100126
@dhirenpratap
@vidakovic
@edcable

### CODE REVIEW

**Comment by nikpawar89** [comment]
@Sanyam96  Could you please resolve the conflicts. We can start working towards its integration.

**Comment by Sanyam96** [comment]
@nikpawar89 
I have solved the merge conflicts with the Develop branch.

**Comment by nikpawar89** [comment]
@Sanyam96  thanks for that I am in process of reviewing your code..

**Comment by nikpawar89** [comment]
As the annotations for portfolio branch are to be inserted, merging this PR will not be feasible.
The remaining work can be converted into GCI tasks and once the PR is completed we can merge it.
@nazeer1100126  @avikganguly01  let me know your views.
 I was also having concern over manually inserting /swagger.json or /swagger.yml  after we have build the application. I am not 100% sure if this will work, but I have seen people generating the files during compile time,
https://tech.homeaway.com/development/2016/06/02/generating-swagger-spec.html
Although this has been done in maven. @Sanyam96  please refer this link
 
For bit level task, I can take the lead for mentoring GCI students to get this PR completed.

**Comment by edcable** [comment]
@avikganguly01 @nazeer1100126 are you in concurrence with @nikpawar89 that we should wait on committing these changes until the annotations for portfolio are complete as well? I would like to at least get this committed and then after GCI do the remaining commits once portfolio is done. Or am I missing something and this can not be done in separate chunks?

**Comment by avikganguly01** [comment]
@Sanyam96 : I am unable to pull in this code as you included following files in your source which I believe belongs to Swagger and we cannot release them under our license.

src/main/resources/swagger-ui/swagger-ui-bundle.js.map
src/main/resources/swagger-ui/swagger-ui-standalone-preset.js.map
src/main/resources/swagger-ui/swagger-ui.css
src/main/resources/swagger-ui/swagger-ui.css.map
src/main/resources/swagger-ui/swagger-ui-standalone-preset.js
src/main/resources/swagger-ui/swagger-ui.js.map
src/main/resources/swagger-ui/swagger-ui-bundle.js
src/main/resources/swagger-ui/swagger-ui.js

You should add a bower.json file to pull in this file, then add bower_components to .gitignore folder and change path references for this file to point to bower_components folder.

**Comment by Sanyam96** [comment]
@avikganguly01 
Hi Avik, Swagger is an open source project in which we have used their Swagger-UI project with some modification to enable Swagger-UI with Swagger-Json.
I have followed their instruction to enable Swagger-UI Please see the link: https://swagger.io/docs/swagger-tools/#download-33

**Comment by avikganguly01** [comment]
@mgeiss : Swagger UI (https://swagger.io/docs/swagger-tools/#download-33) is advocating customizing their css  and js files directly. Can we put our license on such modified files like swagger-ui.css and swagger-ui.js?

**Comment by ghost** [comment]
we should not change the underlying license of swagger ... if needed we should exclude them from the license check ... even if we change the code ... it is not ours (;

**Comment by vidakovic** [comment]
Just FYI: I was @Sanyam96 's mentor last year and had a look at his changes. Looks good to me.

**Comment by ShruthiRajaram** [comment]
@Sanyam96 , kindly resolve the conflicts and squash the commits.

**Comment by ShruthiRajaram** [comment]
@nikpawar89 , @avikganguly01 , @nazeer1100126 and @vidakovic kindly review this PR.
@Sanyam96   can you check the file "fineract-provider.iml" , I think this will break the deployment.

**Comment by Sanyam96** [comment]
Okay, I'll check and remove the 'fineract-provider.iml' file
Might be pushed because of IntelliJ IDEA.

**Comment by ShruthiRajaram** [comment]
@Sanyam96  kindly squash commits.

**Comment by vidakovic** [comment]
@Sanyam96 looks like the type of on variable in ClientData changed... could you take care of that and update the Swagger documentation accordingly? I'll do then a final check... the rest still looks good to me. Maybe we can get this done over the weekend/early next week? Ping me if you need anything.

**Comment by Sanyam96** [comment]
@vidakovic the variable changed in the latest merge with develop branch with some other PR #488 
I'll solve the merge conflicts again very soon

**Comment by Sanyam96** [comment]
I have solved the merge conflicts

**Review by ShruthiRajaram — APPROVED** [review]

**Comment by ShruthiRajaram** [comment]
@vidakovic  thanks for the review. @Sanyam96 has resolved issues mentioned and no other changes were introduced. So merged the PR.

**Comment by vidakovic** [comment]
:tada: @Sanyam96 .... thanks @ShruthiRajaram for the merge

**Comment by MexinaD** [comment]
Hello @Sanyam96  @ShruthiRajaram 
I was building the platform when trying to merge one of the PRs but the build failed at "licenseMain" with the error of missing header to alot of files and all relate with this PR.
@ShruthiRajaram  did it build successfully on your end?

**Comment by ShruthiRajaram** [comment]
Hi @MexinaD, run 1. ./gradlew -Penv=dev clean cleanEclipse eclipse and 2. ./gradlew -Penv=dev clean war then run the server. You will be able to build it successfully.

**Pull request merged**
