### PR TITLE
Added missing Tag annotation for APIs

### PR DESCRIPTION
**Pull request by BLasan**
## Description

See [FINERACT-1222](https://issues.apache.org/jira/browse/FINERACT-1222)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by BLasan** [comment]
@vorburger Please review sir

**Comment by BLasan** [comment]
@vorburger @awasum Build fails. I've just added the missing Tag annotations.  Please take a look

**Comment by awasum** [comment]
This is still failing..check Travis. Ping us only when Travis passes..please.
 
Keep up the good work.

One ping to the maintainers is enough..You dont need to ping us every few minutes as we are getting notifications on all what is going on but may not have the time to respond due to out day jobs..but be assured that someone will respond eventually. Be patient.

**Comment by BLasan** [comment]
Build fails due to the previous commits. Don't know the exact commit which leads to fail the build. This is the error and the warning I'm getting
```
> Task :fineract-client:compileJava
/home/benura/Desktop/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/services/ImagesApi.java:39: error: duplicate class: org.apache.fineract.client.services.ImagesApi
public interface ImagesApi {
       ^
/home/benura/Desktop/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/auth/OAuthOkHttpClient.java:71: warning: [deprecation] create(MediaType,String) in RequestBody has been deprecated
        RequestBody body = request.getBody() != null ? RequestBody.create(mediaType, request.getBody()) : null;
                                                                  ^
1 error
1 warning
```

**Comment by BLasan** [comment]
@awasum Please review sir

**Comment by BLasan** [comment]
@vorburger Could you please review this sir?

**Comment by BLasan** [comment]
@ptuomola Please review

**Review by xurror — APPROVED** [review]
LGTM

**Comment by BLasan** [comment]
@vorburger Could you please verify this sir?

**Comment by BLasan** [comment]
Thanks for verifying @xurror  :)

**Comment by xurror** [comment]
You're welcome. We appreciate your contributions thus far. Keep up the good work.

**Pull request merged**
