### PR TITLE
FINERACT-428 Parallelization of Jobs :Parallelizing and paging of update loan summary

### PR DESCRIPTION
**Pull request by wkk91193**
Opening a new PR based on feedback from PR #464

### CODE REVIEW

**Comment by vorburger** [comment]
@wkk91193 would you mind to re-rebase this, so that Travis CI will run on it?

@avikganguly01 will you re-review this as requested in #464 ?

**Comment by wkk91193** [comment]
@vorburger will rebase once green light given from @avikganguly01

**Comment by vorburger** [comment]
@wkk91193 I'm currently doing a quick run of review on all open PRs, and was just wondering if you would still like to get this very old open one merged? If so, could you rebase it, so that we can see if it actually builds on Travis? (FYI when this PR was raised, this project did not have automated CI on Travis set up; but meanwhile it does.)

Without hearing back within let's say ... 1 month, I would be inclined to just close this (un-merged).

**Comment by vorburger** [comment]
Let's close this now, just to have less open PRs; you can open a new PR with this when you resolved the feedback and conflicts.

**Comment by wkk91193** [comment]
Reopened a new PR after a rebase #687

**Pull request closed without merging**
