### PR TITLE
bump flyway from 2.1.1 to 6.4.1

### PR DESCRIPTION
**Pull request by xurror**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by vorburger — APPROVED** [review]
LGTM! Just has merge conflict following removal of `dev-dependencies.gradle` in #881.

**Comment by xurror** [comment]
> @xurror the change to `V204__insert_script_for_charges_paid_by_for_accruals.sql` just adds a missing semicolon at the end?

Yes

**Comment by xurror** [comment]
@ptuomola, @awasum  is it OK for you?

**Comment by xurror** [comment]
@vorburger, conflicts are resolved.

**Review by vorburger — APPROVED** [review]

**Comment by awasum** [comment]
Wooow...this finally worked? Thank you both very much. What happened that drizzle or something else stopped having problems wrt Flyway? Just curious...is it the new upgrades we made ?

**Comment by vorburger** [comment]
@awasum I was wondering (and asked..) exactly the same in FINERACT-810 ... magical! :sweat_smile:

**Pull request merged**
