### PR TITLE
Test downloaded file name (FINERACT-1218)

### PR DESCRIPTION
**Pull request by vorburger**
an extension of FINERACT-1218 required to guarantee non-regression in FINERACT-1201.

### CODE REVIEW

**Comment by vorburger** [comment]
https://travis-ci.org/github/apache/fineract/builds/740634171 failed due to FINERACT-1167 (see #1458), so close & re-open to retry...

**Comment by vorburger** [comment]
@ptuomola  (or any other active committers?) willing to review this one and merge if LGTY?

**Comment by vorburger** [comment]
@vidakovic do you want to review this one, and merge if it LGTY?

**Review by vidakovic — APPROVED** [review]
LGTM

**Pull request merged**
