### PR TITLE
Feature to transfer fund from saving to share

### PR DESCRIPTION
**Pull request by MexinaD**
## Description
Added ability to transfer fund from saving balance and purchase share for that transfer amount ( transfer from saving to share)

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by santoshconflux** [comment]
@MexinaD , What is the Fineract issue id for this PR?

**Comment by MexinaD** [comment]
@santoshconflux  this is a local requirement that i was developing but the changes made the system to behave differently on some functionalities, i was told in the mail list to push a PR for someone to check on the codes and see what could be the cause so i didn't create a ticket. Should i create the ticket still?
The email has a title of "Help on the error i get"

**Comment by santoshconflux** [comment]
@MexinaD , Yes any PR(related to bug,new feature, enhancement, etc)  need to have ticket id. Helpful in release notes.

**Comment by MexinaD** [comment]
Here is the ticket https://issues.apache.org/jira/browse/FINERACT-791 @santoshconflux

**Comment by vorburger** [comment]
FTR: The context here is https://lists.apache.org/thread.html/6179f8a4435d793ab6c977f82c946a6d59a840834d5e4346301b06d8@%3Cdev.fineract.apache.org%3E, as per that email, this PR fails to build due to "Caused by: org.apache.openjpa.lib.jdbc.ReportingSQLException: Too many tables; MySQL can only use 61 tables in a join" - someone will have to figure out how to fix the code proposed here before this could be reviewed and merged.

**Comment by awasum** [comment]
@MexinaD Would you like tot take a look t this PR again and make it pass Travis?

**Comment by vorburger** [comment]
@MexinaD are you still planning to work on this one?

Or was this just an illustration of something and can already be closed?

I'll close this PR on 2020.01.31 if there are no updates until then.

**Pull request closed without merging**
