### PR TITLE
Removed unwanted result-set previous method

### PR DESCRIPTION
**Pull request by BLasan**
## Description

See [FINERACT-1089](https://issues.apache.org/jira/browse/FINERACT-1089)

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Related PR
#1184 

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by BLasan** [comment]
@vorburger @ptuomola Please review

**Review by ptuomola — CHANGES_REQUESTED** [review]
Hi @BLasan - thanks for attempting this, but resolving this issue is a bit more complicated than just removing the offending lines as the calls to rs.previous() are there for a reason: 

Currently the called function takes the ResultSet and extracts data until it finds a row that doesn't belong with the others. Then it reverses the cursor by 1 row with rs.previous(). That way when the control returns to the calling function, the cursor is set so that the calling function gets the first row of the next group by calling rs.next(). 

If we just remove the rs.previous(), then calling rs.next() in the calling function will give us the _second_ row of the next group, as we have already consumed the first row within the called function.

So one way to solve this would be to "flatten" the functions so that all work with the ResultSet is in same function - so that there is no need to pass rs.previous(). But to ensure that the "flattening" doesn't change the behaviour, it would be good to first have a test case which checks the functionality. Then when we refactor the function, we can ensure we haven't broken the functionality. 

Hope this helps...

**Comment by BLasan** [comment]
> Hi @BLasan - thanks for attempting this, but resolving this issue is a bit more complicated than just removing the offending lines as the calls to rs.previous() are there for a reason:
> 
> Currently the called function takes the ResultSet and extracts data until it finds a row that doesn't belong with the others. Then it reverses the cursor by 1 row with rs.previous(). That way when the control returns to the calling function, the cursor is set so that the calling function gets the first row of the next group by calling rs.next().
> 
> If we just remove the rs.previous(), then calling rs.next() in the calling function will give us the _second_ row of the next group, as we have already consumed the first row within the called function.
> 
> So one way to solve this would be to "flatten" the functions so that all work with the ResultSet is in same function - so that there is no need to pass rs.previous(). But to ensure that the "flattening" doesn't change the behaviour, it would be good to first have a test case which checks the functionality. Then when we refactor the function, we can ensure we haven't broken the functionality.
> 
> Hope this helps...

Hi. Please refer this. As far as know, initially it does not point to the first row of the selected data. This will give a clear idea
https://www.tutorialspoint.com/java-resultset-next-method-with-example

**Comment by ptuomola** [comment]
Hi @BLasan - no, the ResultSet initially doesn't point at the first row. But this is not a question about the initial position:  the same ResultSet is being iterated by both the calling function and the called function. The calling function expects the ResultSet to be returned in such state that by calling rs.next() it gets the next record to be processed. If you remove rs.previous() from the called function, that will no longer be the case and one record gets skipped. You can try it out by stepping through the code with a debugger and seeing what happens (as long as your JDBC driver supports rs.previous())

**Comment by BLasan** [comment]
> Hi @BLasan - no, the ResultSet initially doesn't point at the first row. But this is not a question about the initial position: the same ResultSet is being iterated by both the calling function and the called function. The calling function expects the ResultSet to be returned in such state that by calling rs.next() it gets the next record to be processed. If you remove rs.previous() from the called function, that will no longer be the case and one record gets skipped. You can try it out by stepping through the code with a debugger and seeing what happens (as long as your JDBC driver supports rs.previous())

Oh!! I didn't notice that. Thanks for the guidance. I'll take a proper look again. :)

**Comment by BLasan** [comment]
> Hi @BLasan - no, the ResultSet initially doesn't point at the first row. But this is not a question about the initial position: the same ResultSet is being iterated by both the calling function and the called function. The calling function expects the ResultSet to be returned in such state that by calling rs.next() it gets the next record to be processed. If you remove rs.previous() from the called function, that will no longer be the case and one record gets skipped. You can try it out by stepping through the code with a debugger and seeing what happens (as long as your JDBC driver supports rs.previous())

Hello @ptuomola , could you please mention the calling function of the extractData with regarding this issue? I was unable to find it as I'm new to the community. Could you please help me in finding this? :)

**Comment by BLasan** [comment]
@vorburger Sir, would you mind adding the steps to reproduce this issue?

**Comment by awasum** [comment]
@BLasan . This might be more complex than you think. Given that you are new to the community, Would you like to look at our JIRA board and pick beginner issues?
JIRA Dashboard: https://issues.apache.org/jira/secure/Dashboard.jspa?selectPageId=12335824

Beginner friendly issues: https://issues.apache.org/jira/browse/FINERACT-1012?filter=12349022

**Comment by vidakovic** [comment]
@BLasan do you see any chance that this PR gets done - let's say - in the next couple of days? Just asking, because of the upcoming release (important security fix). No worries, we'll have immediately another release on the heels of this one. Just to know for triaging the Jira issues.

**Comment by BLasan** [comment]
> @BLasan do you see any chance that this PR gets done - let's say - in the next couple of days? Just asking, because of the upcoming release (important security fix). No worries, we'll have immediately another release on the heels of this one. Just to know for triaging the Jira issues.

Shall I give an update tonight sir ? Need to reproduce this and check again

**Comment by BLasan** [comment]
@ptuomola @vorburger any idea?

**Comment by ptuomola** [comment]
> @ptuomola @vorburger any idea?

Hello @BLasan - any idea about what?

**Comment by BLasan** [comment]
> > @ptuomola @vorburger any idea?
> 
> Hello @BLasan - any idea about what?

Didn't get any issue in getting interest charts. Does this issue still occur?

**Comment by ptuomola** [comment]
> > > @ptuomola @vorburger any idea?
> > 
> > 
> > Hello @BLasan - any idea about what?
> 
> Didn't get any issue in getting interest charts. Does this issue still occur?

As far as I can see, the issue still exists. Not all JDBC drivers support resultset.previous(). It would make sense to refactor the logic so that previous() is not required.

**Comment by BLasan** [comment]
@ptuomola Would you mind adding the reproducing steps? Isn't it in the interest rate charts tab in FD creation?
Screenshot from 2021-03-22 14-47-29

**Comment by ptuomola** [comment]
@BLasan Sorry, I don't have steps to reproduce. You should be able to work them out by looking at the code? But that's what I would need to do to work out how to reproduce. 

This was originally reported by @vorburger as he saw it in the logs - if it's still happening on fineract.dev, he may be able to point to the account where this is happening to reproduce.

**Comment by BLasan** [comment]
> @BLasan Sorry, I don't have steps to reproduce. You should be able to work them out by looking at the code? But that's what I would need to do to work out how to reproduce.
> 
> This was originally reported by @vorburger as he saw it in the logs - if it's still happening on fineract.dev, he may be able to point to the account where this is happening to reproduce.

For this currently Fineract has used `rs.previous()` in iterating the result set. I think that's what @vorburger has reported. But there were no error getting back from the server when visit the interest chart tab (As far as I could remember this was related to a GET method)

**Comment by ptuomola** [comment]
If you look at the code, I think the call to rs.previous() only happens in case of having a specific combination of interest rate slabs / interest rates that are read from the database.

**Comment by BLasan** [comment]
> If you look at the code, I think the call to rs.previous() only happens in case of having a specific combination of interest rate slabs / interest rates that are read from the database.

Yuh, so the goal of this issue is to replace that with an appropriate one without affecting the functionality right?

**Comment by ptuomola** [comment]
Yes - so in all the cases where rs.previous() is currently called, the
output should be the same but without calling rs.previous()

**Pull request closed without merging**
