### PR TITLE
FINERACT-1029 Failing lint test for static

### PR DESCRIPTION
**Pull request by nnatarajan**
## Description
@vorburger 

From the static lint check, it appears that the variables created are not being used.

It is ok to delete the variables?

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by xurror — APPROVED** [review]
LGTM

**Comment by vorburger** [comment]
@nnatarajan would you be willing to resolve the merge conflicts which now appear here? Thanks! (It's just due to us having meanwhile merged other PRs; this sometimes happens when we work in parallel, and is somewhat unavoidable.)

**Comment by nnatarajan** [comment]
@vorburger 

How frustrating! Both checks passed on GitHub yesterday, earning xurror ok.

I was concerned that this would not get merged in time.

It seems with all the bulk changes today have resulted in merge conflicts, which will continue until completed.

Please let me know when the bulk changes are complete, then it will make sense to redo the 500 changes on my end.

I am hoping that I can revisit and resolve this tomorrow.

**Comment by vorburger** [comment]
Bulk changes for mass reformatting are now fully completed.

**Comment by nnatarajan** [comment]
@vorburger , resolved the merge conflicts.

**Pull request merged**
