### PR TITLE
clean up ClientSavingsIntegrationTest

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-891

### CODE REVIEW

**Comment by vorburger** [comment]
This failed due to what #764 will fixed (work around, deactivating test); let's rebase this once that is in.

**Comment by xurror** [comment]
This is still failing

**Comment by awasum** [comment]
https://github.com/apache/fineract/pull/764 has been merged. lets run this or rebase with develop and see.

**Comment by vorburger** [comment]
This one seems to have failed for other reasons than #761, perhaps my "cleanup" here wasn't all that clean? :smile: I need to look more into this, not right now but some other time, unless anyone else is interested in helping with this (this should, hopefully, be a much simpler just trivial mistake?):


```
> Task :integrationTest

org.apache.fineract.integrationtests.ClientSavingsIntegrationTest > testSavingsAccountPostInterestOnLastDayWithdrawalWithOverdraft FAILED
    java.lang.AssertionError at ClientSavingsIntegrationTest.java:1383

org.apache.fineract.integrationtests.ClientSavingsIntegrationTest > testSavingsAccountPostInterestOnLastDayWithOverdraft FAILED
    java.lang.AssertionError at ClientSavingsIntegrationTest.java:1042
```

**Comment by vorburger** [comment]
I want to leave this for anyone else interested to work on, and am "abandoning" this PR (and have un-assigned FINERACT-891; feel free to pick it up).

**Pull request closed without merging**
