### PR TITLE
remove leading and trailing spaces in report names (FINERACT-1327)

### PR DESCRIPTION
**Pull request by francisguchie**
## Description

Read in details here https://github.com/vorburger/fineract-pentaho/issues/9 and https://issues.apache.org/jira/browse/FINERACT-1327

Some report names under the stretchy report have names with trailing or leading spaces making which lead to errors during report spooling

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by vorburger — CHANGES_REQUESTED** [review]
@francisguchie I don't follow the details here, but if you say this helps, I'm happy to merge it... except for a small point - the V365 migration is (going to be) "taken" by #1663. Would you be willing to change this one to be V366?

**Comment by francisguchie** [comment]
@vorburger 

Yes i am willing to change it to V366

> @francisguchie I don't follow the details here, but if you say this helps, I'm happy to merge it... except for a small point - the V365 migration is (going to be) "taken" by #1663. Would you be willing to change this one to be V366?

**Comment by francisguchie** [comment]
@vorburger  its done

**Comment by vorburger** [comment]
This LGTM as is, but should only be (squash) merged AFTER #1663 (just because of the SQL version numbers).

**Pull request merged**
