### PR TITLE
FINERACT-1878 Update staff to read and write images to staff path

### PR DESCRIPTION
**Pull request by drew-dectech**
## Description
[FINERACT-1878](https://issues.apache.org/jira/browse/FINERACT-1878) - Update path for staff images

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@drew-dectech Kindly asking you to run the "./gradlew spotlessApply" on the project to get rid of the checkstyle issues.

**Review by galovics — CHANGES_REQUESTED** [review]
Please add tests to cover the proposed changes. Thanks.

**Comment by vidakovic** [comment]
@drew-dectech is this still being worked on or can we close this PR as it's quite stale?

**Comment by drew-dectech** [comment]
> @drew-dectech is this still being worked on or can we close this PR as it's quite stale?

@vidakovic Going to get the tests in today, sorry about that

**Comment by drew-dectech** [comment]
Added tests to cover the changes. Anything I can do to move this forward? @galovics

**Comment by galovics** [comment]
@drew-dectech I don't see the tests for the file repository.

**Comment by adamsaghy** [comment]
@drew-dectech Are you still working on this?

**Comment by jason-waale** [comment]
@adamsaghy @galovics, what's the process for me to pick up ownership of finishing this change?

**Comment by adamsaghy** [comment]
I am not sure, but i would say hence it was 6 month since he did anything in this PR:
- you might wanna take his changes and open a new PR, but please give him credit for the changes he did

@drew-dectech Are you okay with this approach or would you like to finish this PR?

**Pull request closed without merging**
