### PR TITLE
FINERACT-822 Enabling MultiVariableDeclaration check

### PR DESCRIPTION
**Pull request by percyashu**
FINERACT-822

### CODE REVIEW

**Comment by percyashu** [comment]
@xurror @awasum @vorburger LGTY?

**Comment by awasum** [comment]
@percyashu automatic Rebase failed. Looks like you will need to manually rebase or fix the conflicts before we can merge this. Are you on it?

**Comment by percyashu** [comment]
OK got it

**Review by awasum — APPROVED** [review]
LGTM

**Pull request merged**
