### PR TITLE
FINERACT-1410 :Allow Payment types to map to all types of Ledgers

### PR DESCRIPTION
**Pull request by ankita10r**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

Screenshot

### CODE REVIEW

**Comment by ptuomola** [comment]
Hello @ankita10r - very strange that Github is not running the Travis build for your pull request. Let me investigate why that's not happening.

**Comment by ankita10r** [comment]
@ptuomola I actually committed twice in order to make travis run, it still didn't. Not sure why. Appreciate you looking into this.

**Comment by ptuomola** [comment]
@ankita10r I think the Apache account for Travis has hit some sort of limit - you can see an error "Owner apache user license exceeded" here: https://app.travis-ci.com/github/apache/fineract/requests

I'll see if I can get any help from the Apache infra team

**Comment by ptuomola** [comment]
I've raised a ticket with the Apache Infra team - let's see if they can help with this.

**Comment by ptuomola** [comment]
Looks like TravisCI is working again. Let's wait to see if the build passes.

**Comment by awasum** [comment]
Issue here: https://issues.apache.org/jira/browse/FINERACT-1410

Please @ankita10r , can you create your JIRA account here: https://issues.apache.org/jira so that we can begin assigning you to issues you fix. 
CC @fynmanoj  and @avikganguly01

**Comment by avikganguly01** [comment]
Thank you @awasum for your guidance.

**Review by avikganguly01 — APPROVED** [review]

**Comment by awasum** [comment]
After merging this PR, Travis is failing on main.. Please, will you like help fix it? https://github.com/apache/fineract/runs/3962992775

**Comment by ptuomola** [comment]
FYI - the failure was due to the SonarQube PR which is different from this - fixed now by a new PR.

**Pull request merged**
