### PR TITLE
Added and Enforced RedundantModifier Checkstyle(2)(Fineract-821)

### PR DESCRIPTION
**Pull request by thesmallstar**
Previous PR: #1240 (This is in continuation to it)

### CODE REVIEW

**Review by ptuomola — APPROVED** [review]
LGTM. Travis build failed due to connection error. If you can retry the build and it passes, then I can merge this.

**Comment by thesmallstar** [comment]
Closing and reopening,

**Comment by thesmallstar** [comment]
@ptuomola  @vorburger  merge this?

**Comment by vorburger** [comment]
Cherry picking this big but essentially just "mechanical" diff to 1.4.0 still could make future maintenance to backport, if anyone wants to do that, significantly easier.. too late,vor still a good idea? @thesmallstar @vidakovic @ptuomola ?

**Pull request merged**
