### PR TITLE
FINERACT-821 Added multiple checkstyles

### PR DESCRIPTION
**Pull request by thesmallstar**
I feel sorry for someone who have to look and consider this PR :P , but anyways. 

So I came across this extremely cool repo: https://github.com/google/google-java-format
It formats java code according to google checkstyles(it is by google). 

It made out code look nicer, and helped implement some of the hardest to implement checkstyles otherwise(Even with plugins). 

Definitely not necessary to merge this, but what do you feel about it?
@vorburger  @awasum  @xurror  @ptuomola

### CODE REVIEW

**Comment by thesmallstar** [comment]
@vorburger  even if this looks good(highly unlikely :P), I will make a separate PR for each checkstyle :)

**Comment by thesmallstar** [comment]
Tests failed due to "Connection reset", closing and opening the PR again.

**Comment by vorburger** [comment]
> Definitely not necessary to merge this, but what do you feel about it?

I've opened new FINERACT-1006 for further discussion about the general topic of "Code Auto Formatting" which is what you are basically exploring here...

**Comment by thesmallstar** [comment]
Progress here: #943

**Pull request closed without merging**
