### PR TITLE
rm hardcoded system time from .travis.yml (fixes FINERACT-788)

### PR DESCRIPTION
**Pull request by vorburger**
see https://issues.apache.org/jira/browse/FINERACT-788

### CODE REVIEW

**Comment by vishwasbabu** [comment]
@vorburger , the date was hardcoded due to https://issues.apache.org/jira/browse/FINERACT-722 and the timezone was hardcoded due to https://issues.apache.org/jira/browse/FINERACT-723 .

**Comment by vorburger** [comment]
> @vorburger , the date was hardcoded due to https://issues.apache.org/jira/browse/FINERACT-722 and the timezone was hardcoded due to https://issues.apache.org/jira/browse/FINERACT-723 .

Hm, OK but between "Integration test cases fail when run on the 1st of a month" (FINERACT-722) and "Travis is just completely broken right now" (FINERACT-788) may be the former is the lesser of two evils? :smiling_imp: Or is there another better quick fix here that anyone can think of?

I guess we could keep (just) the `export TZ=Asia/Kolkata` - would that be better?

**Comment by vishwasbabu** [comment]
> Hm, OK but between "Integration test cases fail when run on the 1st of a month" (FINERACT-722) and "Travis is just completely broken right now" (FINERACT-788) may be the former is the lesser of two evils? 😈 Or is there another better quick fix here that anyone can think of?
> 
> I guess we could keep (just) the `export TZ=Asia/Kolkata` - would that be better?

Yes of course :) . We could also hard-code the date to "21 August 2019 01:02:03" and hope FINERACT-722 is fixed within the next 5 months !

**Comment by vorburger** [comment]
> > I guess we could keep (just) the `export TZ=Asia/Kolkata` - would that be better?

In a 2nd commit to this PR, I've just reverted that removal, so we keep `TZ` but rm `date`.

> We could also hard-code the date to "21 August 2019 01:02:03" 

Nah, that just postpones the problem - the same issue will just re-occur when services.gradle.org renews their cert the next time around... I really think we should avoid hard-coding a fixed time here (because of this problem).

> and hope FINERACT-722 is fixed within the next 5 months !

hope dies last! :smile_cat: 

I'll self merge this in 48h, unless someone else does before or suggests a better solution.

**Comment by awasum** [comment]
See new PR: https://github.com/apache/fineract/pull/914 which may be related to this...

**Pull request merged**
