### PR TITLE
Log only WARN & ERR but not INFO anymore (re. FINERACT-1168)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-1295

PS: Originally related to (but doesn't solve) FINERACT-1168, but can really be independently reviewed and merged - or not.

### CODE REVIEW

**Comment by ptuomola** [comment]
Just wondering... do we want to make this the default behaviour? Or just something that is used when running integration tests? I personally think seeing the INFO would be OK as normal behaviour (as that's what people would expect to see from other Spring Boot apps) - and we would just turn it off for Integration Tests. But not sure how easy that is to achieve?

**Comment by vorburger** [comment]
I thought about this, and while using it actually started liking it better like this, it's suddenly so... "quiet, and clean"! ;-) It also "feels" like it's "lighter" and"starts faster", although that's just "perception", of course. But YMMV. It's a bit like Maven (which verbosely logs everything it's doing) VS Gradle (which spews less logs). This also feels like it's more inline with our https://github.com/apache/fineract#logging-guidelines, notably the point about log levels. So my vote is on just changing this generally, not just for ITs, but I'm interested in how others feel about it.

**Comment by vorburger** [comment]
What do other recently active commiters think re this - pro or con? @vidakovic @avikganguly01 @fynmanoj @percyashu  @awasum

**Comment by xurror** [comment]
I understand this does not resolve https://issues.apache.org/jira/browse/FINERACT-1168 but I think this change only looks good if we can get https://issues.apache.org/jira/browse/FINERACT-764. So, just a thought instead having a foreplay with this logging why not just package it with https://github.com/apache/fineract/pull/1444 or bring it in after.
But overall, I think it's a good fit though.

**Comment by avikganguly01** [comment]
@vorburger : Logstash scripts in some older implementations will break if we upgrade but that's fine.

**Comment by vorburger** [comment]
@avikganguly01 do you think it's useful to have INFO logs and has any real world in your logstash? My experience in running Fineract.dev and using Google Error Reporting has been that all I ever look at and seem to care about is WARN and ERROR... (BTW note all the issues linked from FINERACT-932 which I've been able to find! Do you want to contribute fixes for some of them?)

**Comment by ptuomola** [comment]
@vorburger just to be clear, I'm happy either way... haven't tried this to see how much cleaner it is, but at the same time I don't think there's a huge amount of useful information in the INFO logging either.

**Comment by vorburger** [comment]
FINERACT-1295

**Comment by vorburger** [comment]
I'm "self merging" this, given that nobody objected on https://lists.apache.org/thread.html/r9e3de9996a7f9f1bd49615b5a7d44f6c8daeca5cbccdac2967233bbd%40%3Cdev.fineract.apache.org%3E

**Pull request merged**
