### PR TITLE
FINERACT-1166: Fix build to work outside git repository

### PR DESCRIPTION
**Pull request by ptuomola**
## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by ptuomola** [comment]
Hmm... I don't think the build failure has anything to do with this change - can't see how changing the config file for Swagger would suddenly make the scheduler fail. Will check if I can replicate this locally.

**Comment by vorburger** [comment]
Let's just rebuild this, so that we can merge this fix rather sooner than later? I'll close and re-open, hoping for a new build.

I've just opened FINERACT-1167 about the failing test, and FINERACT-1168 about the root cause of why debugging this kind of failure is a PITA.

**Comment by vorburger** [comment]
@ptuomola duh, failed again! Time to re-open FINERACT-886? :cry:

**Review by vorburger — APPROVED** [review]
LGTM

**Pull request merged**
