### PR TITLE
add link to Web UIs, Mobile App, and fineract.dev

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
#783 ignores the failing test.  I'm closing and re-opening to see if it passes.

@awasum do you want to review and Rebase and Merge this REVIEW change?

**Comment by awasum** [comment]
Seems there is a problem.

```
org.apache.fineract.integrationtests.RecurringDepositTest > testRecurringDepositAccountWithPrematureClosureTypeReinvest FAILED
    java.lang.AssertionError at RecurringDepositTest.java:3048
```

**Comment by awasum** [comment]
Here is the problem: https://travis-ci.org/github/apache/fineract/builds/677887476

**Comment by vorburger** [comment]
#784

**Comment by vorburger** [comment]
@nikpawar89 @xurror thanks for your interest and votes of support for the README change in #782. 

How do you feel about this one?

**Comment by nikpawar89** [comment]
@vorburger  just thinking out loud- do we want to mention https://github.com/openMF/mifosx for pentaho reports related module?  otherwise +1 from me.

**Review by xurror — APPROVED** [review]
LGTM

**Comment by awasum** [comment]
> @vorburger just thinking out loud- do we want to mention https://github.com/openMF/mifosx for pentaho reports related module? otherwise +1 from me.

Hmm..Good one...But pentaho reports with current Fineract is even broken.

**Comment by vorburger** [comment]
> @vorburger just thinking out loud- do we want to mention https://github.com/openMF/mifosx for pentaho reports related module? 

No, I'm actively against that, because I fear that could create a lot more confusion than answer anyone's question... that repo de facto is "dead", given that it hasn't been updated in 4 years, and IMHO we shouldn't refer to it anymore from Fineract's README (other than perhaps from a "Historical" section for archaeologists, if anyone would like to add something like that).

I do understand the (old) issue about Pentaho-based reports having been "lost" in the move to Apache. That is a problem I suspect someone will want to address somehow, someday (with a separate additional service, perhaps?), but this PR is not the place for that? 

Anyway, strictly speaking, https://github.com/openMF/mifosx is course not the "pentaho reports related module", but a (now very old) predecessor version of the same code that is in this repo. (You cannot "use" that "module" with fineract, just like that.)

> otherwise +1 from me.

Ok, then based on that +1 and @xurror approval, let's merge this, if OK for you as-is @awasum ?

PS: Build failed again due to another FINERACT-885 - I'll deal with that separately, let's not hold this up.

**Comment by awasum** [comment]
Go ahead. @vorburger

**Pull request merged**
