### PR TITLE
Added ReadinessProbe for mysql container (FINERACT-1292)

### PR DESCRIPTION
**Pull request by BLasan**
FINERACT-1292

## Description

Added ReadinessProbe configuration values for MySql container.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by BLasan** [comment]
@xurror Travis build fails. Is this due to the issue[ FINERACT-887 ](https://issues.apache.org/jira/browse/FINERACT-887)?

**Comment by BLasan** [comment]
@vorburger @xurror Could you please suggest a way to get rid of this travis build issue? I rebased the code to the latest but still getting this issue

**Comment by vorburger** [comment]
@BLasan you need to follow the process outlined on https://github.com/apache/fineract#pull-requests please

**Comment by vorburger** [comment]
FINERACT-924

**Review by vorburger — APPROVED** [review]
LGTM; this makes sense, to me (but I've not actually tested it). @xurror do you want to review and merge this?

**Comment by BLasan** [comment]
@xurror please review

**Comment by vorburger** [comment]
@xurror without hearing back from you, I'll merge this one in 3 days. (It's obviously totally fine if you are busy, no stress; we just want to give new contributors a chance to make an impact in this project.)

**Review by xurror — APPROVED** [review]
Thanks @vorburger for drawing my attention on this again.
This looks good. 
I'm merging it myself now.

**Pull request merged**
