### PR TITLE
Fixes broken build due to spotless and error-prone

### PR DESCRIPTION
**Pull request by thesmallstar**

### CODE REVIEW

**Review by vorburger — APPROVED** [review]
LGTM. Will merge as soon as build passed.. Thank You!

**Comment by thesmallstar** [comment]
Error-prone needs a fix, looking into it.

**Review by vorburger — CHANGES_REQUESTED** [review]
Build still failed (just changing Approve to Request Changes to avoid another commiter merging this by mistake).

**Comment by percyashu** [comment]
@thesmallstar I think if you fix the current 1 problem, the compileIntegrationTest may yield no violation.

**Comment by thesmallstar** [comment]
@percyashu yes :) Let's see what Travis says now.

**Comment by percyashu** [comment]
LGTM

**Review by vorburger — APPROVED** [review]

**Pull request merged**
