### PR TITLE
FINERACT-384 - Product Mix - for Saving Accounts

### PR DESCRIPTION
**Pull request by ippezshelby**

### CODE REVIEW

**Comment by nazeer1100126** [comment]
Changes Looks OK. But instead of writing code similar to existing loan product mix implementation, you should have extended by adding entity type. By extending existing implementation, you should have avoided lot of duplicate/similar code.

**Comment by avikganguly01** [comment]
@Ippezrobert : Thank you for the contribution. Would you be able to extend the existing implementation to remove the duplicate code?

**Comment by vorburger** [comment]
@Ippezrobert thank you very much for your interest in Mifos!  I'm an (old) volunteer who got reminded of Mifos this week-end at the FOSDEM conference, and I'm taking a moment to help the project clean up some of it's old issues and pull requests etc.  

We were wondering whether you are still alive, and would be willing to rebase this PR and take any previous review feedback into account?  If we don't hear from you within 2 weeks, we will take the liberty to close this PR, to avoid confusion for future new contributors looking at this repository - hope you understand and that's fair.

**Comment by vorburger** [comment]
Friendly service reminder: I will close this PR in 3 days to help this project have a clean list of active PRs.

**Pull request closed without merging**
