### PR TITLE
FINERACT-1724: Added test cases to test GetNextRecurringDate method in CalendarUtils

### PR DESCRIPTION
**Pull request by DheerajKumar19**
[FINERACT-1724](https://issues.apache.org/jira/browse/FINERACT-1724) 
This PR was intended to add a test case for a function which was not already covered within the existing test suite.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by galovics** [comment]
@DheerajKumar19 can you pls squash your commits into a single one? Also, add a respective FINERACT JIRA ticket into the PR title and the commit's message as a prefix. Thanks.

**Comment by DheerajKumar19** [comment]
There is no jira ticket linked to this. And I have no access to create a jira ticket. This PR was intended to add a test case for a function which has no test case coverage as a part of our course project.

**Comment by adamsaghy** [comment]
@DheerajKumar19 You might wanna use FINERACT-1724 then. (minor fixes and upgrades for 1.9 version)

**Comment by DheerajKumar19** [comment]
Thank you will add this as my ticket!

**Comment by DheerajKumar19** [comment]
@adamsaghy I have resolved all the review comments.

**Comment by galovics** [comment]
@DheerajKumar19 please fix the build. As you can see they are failing.

**Comment by adamsaghy** [comment]
@DheerajKumar19 please run `checkstyleTest` on to see the problems.

**Pull request closed without merging**
