### PR TITLE
upgrade OpenJPA from 3.1.0 to 3.1.1 (FINERACT-908)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-908

### CODE REVIEW

**Comment by vorburger** [comment]
@awasum @xurror @nemux (https://github.com/apache/openjpa/pull/61 yay!) @nikpawar89 @rrpawar96 @maektwain OK to merge this?

**Comment by maektwain** [comment]
Ok 👌

**Comment by nemux** [comment]
Agree!  👌

**Comment by awasum** [comment]
Good to gooo

**Pull request merged**
