### PR TITLE
use throw instead of confusing return null inside catch

### PR DESCRIPTION
**Pull request by vorburger**
in JournalEntryWritePlatformServiceJpaRepositoryImpl

### CODE REVIEW

**Comment by vorburger** [comment]
@awasum how about this? It's apparently done wrong (pattern) in many classes in the code.

@maektwain FYI

**Comment by maektwain** [comment]
Gotcha , should I wait for this to be merged?

**Comment by maektwain** [comment]
We should gtmit

**Comment by vorburger** [comment]
@maektwain I've just self merged it, assuming no objections, to unblock you so that you can rebase.

**Pull request merged**
