### PR TITLE
remove TODO Auto-generated method stub

### PR DESCRIPTION
**Pull request by xurror**
## Description
Removed an already implemented trailing TODO task from the code base

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vorburger** [comment]
@xurror thanks for this first contribution! The build failed just because of [FINERACT-800](https://issues.apache.org/jira/browse/FINERACT-800). Could you rebase this when #657 has been merged?

**Comment by awasum** [comment]
@xurror  Rebase this now as #657  has been merged. Thanks.

**Comment by awasum** [comment]
Will merge this now. Thanks for your contribution @xurror . Please, Pick other issues and try to fix them. Ask for help on mailing list if you get into problems.

**Comment by xurror** [comment]
When I try rebasing, I notice alot of conflicting commits.
When I try adding the incoming conflicting commits, the build fails but when I skip the conflicts, I fall 9 commits behind the upstream develop but all builds go well.

Is this a normal behaviour?

On Mon, 25 Nov 2019 at 09:00, Awasum Yannick <notifications@github.com<mailto:notifications@github.com>> wrote:

Merged #655<https://github.com/apache/fineract/pull/655> into develop.

**Comment by awasum** [comment]
This is already merged...just go back to your develop branch and pull from upstream develop.

**Comment by xurror** [comment]
Ok thanks


On Mon, 25 Nov 2019 at 13:08, Awasum Yannick <notifications@github.com<mailto:notifications@github.com>> wrote:

This is already merged...just go back to your develop branch and pull from upstream develop.

**Pull request merged**
