### PR TITLE
remove org.gradle.daemon=false (FINERACT-948)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-948

### CODE REVIEW

**Comment by vorburger** [comment]
@ptuomola @awasum @xurror let's try this? 

We (anyone, not only me) can always raise a revert PR, if we find it to be more trouble than beneficial...

**Comment by awasum** [comment]
Failure:

`
> Task :compileIntegrationTestJava
/home/travis/build/apache/fineract/fineract-provider/src/integrationTest/java/org/apache/fineract/integrationtests/StaffTest.java:135: warning: [unchecked] unchecked cast
        final List<HashMap> responseActive = (List<HashMap>)StaffHelper.getStaffListWithState(requestSpec, responseSpec, "active");
                                                                                             ^
  required: List<HashMap>
  found:    Object
/home/travis/build/apache/fineract/fineract-provider/src/integrationTest/java/org/apache/fineract/integrationtests/StaffTest.java:144: warning: [unchecked] unchecked cast
        final List<HashMap> responseInactive = (List<HashMap>)StaffHelper.getStaffListWithState(requestSpec, responseSpec, "inactive");
                                                                                               ^
  required: List<HashMap>
  found:    Object
2 warnings
`
See Travis log: https://travis-ci.org/github/apache/fineract/builds/684752992

Seems another Integration Test is Flaky?

**Comment by vorburger** [comment]
> Seems another Integration Test is Flaky?

Yes, but not what you noticed, that one is just a warning - and #842 fixes that.

The IT failure here is FixedDepositTest > testFixedDepositAccountClosureTypeWithdrawal_WITH_HOLD_TAX - I've just created FINERACT-950 and raised #843.

**Comment by awasum** [comment]
Thank you.

**Pull request merged**
