### PR TITLE
FINERACT-1724 Refactor Logging: Transition from java.util.logging to SLF4J

### PR DESCRIPTION
**Pull request by Onyx2406**
## Description

Describe the changes made and why they were made.

Refactored Logging: Transition from java.util.logging to SLF4J

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@Onyx2406 Please amend the commit message and your PR title by adding a relevant FINERACT jira number. You might wanna use FINERACT-1724 (it contains small bugfixes and enhancements).

**Comment by adamsaghy** [comment]
@Onyx2406 Please fix the failing compilation!

**Comment by Onyx2406** [comment]
@adamsaghy can you please re-run the tests? It should pass now. Thanks!

**Comment by vidakovic** [comment]
@Onyx2406 ... how about doing all this with Lombok annotations ("@Slf4j", lower case "log" etc.)?

**Comment by Onyx2406** [comment]
> @Onyx2406 ... how about doing all this with Lombok annotations ("@slf4j", lower case "log" etc.)?

Yes, that would work as well using Lombok annotations as implemented in some other files. I used upper case "LOG" as it is the convention provided in the readme file examples. So, it's not case sensitive. I've also noticed that we are using a variety of logging methods across the project, such as "LOG", "log", and utilizing both lombok.extern.slf4j.Slf4j and org.slf4j.Logger.

So let me know if I should implement that way.

**Review by galovics — APPROVED** [review]

**Pull request merged**
