### PR TITLE
FINERACT-1714: Capitalized titles and line breaks

### PR DESCRIPTION
**Pull request by david-kariuki**
Capitalize major titles and add line breaks to increase readability

### CODE REVIEW

**Comment by adamsaghy** [comment]
@david-kariuki Please attach a FINERACT jira story number to your PR and commit!

**Comment by adamsaghy** [comment]
@david-kariuki Please squash you commits!

**Comment by david-kariuki** [comment]
> @david-kariuki Please attach a FINERACT jira story number to your PR and commit!

How do I go about this? I made these changes on Github's markdown editor.

**Comment by adamsaghy** [comment]
@david-kariuki I dont think you can do it from there. Is it possible to checkout the project into your machine and squash the commits and push them back for you?

**Comment by david-kariuki** [comment]
> @david-kariuki Please squash you commits!

Done

**Comment by adamsaghy** [comment]
@david-kariuki Unfortunately, we cannot merge this into this way. When you merged the latest changes into your branch, you havent rebased it, rather used merge strategy. The problem is this way it would override the develop branch git history...That is the reason why it shows all the changes which were done by others as part of your PR.

Would you please checkout the latest version of develop and apply your changes on it? Or rebase your branch with the latest develop branch?

**Comment by david-kariuki** [comment]
I will checkout from the latest version and make new changes. Thank you.

**Pull request closed without merging**
