### PR TITLE
FINERACT-1113 add total_recovered_derived field to LoanSummaryData object

### PR DESCRIPTION
**Pull request by tonic889**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ X] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [X ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ X] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ X] Integration tests have been created/updated for verifying the changes made.

- [ X] All Integrations tests are passing with the new commits.

- [ X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by awasum** [comment]
@percyashu , @thesmallstar , Will you like to review this one?

**Review by percyashu — COMMENTED** [review]
@tonic889 this PR is the initial step to [cui-2225](https://github.com/openMF/community-app/issues/2225) right? With this addition will [cui-2225](https://github.com/openMF/community-app/issues/2225) be resolved? I would recommend you do them together to find out if  this PR and logic proposed **bharathcgowda**, [cui-2225](https://github.com/openMF/community-app/issues/2225)  will be resolved.

**Comment by tonic889** [comment]
@percyashu @luckyman20 Yes this is the fineract side change for cui-2225.  @luckyman20 have you already done the community app changes for this?  if so, are you able to test against this PR? totalRecovered amount has been added to the loan summary, you would only have to compare this with totalWrittenOff to hide the button as you have suggested. or if you prefer I can do the community app side change too.

**Comment by luckyman20** [comment]
We can merge this ahead of community-app changes as this is only an addition to the fineract. I will create the PR on community-app after this is merged.

**Comment by thesmallstar** [comment]
@tonic889 thanks for the PR,
Will you also like to write a test for this (not necessarily now, but later maybe?)

**Review by ptuomola — APPROVED** [review]
LGTM

**Comment by luckyman20** [comment]
@vorburger @ptuomola Is it good to merge? If yes, then I think we shouldn't delay it.

**Comment by ptuomola** [comment]
@luckyman20 I was waiting for a reply to the question from @thesmallstar above... but the code looks OK to me, so happy to merge.

**Comment by vorburger** [comment]
Please make sure that the Fix Version on issues for merged PRs is set (this one in FINERACT-1113 was not); else they'll miss in the Release Notes.

**Pull request merged**
