### PR TITLE
add spring-boot-starter-actuator dependency

### PR DESCRIPTION
**Pull request by vorburger**
see https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html

### CODE REVIEW

**Comment by vorburger** [comment]
see #619 for one possible use of this - but I think it's handy more generally.

Would anyone have any concerns / objections to adding this?

**Comment by mohitsinha** [comment]
The endpoints exposed by this particular version of actuator should be safe. Or, we can manually configure the endpoints that we need.

**Comment by vorburger** [comment]
Travis CI Build Failure is totally unrelated to this change, let's discuss that in [FINERACT-779](https://jira.apache.org/jira/browse/FINERACT-779) ...

**Comment by vorburger** [comment]
> Travis CI Build Failure is totally unrelated to this change, let's discuss that in [FINERACT-779](https://jira.apache.org/jira/browse/FINERACT-779) ...

No, it actually was due to this change, see details in [FINERACT-779](https://jira.apache.org/jira/browse/FINERACT-779); I've now amended this PR with a change to the logging configuration which should hopefully make this PR pass the Travis build.

**Comment by vorburger** [comment]
@awasum @conradsp review and merge this one, whenver you have a moment? (Not urgent.)

**Comment by conradsp** [comment]
Looks good - but wondering if we should be logging at debug level for the actuator? Should we change that to info?

**Comment by vorburger** [comment]
That logs too much, and fails Integration Test on Travis .. (more recent
Spring versions changed that particular log from info to debug).

**Comment by conradsp** [comment]
Thanks for the clarification. I will merge.

**Pull request merged**
