### PR TITLE
client: serialize LocalDate as 2009-01-01 (FINERACT-1234)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-1234

### CODE REVIEW

**Comment by vorburger** [comment]
What we really should do is FIRST merge #1453 (when green), then rebase this - to make sure no broken build.

**Comment by vorburger** [comment]
This PR "includes" #1452. You can already review it by just looking at the 2nd commit only.

**Comment by vorburger** [comment]
> This PR "includes" #1452. You can already review it by just looking at the 2nd commit only.

@ptuomola @vidakovic build now passed, this is ready for review (note comment above).

**Comment by vorburger** [comment]
Ignore failed _continuous-integration/travis-ci/push_ (again just because I pushed to the wrong remote), consider only _[continuous-integration/travis-ci/pr](https://travis-ci.org/github/apache/fineract/builds/737717956)_.

**Comment by vorburger** [comment]
@ptuomola @vidakovic build now passed, this is ready for review (note comment above).

**Comment by vorburger** [comment]
@ptuomola @vidakovic so this one would be next in my... "streak" :smile: Does this LGTY? (Whenever you get to it - no stress.)

**Review by vidakovic — APPROVED** [review]
LGTM

**Review by ptuomola — APPROVED** [review]
LGTM

**Pull request merged**
