### PR TITLE
Notification sub-system

### PR DESCRIPTION
**Pull request by cnangeh**
Work done:

- [x] User subscription to topic on user creation
- [x] Topic creation on entity creation
- [x] Upgrade process of user notification
- [x] Migration script - topic, topic subscription models for new and already existing users and entities
- [x] Update user subscription on user transfer and/or update of user's permission
- [x] Update topic details when entity details updates
- [x] Update topic details when member type are updated at the system level
- [x] Unit test topic-subscriber model
- [x] Added Spring Events to be used in place where ActiveMQ is absent

### CODE REVIEW

**Comment by nazeer1100126** [comment]
@Anh3h Instead of modifying existing services, can you implement in such a way, if notification feature is enabled, another subscriber(s) should do the required actions.

**Comment by cnangeh** [comment]
@nazeer1100126 Existing services like?
Cause what I actually do is check is activemq is active on system before enabling it on fineract

**Comment by nazeer1100126** [comment]
@Anh3h For example, these are some of existing services.
RoleWritePlatformServiceJpaRepositoryImpl.java
AppUserWritePlatformServiceJpaRepositoryImpl.java
OfficeWritePlatformServiceJpaRepositoryImpl.java

**Comment by cnangeh** [comment]
Okay. I will work on that

**Comment by avikganguly01** [comment]
@Anh3h : Great to see that you covered spring events, can you fix the conflicts so that this can be pulled in?

**Comment by avikganguly01** [comment]
@Anh3h : I have taken the liberty of rebasing your code, fixing a minor conflict and merging it. Closing this PR as well as your previous open PR which I believe is a subset of this PR.

**Pull request closed without merging**
