### PR TITLE
Activate and Enforce new Checkstyle check related to import statement order (FINERACT-821)

### PR DESCRIPTION
**Pull request by vorburger**
Please see the individual commit message for details about the steps.

Note how the reformatting and other changes are in separate commit, to ease review of this PR.

### CODE REVIEW

**Comment by vorburger** [comment]
@awasum hey how do you like this? :smiling_imp: 

FYI full disclosure :smile_cat:  you actually motivated me to finally do this, because I noticed while I was just reviewing your #701 earlier again that in many PRs in this project there are always a bunch of import order related changes, not specific to upgrading e.g. Spring Boot or whatever the PR is about (I've run into this in other PRs in the past). In other projects I'm used to working on, this is a total non-issue, because...

... in my experience, fixing an import order convention (any one, in the end it does not really matter which one; this one IMHO is just simply the most simple and logical one, even if it takes a second to get used to it, but then it feels natural), then doing a bulk re-ordering once, and from then onwards enforcing it (which this also does), and... bingo - no more arbitrary import order changes in PRs! (Because people have to fix them, otherwise their PR's build fails.)

**Comment by awasum** [comment]
> @awasum hey how do you like this? 
> 
> FYI full disclosure  you actually motivated me to finally do this, because I noticed while I was just reviewing your #701 earlier again that in many PRs in this project there are always a bunch of import order related changes, not specific to upgrading e.g. Spring Boot or whatever the PR is about (I've run into this in other PRs in the past). In other projects I'm used to working on, this is a total non-issue, because...
> 

Super useful, I use IntelliJ from Jetbrains. I usually natural use Optimize Import (CTRL + ALT + O) whenever I finish working with a class each time. I dont know how I developed that instinct...Maybe I saw it somewhere in open source and it clicked. 

For something which enforces this Import Optimization rule, do you know if we could get somethign similar for IntelliJ (a EPF compatible) type of config for Fineract on IntelliJ to enforce our preferences.
Is that even something of value to the project? Probably not. And is something which should not really go with this PR.

Once this passes Travis, I will just merge it, as long as am not asleep by then..

**Comment by awasum** [comment]
Travis error: ```ERROR: Service 'fineract-server' failed to build: The command '/bin/sh -c wget https://repo1.maven.org/maven2/org/drizzle/jdbc/drizzle-jdbc/1.4/drizzle-jdbc-1.4.jar' returned a non-zero code: 8```

Looks like when trying to get drizzle driver, return type of HTTP request is 403...II dont know why. Maybe we close and open for Travis to run again and lets see if this will pass.

**Comment by awasum** [comment]
See: https://travis-ci.org/apache/fineract/builds/642603388#L9768

**Comment by awasum** [comment]
image

`wget https://repo1.maven.org/maven2/org/drizzle/jdbc/drizzle-jdbc/1.4/drizzle-jdbc-1.4.jar`
actually works on my local Ubuntu 16.04 System.

**Review by awasum — APPROVED** [review]
Looks good to me. Merging.

**Pull request merged**
