### PR TITLE
FINERACT-1932: Add custom Configuration class for shareproduct services

### PR DESCRIPTION
**Pull request by mmagdiab**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by galovics — APPROVED** [review]

**Comment by adamsaghy** [comment]
@mmagdiab Please kindly check the below error:
```
    (see https://errorprone.info/bugpattern/NonApiType)
/home/runner/work/fineract/fineract/fineract-provider/src/main/java/org/apache/fineract/portfolio/shareproducts/starter/ShareProductsConfiguration.java:36: error: [WildcardImport] Wildcard imports, static or otherwise, should not be used
import org.apache.fineract.portfolio.shareproducts.service.*;
^
```

**Comment by mmagdiab** [comment]
> @mmagdiab Please kindly check the below error:
> 
> ```
>     (see https://errorprone.info/bugpattern/NonApiType)
> /home/runner/work/fineract/fineract/fineract-provider/src/main/java/org/apache/fineract/portfolio/shareproducts/starter/ShareProductsConfiguration.java:36: error: [WildcardImport] Wildcard imports, static or otherwise, should not be used
> import org.apache.fineract.portfolio.shareproducts.service.*;
> ^
> ```

resolved

**Comment by vidakovic** [comment]
@mmagdiab could you please resolve these conflicts?

**Comment by mmagdiab** [comment]
Conflicts resolved.

**Review by vidakovic — APPROVED** [review]
LGTM

**Pull request merged**
