### PR TITLE
FINERACT-971 Added and enforced AvoidNoArgumentSuperConstructorCall Checkstyle

### PR DESCRIPTION
**Pull request by thesmallstar**
FINERACT-971

### CODE REVIEW

**Review by vorburger — CHANGES_REQUESTED** [review]
@thesmallstar I like the removal of the `super()`, but why did you also make few classes `final`? Especially for JPA Entities like `Teller extends AbstractPersistableCustom` I'm not sure that's a good idea, with all the magic bytecode enhancement from OpenJPA, and the planned move to EclipseLink.

**Review by vorburger — CHANGES_REQUESTED** [review]
@thesmallstar I like the removal of the `super()`, but why did you also make few classes `final`? Especially for JPA Entities like `Teller extends AbstractPersistableCustom` I'm not sure that's a good idea, with all the magic bytecode enhancement from OpenJPA, and the planned move to EclipseLink.

**Comment by thesmallstar** [comment]
@vorburger  that had to be done due to other checkstyle. Since I removed the public constructor, I will instead only remove super() so that they don't have to be made final.

**Comment by vorburger** [comment]
@thesmallstar how is finishing this up coming along?

**Comment by thesmallstar** [comment]
@vorburger I am about to make a PR for sqlSearch and will fix this today itself :)

**Review by vorburger — APPROVED** [review]
LGTM

**Pull request merged**
