### PR TITLE
[FINERACT-1690]Improve gitpod integration

### PR DESCRIPTION
**Pull request by mwaaas**
## Description

Fixing https://issues.apache.org/jira/browse/FINERACT-1690

### CODE REVIEW

**Comment by vidakovic** [comment]
@mwaaas could you please:
- squash the commits?
- if there's no JIra ticket: please create one and format the PR title according to the general rules ("FINERACT-XXXX: ...")

Thanks

**Comment by mwaaas** [comment]
@vidakovic thanks for the quick response. I have done as suggested. 

Out of curiosity why squash commits, while they could be squashed during merge?

**Comment by vidakovic** [comment]
@mwaaas ... because we don't merge, we "rebase and merge"... check the buttons here and you'll see there is no "squash and rebase". When you squash then there's no accidental merging of multiple commits (usually it's not that interesting how you got to your solution, just that you have it)... and - if I'm not mistaken - if I squash and merge via Github's UI then GH prompts me again to choose a commit message.

So... in general... it's just more convenient... thanks for squashing.

**Comment by vidakovic** [comment]
@mwaaas ... just one more: I think you chose the wrong Jira project? It's "FINERACT" not "AAR".

**Comment by mwaaas** [comment]
> @mwaaas ... just one more: I think you chose the wrong Jira project? It's "FINERACT" not "AAR".

My bad I have rectified the mistake

**Review by galovics — APPROVED** [review]
LGTM

**Pull request merged**
