### PR TITLE
Change /authentication API to pass data in request body instead of URL arguments (FINERACT-726)

### PR DESCRIPTION
**Pull request by vorburger**
see https://issues.apache.org/jira/browse/FINERACT-726

### CODE REVIEW

**Comment by awasum** [comment]
How will this affect the UI? will the UI break after we merge this? https://github.com/openMF/community-app

**Comment by vorburger** [comment]
> How will this affect the UI? will the UI break after we merge this?

I've just emailed you privately re. this.

Re. the build failure, I'm curious if this passes when we retry tomorrow.. see https://issues.apache.org/jira/browse/FINERACT-820.

**Comment by vorburger** [comment]
@awasum build failure went away simply by retrying.. want to review this?

**Comment by awasum** [comment]
> @awasum build failure went away simply by retrying.. want to review this?

Its now monday. lol

**Review by awasum — APPROVED** [review]

**Comment by piotratmines** [comment]
@awasum, @vorburger Hello gentleman, so is the community-app working with the changes?

**Pull request merged**
