### PR TITLE
add /rebase comment support for Pull Requests (FINERACT-829)

### PR DESCRIPTION
**Pull request by vorburger**
https://github.com/marketplace/actions/automatic-rebase

https://github.com/cirrus-actions/rebase

@awasum and anyone else reading this, how about adding this?

### CODE REVIEW

**Comment by vorburger** [comment]
#693 will fix the build failure seen here

**Comment by awasum** [comment]
@vorburger Do we need this documented somewhere on the readme. It can be done after this has been merged if you want. Looks like just writing /rebase in a PR comment should activate this action and rebase the PR. Is this correct?

**Review by awasum — APPROVED** [review]

**Comment by vorburger** [comment]
self merging this one based on @awasum comment in #692 ("no experience with Github Actions. Merge when you feel comfortable with this.") - I don't expect any other committers could have a problem with this.

**Comment by vorburger** [comment]
> @vorburger Do we need this documented somewhere on the readme. It can be done after this has been merged if you want. Looks like just writing /rebase in a PR comment should activate this action and rebase the PR. Is this correct?

Yeah, but doesn't seem to quite work yet.. watch https://issues.apache.org/jira/browse/FINERACT-829.  Once it does work, I'll announce it on the mailing list. We can also add it to the README, good idea. (Though in practice I think folks typically "learn" about such things less by reading about it in doc and more through seeing others use it in PRs and then by copy cat...)

**Pull request merged**
