### PR TITLE
Fix all months installments getting reshceduled in ApplyHolidaysToLoans rescheduling loan to specific date (FINERACT-2017)

### PR DESCRIPTION
**Pull request by 2vinodhkumar**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by bharathcgowda** [comment]
@adamsaghy  can you please help us in reviewing this PR?

**Comment by adamsaghy** [comment]
@2vinodhkumar Please fix the title and the commit message to fit for the required format:
"FINERACT-XXXX: short description"

Also please squash your commits: 1 PR 1 commit only!

Also please add at least one test case (integration test) which proves this fix is working!

**Review by adamsaghy — CHANGES_REQUESTED** [review]
@2vinodhkumar Please fix the title and the commit message to fit for the required format:
"FINERACT-XXXX: short description"

Also please squash your commits: 1 PR 1 commit only!

Also please add at least one test case (integration test) which proves this fix is working!

**Comment by adamsaghy** [comment]
Seems like we have a contester for the same story :)
https://github.com/apache/fineract/pull/3645

**Comment by adamsaghy** [comment]
I am closing hence someone else was already fixed it and it got merged

**Comment by 2vinodhkumar** [comment]
> Seems like we have a contester for the same story :) #3645

@adamsaghy  It seems is not yet fixed. Can you please confirm? If not let me know I can continue on this...

**Comment by adamsaghy** [comment]
> > Seems like we have a contester for the same story :) #3645
> 
> 
> 
> @adamsaghy  It seems is not yet fixed. Can you please confirm? If not let me know I can continue on this...

I believe it was fixed.

**Pull request closed without merging**
