### PR TITLE
FINERACT-1960: Add flag to Savings Charges to be recognized as accrual income

### PR DESCRIPTION
**Pull request by josehernandezfintecheandomx**
## Description

In order to implement [Periodic Accrual accounting for Savings products](https://cwiki.apache.org/confluence/plugins/servlet/mobile?contentId=66852861#content/view/66852861) we have  added a flag to Savings Charges to It can be recognized or not as accrual income.

The API for charges was updated to support this new parameter `recognizedAsAccrualIncome` and It will be only required for the Savings charges, the other charges for other products remain as current and the default value for this will be `false` 

[FINERACT-1960](https://issues.apache.org/jira/browse/FINERACT-1960)

- API Charge screenshot
Screenshot 2023-07-29 at 12 02 49

- Integration Tests
Screenshot 2023-07-29 at 13 52 27

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@josehernandezfintecheandomx Can you please link the relevant FINERACT story for this change?
@bharathc27 Could you please review the business need after it got linked?

**Review by adamsaghy — CHANGES_REQUESTED** [review]
I dont like the idea to add `recognizedAsAccrualIncome` parameter, hence all the charges are recognized as income by default. 

Here the value would be by default `false` which is wrong for loan charges for example.

Can you please help me to understand better this changes and the business requirement it supports?

**Comment by josehernandezfintecheandomx** [comment]
> I dont like the idea to add `recognizedAsAccrualIncome` parameter, hence all the charges are recognized as income by default.
> 
> Here the value would be by default `false` which is wrong for loan charges for example.
> 
> Can you please help me to understand better this changes and the business requirement it supports?

@adamsaghy I've updated the description with the Jira ticket https://issues.apache.org/jira/browse/FINERACT-1960

**Comment by adamsaghy** [comment]
> > I dont like the idea to add `recognizedAsAccrualIncome` parameter, hence all the charges are recognized as income by default.
> > Here the value would be by default `false` which is wrong for loan charges for example.
> > Can you please help me to understand better this changes and the business requirement it supports?
> 
> @adamsaghy I've updated the description with the Jira ticket https://issues.apache.org/jira/browse/FINERACT-1960

Hi

recognizedAsAccrualIncome = false by default is still a problem for all the other cases which is not related to Savings account but Loan charge where all charges are considered as income... we shall not retrieve this value as false for them... i reckon

**Pull request closed without merging**
