### PR TITLE
improve logging in SchedulerTriggerListener (re. FINERACT-922)

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by maektwain** [comment]
This failed because of another issue.

**Comment by vorburger** [comment]
Please don't merge this one just yet; I want to do some more local tests to compare this VS #813.

**Comment by vorburger** [comment]
> Please don't merge this one just yet; I want to do some more local tests to compare this VS #813.

Let's actually (get this reviewed to) merge this... together with, not instead of #813 - having both shouldn't do any harm - more eyes on logging is probably a very Good Thing in the case of the scheduler, with all the problems we're having with it.

**Comment by vorburger** [comment]
@awasum @ptuomola review and merge this?

**Comment by ptuomola** [comment]
Looks good to me - all makes sense

**Review by awasum — APPROVED** [review]
LGTM.

**Comment by awasum** [comment]
Unrelated to this issue maybe but Image build to publish on Dcoker Hub keeps failing over the past 24 hours.
image

We cannot check the problem since we dont have access to dockerhub logs maybe? see: 
https://hub.docker.com/login/?next=/redirect/?resource_uri=/api/audit/v1/action/1a8b1cff-5274-4f3a-bef9-fc760c188155/

Does it mean docker images are not been built? 

Do we goto Infra with this?

**Comment by vorburger** [comment]
@awasum re. Docker Hub, please open a JIRA issue (in FINERACT, not INFRA),
and assign it to me.

>

**Pull request merged**
