### PR TITLE
Fineract-722

### PR DESCRIPTION
**Pull request by DylanRobson**
## Description
Fixes issue where global configurations were affecting state between integration tests. This caused LoanReschedulingWithinCenterTest to fail only on the first day of the month because the "skip-repayment-on-first-day-of-month" configuration was modified but never reset by GlobalConfigurationTest.
Also updated other integration tests to reset and verify default global configurations.
## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.
(N/A)

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by cnangeh — COMMENTED** [review]
I just tested this and got the same integration test failing with or without this updates. Are there some particular failing test I should be looking out for?

**Comment by edcable** [comment]
@vorburger @vishwasbabu @awasum Are you able to see if this pull request is cause of integration tests failing?

**Comment by vorburger** [comment]
This failed due to that `The job exceeded the maximum log length, and has been terminated.` problem, see [FINERACT-800](https://issues.apache.org/jira/browse/FINERACT-800), which I fixed in #657. @DylanRobson could you please rebase this?

**Comment by vorburger** [comment]
> This failed due to that `The job exceeded the maximum log length, and has been terminated.` problem, see [FINERACT-800](https://issues.apache.org/jira/browse/FINERACT-800), which I fixed in #657. @DylanRobson could you please rebase this?

@DylanRobson we're not sure whether you're still interested in actively contributing to this project, so I've just gone ahead and done the rebase of this PR in #671, and will merge that one if it passes the build.

**Comment by edcable** [comment]
Thanks @vorburger I'm glad the hard work of @DylanRobson will get shipped!

**Pull request closed without merging**
