### PR TITLE
Fineract-725 Added Jacoco to measure current code coverage

### PR DESCRIPTION
**Pull request by thesmallstar**
## Description
please refer: https://issues.apache.org/jira/browse/FINERACT-725
A report like this is being generated currently:
image

To generate run:  sudo ./gradlew clean build jacocoTestReport
If these changes are correct, I suggest we also add this to read me :) 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by xurror — COMMENTED** [review]
This looks good. I think it would also be good if issues can be created for the lacking tests on jira so that willing contributors can lend a hand to implement them

**Comment by thesmallstar** [comment]
@xurror thank you for the review. 
Also about the issues you mentioned: This was a subtask on one of the GSoC project, the work is properly explained on [FINERACT-713](https://issues.apache.org/jira/browse/FINERACT-713)
We can add more subtasks and work on them :D

**Review by vorburger — CHANGES_REQUESTED** [review]
>  If these changes are correct, I suggest we also add this to read me :)

This is great! Before we merge, could I suggest that, as part of this PR, you add a section about this to the README?  It should explain how to run it, what it covers (is this showing coverage only of unit or also of integration tests?), and where to find the results.

**Comment by thesmallstar** [comment]
@vorburger okay, on it.
Also sir, I have mailed you my gsoc proposal, can you please review it?

**Review by vorburger — APPROVED** [review]

**Comment by awasum** [comment]
> This looks good. I think it would also be good if issues can be created for the lacking tests on jira so that willing contributors can lend a hand to implement them

Do that, please

**Comment by thesmallstar** [comment]
@awasum yes on it.
-thanks

**Pull request merged**
