### PR TITLE
FINERACT-821 Added and Enforced ArrayTypeStyle checkstyle

### PR DESCRIPTION
**Pull request by thesmallstar**
Refer: https://issues.apache.org/jira/browse/FINERACT-821

### CODE REVIEW

**Review by Wandji69 — COMMENTED** [review]
@thesmallstar Great Work.

**Review by vorburger — APPROVED** [review]
LGTM

**Review by xurror — APPROVED** [review]
Great, will merge once you rebase this.

**Comment by thesmallstar** [comment]
@vorburger I will rebase all of them one by one since when one gets merged others have conflicts. 
So We can follow this: You can approve a PR and not worry about merge conflicts, I will comment on any one of the pending PR so that you can merge it, and then I will solve some other conflict and notify you again.
hope that works?

**Comment by vorburger** [comment]
SGTM. You could also play mean little tricks ;-) and put the new lines at
different places in the uncommented section of the XML to avoid merge
conflicts... ;-) PS: if only git was smarter about merging XML!

>

**Comment by thesmallstar** [comment]
@vorburger this is ready to merge

**Review by vorburger — APPROVED** [review]

**Pull request merged**
