### PR TITLE
FINERACT-1021 - Update to JUnit 5

### PR DESCRIPTION
**Pull request by xurror**
[FINERACT-1021](https://issues.apache.org/jira/browse/FINERACT-1021)

### CODE REVIEW

**Comment by xurror** [comment]
@vorburger @awasum good for you?

**Review by vorburger — APPROVED** [review]
LGTM! I've not really reviewed this line by line, but glanced over it, seen it passes tests - so no objections.

PS: I'm also intentionally merging this big change BEFORE #943 which I want to do in a few hours.

**Comment by vorburger** [comment]
Wait a second - this disabled all tests!!!!! :sob: 

Both `./gradlew test` and `./gradlew integrationTest` don't do anything, anymore after I merge this.

We therefore either have to revert this ASAP, or fix it today... sorry & thanks for understanding.

The Revert is non-trivial because I've meanwhile merged other PRs.

@xurror @percyashu @thesmallstar @awasum @ptuomola would one of you like to look into how to make tests run? I'm guessing the Gradle needs some sort of configuration change to run JUnit 5...

This is now blocking #943 ... :disappointed:

**Comment by vorburger** [comment]
==> #1054

**Pull request merged**
