### PR TITLE
FINERACT-1101 [Backport PR] Added Mustache templates to Swagger Codegen

### PR DESCRIPTION
**Pull request by Grandolf49**
## Description
This is a backport PR for `1.4.0`. It addresses FINERACT-1101. Read #1271 for more details.
 
## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by awasum** [comment]
Did you also raise a PR for develop branch? Else if we merge this on branch 1.4.0 only, then develop branch and subsequently the next release will lack this PR. Maybe we should just merge everything on develop? and let @vidakovic decide what to cherry pick. cc @vorburger

**Comment by Grandolf49** [comment]
> Did you also raise a PR for develop branch? Else if we merge this on branch 1.4.0 only, then develop branch and subsequently the next release will lack this PR. Maybe we should just merge everything on develop? and let @vidakovic decide what to cherry pick. cc @vorburger

Yes this is merged in develop already. Check this PR #1271

**Review by vidakovic — APPROVED** [review]
LGTM

**Comment by vidakovic** [comment]
@Grandolf49 please have look at #1292 and comment if that works for you.

**Comment by Grandolf49** [comment]
@vidakovic #1292 LGTM

**Pull request merged**
