### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by iamrupok**

### CODE REVIEW

**Comment by nazeer1100126** [comment]
@iamrupok This PR has conflicts and other changes (66 commits). You should send PR with your changes only.

**Comment by iamrupok** [comment]
@nazeer1100126 Conflict Resolved

**Comment by nazeer1100126** [comment]
@iamrupok Still I can't review this as it is having 67 commits

**Comment by iamrupok** [comment]
changed only 8 file and pushed only how can this be 63 file

**Pull request closed without merging**
