### PR TITLE
FINERACT-982 - Completely ditch use of Drizzle JDBC Driver after all

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

We have replaced the use of the Drizzle Driver to MariaDB. Also changes in the charset and collation has been made. 

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by j2l** [comment]
Hi, 
Very interesting but I'm getting an error when I build it:
```
...
fineractmysql_1    | 2021-07-22  8:30:58 139903434213120 [Note] InnoDB: Buffer pool(s) load completed at 210722  8:30:58
fineractmysql_1    | 2021-07-22  8:30:58 139904319616704 [Note] Reading of all Master_info entries succeeded
fineractmysql_1    | 2021-07-22  8:30:58 139904319616704 [Note] Added new Master_info '' to hash table
fineractmysql_1    | 2021-07-22  8:30:58 139904319616704 [Note] mysqld: ready for connections.
fineractmysql_1    | Version: '10.2.39-MariaDB-1:10.2.39+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
fineract-server_1  | 2021-07-22 08:30:59.384  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http) 8443 (https)
fineract-server_1  | 2021-07-22 08:30:59.811 ERROR 1 --- [           main] com.zaxxer.hikari.HikariConfig           : Failed to load driver class org.mariadb.jdbc.Driver from HikariConfig class classloader org.springframework.boot.loader.LaunchedURLClassLoader@7dc7cbad
fineract-server_1  | 2021-07-22 08:30:59.815 ERROR 1 --- [           main] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'org.apache.fineract.infrastructure.core.boot.WebXmlConfiguration': Unsatisfied dependency expressed through field 'basicAuthenticationProcessingFilter'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'basicAuthenticationProcessingFilter' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/org/apache/fineract/infrastructure/security/filter/TenantAwareBasicAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.authenticationManager': Cannot resolve reference to bean 'customAuthenticationProvider' while setting constructor argument with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customAuthenticationProvider' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/META-INF/spring/securityContext.xml]: Cannot resolve reference to bean 'userDetailsService' while setting bean property 'userDetailsService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsService': Unsatisfied dependency expressed through field 'platformUserRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appUserRepository' defined in org.apache.fineract.useradministration.domain.AppUserRepository defined in : Cannot create inner bean '(inner bean)#5d152bcd' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#5d152bcd': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tenantDatabaseUpgradeService' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/org/apache/fineract/infrastructure/core/service/TenantDatabaseUpgradeService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcTenantDetailsService' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/org/apache/fineract/infrastructure/security/service/JdbcTenantDetailsService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hikariTenantDataSource' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/META-INF/spring/hikariDataSource.xml]: Cannot resolve reference to bean 'hikariConfig' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hikariConfig' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/META-INF/spring/hikariDataSource.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
fineract-server_1  | PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'driverClassName' threw exception; nested exception is java.lang.RuntimeException: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
fineract-server_1  | 2021-07-22 08:30:59.899  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
fineract-server_1  | 2021-07-22 08:30:59.921 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
fineract-server_1  | 
fineract-server_1  | org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
fineract-server_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161)
fineract-server_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
fineract-server_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
fineract-server_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
fineract-server_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
fineract-server_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
fineract-server_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
fineract-server_1  | 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
fineract-server_1  | 	at org.apache.fineract.ServerApplication.main(ServerApplication.java:61)
fineract-server_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
fineract-server_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
fineract-server_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
fineract-server_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
fineract-server_1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
fineract-server_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
fineract-server_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
fineract-server_1  | 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
fineract-server_1  | Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
fineract-server_1  | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:142)
fineract-server_1  | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104)
fineract-server_1  | 	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:440)
fineract-server_1  | 	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:193)
fineract-server_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178)
fineract-server_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158)
fineract-server_1  | 	... 16 common frames omitted
fineract-server_1  | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.apache.fineract.infrastructure.core.boot.WebXmlConfiguration': Unsatisfied dependency expressed through field 'basicAuthenticationProcessingFilter'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'basicAuthenticationProcessingFilter' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/org/apache/fineract/infrastructure/security/filter/TenantAwareBasicAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.authenticationManager': Cannot resolve reference to bean 'customAuthenticationProvider' while setting constructor argument with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customAuthenticationProvider' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/META-INF/spring/securityContext.xml]: Cannot resolve reference to bean 'userDetailsService' while setting bean property 'userDetailsService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsService': Unsatisfied dependency expressed through field 'platformUserRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appUserRepository' defined in org.apache.fineract.useradministration.domain.AppUserRepository defined in : Cannot create inner bean '(inner bean)#5d152bcd' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#5d152bcd': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tenantDatabaseUpgradeService' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/org/apache/fineract/infrastructure/core/service/TenantDatabaseUpgradeService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcTenantDetailsService' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/org/apache/fineract/infrastructure/security/service/JdbcTenantDetailsService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hikariTenantDataSource' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/META-INF/spring/hikariDataSource.xml]: Cannot resolve reference to bean 'hikariConfig' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hikariConfig' defined in URL [jar:file:/app/fineract-provider.jar!/BOOT-INF/classes!/META-INF/spring/hikariDataSource.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
fineract-server_1  | PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'driverClassName' threw exception; nested exception is java.lang.RuntimeException: Failed to load driver class org.mariadb.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
fineract-server_1  | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
fineract-server_1  | 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
fineract-server_1  | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1420)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
fineract-server_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
fineract-server_1  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:408)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
fineract-server_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
fineract-server_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
fineract-server_1  | 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:211)
fineract-server_1  | 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:202)
fineract-server_1  | 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:96)
fineract-server_1  | 	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:85)
fineract-server_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:255)
fineract-server_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:229)
fineract-server_1  | 	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53)
fineract-server_1  | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5166)
fineract-server_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
fineract-server_1  | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
fineract-server_1  | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
fineract-server_1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
fineract-server_1  | 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
fineract-server_1  | 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
fineract-server_1  | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
fineract-server_1  | 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
fineract-server_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
fineract-server_1  | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
fineract-server_1  | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
fineract-server_1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
fineract-server_1  | 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
fineract-server_1  | 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
fineract-server_1  | 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
fineract-server_1  | 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
fineract-server_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
fineract-server_1  | 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
fineract-server_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
fineract-server_1  | 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
fineract-server_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
fineract-server_1  | 	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
fineract-server_1  | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)
fineract-server_1  | 	... 21 common frames omitted
...
```

**Comment by IOhacker** [comment]
Let me do the fixes in some queries about the collation.

**Comment by IOhacker** [comment]
Closing the PR to fix the errors

**Comment by j2l** [comment]
> Let me do the fixes in some queries about the collation.

Thank you! 
I'm on Ubuntu if you need some install feedback :)

**Pull request closed without merging**
