### PR TITLE
Adding UI to K8s deployment (FINERACT-1419)

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

Adding UI to K8s deployment (FINERACT-1419)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [X] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [X] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by ptuomola — APPROVED** [review]
LGTM

**Comment by ptuomola** [comment]
Concept looks OK, but I think there's a problem in the docker-compose.yml:

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.community-app.depends_on contains an invalid type, it should be an array
services.fineract-server.depends_on contains an invalid type, it should be an array

**Comment by IOhacker** [comment]
Hello,

It is because the version of Docker Compose in Travis-Ci, I will send a fix
in the travis yml

**Comment by ohadzer** [comment]
Anything new with this PR? I'm really waiting for it

**Comment by IOhacker** [comment]
Hello,

I have been with some work load, it will be fixed tonight.

**Comment by ohadzer** [comment]
Anything new? I'm still waiting for it
I tried to test the branch and it didn't work
Thanks

**Comment by ptuomola** [comment]
@ohadzer I've rebased this as a separate PR and merged it - so the latest develop branch should now have this included...

**Pull request closed without merging**
