### PR TITLE
Bulk import feature (FINERACT-1396)

### PR DESCRIPTION
**Pull request by Cadreia**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by awasum** [comment]
Thanks for contributing to Apache Fineract @Cadreia . What issue is this PR fixing?

**Comment by ptuomola** [comment]
Hi - is this ready for review, or still work in progress?

**Comment by Cadreia** [comment]
It's still WIP. Will submit for review once I'm done.

**Comment by awasum** [comment]
@bharathc27 , @francisguchie , will you like to functionally test this and let us know if its ready to be merged?

@BLasan  will you like to also review this? Also watch how @ptuomola  does code reviews so you can learn.

**Comment by BLasan** [comment]
> @bharathc27 , @francisguchie , will you like to functionally test this and let us know if its ready to be merged?
> 
> @BLasan will you like to also review this? Also watch how @ptuomola does code reviews so you can learn.

Will start reviewing today

**Review by ptuomola — APPROVED** [review]
LGTM

**Comment by ptuomola** [comment]
Apologies @BLasan - did not notice you were going to review this as well.

**Comment by ptuomola** [comment]
Looked OK to me - the only thing I was going to comment on was the commented out code - this should have been cleaned up.

**Pull request merged**
