### PR TITLE
FINERACT-1938: Fix calculating running balance after release amount in batch request

### PR DESCRIPTION
**Pull request by mariiaKraievska**
## Description

Fix calculating running balances in futher transactions after release amount transaction in batch request.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

JIRA ticket - https://issues.apache.org/jira/browse/FINERACT-1938

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@marta-jankovics FYI

**Comment by mariiaKraievska** [comment]
PTAL, there were 3 workflows failed due to formatting violations. I hope it should be fine now.

**Comment by adamsaghy** [comment]
@mariiaKraievska Please squash your commits together!

**Comment by mariiaKraievska** [comment]
@adamsaghy Done, PTAL

**Review by adamsaghy — APPROVED** [review]
LGTM

**Comment by adamsaghy** [comment]
@mariiaKraievska please check the conflicts and squash your commits

**Comment by marta-jankovics** [comment]
Can be merged, looks good.

**Comment by adamsaghy** [comment]
Please squash your commits and it is ready to be merged

**Comment by adamsaghy** [comment]
@mariiaKraievska please squash your commits and resolve the conflicts. Instead of merging of the latest develop branch, please trx using rebasing strategy ;)

**Comment by mariiaKraievska** [comment]
Done, PTAL

**Comment by mariiaKraievska** [comment]
All checks have passed, no conflicts. Can it be merged, please?

**Comment by adamsaghy** [comment]
> All checks have passed, no conflicts. Can it be merged, please?

Yes, thank you for your contribution! ;)

**Comment by mariiaKraievska** [comment]
> > All checks have passed, no conflicts. Can it be merged, please?
> 
> Yes, thank you for your contribution! ;)

Thank you too!

**Pull request merged**
