### PR TITLE
FINERACT-1721: Loan Delinquency Tags with Loan charges

### PR DESCRIPTION
**Pull request by josehernandezfintecheandomx**
## Description

When a loan account receives credits on the overdue outstanding payments, his/her Delinquency Classification may change with that. Delinquency classification of the loan should be checked and correct in Real-time when new transactions are made on the loan account

[FINERACT-1721](https://issues.apache.org/jira/browse/FINERACT-1721)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by galovics — CHANGES_REQUESTED** [review]
Testcase please.

**Comment by adamsaghy** [comment]
@josehernandezfintecheandomx Please check the failing tests!

**Review by galovics — APPROVED** [review]

**Comment by adamsaghy** [comment]
Please add a test case which check the delinquency got corrected at "add charge" and "waive charge"

**Review by galovics — CHANGES_REQUESTED** [review]
Testcase pls.

**Comment by josehernandezfintecheandomx** [comment]
> Testcase please.

Integration test case added

**Comment by josehernandezfintecheandomx** [comment]
> Please add a test case which check the delinquency got corrected at "add charge" and "waive charge"

Integration Test added  including a charge

**Review by galovics — APPROVED** [review]

**Pull request merged**
