### PR TITLE
FINERACT-821 Added and Enforced Typename checkstyle

### PR DESCRIPTION
**Pull request by thesmallstar**
Refer: https://issues.apache.org/jira/browse/FINERACT-821
Needs a rebase, please do not merge this I will review this once again before any of the mentors can take a look :)

### CODE REVIEW

**Comment by vorburger** [comment]
> before any of the mentors can take a look :)

@thesmallstar you can use Mark as Draft (on the right) to "signal" that a PR is Work-In-Progress (WIP)

**Comment by thesmallstar** [comment]
@vorburger  ready for your review.

**Review by xurror — APPROVED** [review]
That's alot of files to changes. Great work on this one. LGTM

**Review by vorburger — APPROVED** [review]
LGTM

**Comment by vorburger** [comment]
@thesmallstar resolve merge conflicts please

**Pull request merged**
