### PR TITLE
FINERACT-1568 Fix Datatable creation fails on PostgreSQL

### PR DESCRIPTION
**Pull request by josehernandezfintecheandomx**
## Description

In attention for the Ticket FINERACT- related to issues in the datatable creation using PostgreSQL

Ignore if these details are present on the associated [Apache Fineract JIRA ticket FINERACT-1568](https://issues.apache.org/jira/browse/FINERACT-1568).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by vidakovic** [comment]
For some reason I can't make this workflow run... can someone else please try?

**Comment by ptuomola** [comment]
I can't make it run either... But it's not clear to me what it is trying to run anyway. All the 5 workflows are already marked as success so not sure what's pending.

**Comment by galovics** [comment]
Strange, I can't run it either but the workflows are successful. Maybe it's just a stuck bit in GH Actions which will be immediately resolved if we push a new commit. Not sure.

**Review by galovics — CHANGES_REQUESTED** [review]
Thanks for the changes @josehernandezfintecheandomx. I'd love to see new test cases added for this functionality since it's broken on develop right now, indicating that this exact use-case was a gap in the existing test suite.
Other than that, looks good.

**Comment by josehernandezfintecheandomx** [comment]
Included in other PR

**Pull request closed without merging**
