### PR TITLE
Fixed kubernetes startup & shutdown commands issue (FINERACT-1288)

### PR DESCRIPTION
**Pull request by BLasan**
## Description

Commands mentioned in README.md file for starting-up & shutting-down the K8s cluster is not accurate according to the naming conventions of the bash files.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by BLasan** [comment]
@vorburger please review

**Review by xurror — CHANGES_REQUESTED** [review]
Instead of renaming the files by removing the extension, it's better you instead update the readme to reflect the file and extension.
Those are shell scripts and it would be good to keep the extension so anyone can know what it is by looking at it.
Removing the extension may just end up being more confusing.

**Comment by BLasan** [comment]
> Instead of renaming the files by removing the extension, it's better you instead update the readme to reflect the file and extension.
> Those are shell scripts and it would be good to keep the extension so anyone can know what it is by looking at it.
> Removing the extension may just end up being more confusing.

ok, I'll change the readme as required :)

**Comment by BLasan** [comment]
@xurror Done! Please review

**Review by xurror — APPROVED** [review]
Nice. LGTM.
I'll merge once it passed the build.

**Pull request merged**
