### PR TITLE
Publish Fineract Provider binary

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

Publish Fineract Provider binary

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [X] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [X] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by IOhacker** [comment]
@galovics @vidakovic @francisguchie Please review this PR, there is a dependency management change that was causing the invalid POM message.

**Comment by francisguchie** [comment]
> @galovics @vidakovic @francisguchie Please review this PR, there is a dependency management change that was causing the invalid POM message.

@IOhacker  thank you for this I will wait on @galovics. Is it possible to select his name under the reviewers **(top right of the issue )**

**Comment by IOhacker** [comment]
@francisguchie thank you, I have added @galovics as a reviewer in the PR, FYI this is the output of the publishing task in OpenMf https://github.com/openMF/fineract/actions/runs/4474466141

**Comment by IOhacker** [comment]
@edcable @galovics @vidakovic I had to create a new PR, the other PR was closed because I lost my previous work when I have deleted my workspace, this PR has the previous comments attended.

**Review by galovics — APPROVED** [review]

**Pull request merged**
