### PR TITLE
Fineract 1012:Spring Security OAuth 2.x to Spring Security 5.2.x

### PR DESCRIPTION
**Pull request by Wandji69**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by awasum** [comment]
Hi @Wandji69 . Thanks for the PR. It looks like you modified the embedded Gradle Wrapper ( gradlew ) in a way that made this PR to fail on Travis as seen here: https://travis-ci.org/github/apache/fineract/builds/701349450 throwing a class not found exception. 
Is this a new error?

Also try to squash your PRs in to 1 commit when possible so we have a clean commit history.

**Comment by durrantk** [comment]
I’m looking into this but have not push. I will also squash.

**Comment by awasum** [comment]
Are @durrantk  and @Wandji69  paring on this PR? if so make sure to use the Co-Author feature for Git and Github. See: https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

**Comment by awasum** [comment]
But it will be easier for one person to get this work done..instead of 2. Is this really that complicated or you all are just learning?

**Pull request closed without merging**
