### PR TITLE
FINERACT-1108 Custom-installment-in-reshedule

### PR DESCRIPTION
**Pull request by fynmanoj**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

https://issues.apache.org/jira/browse/FINERACT-1108

Originally located at https://mifosforge.jira.com/browse/AL-9
## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vorburger** [comment]
@avikganguly01 knowing that @fynmanoj works with you, and assuming that you are still an active committer to this project (are you?), I was wondering if you would like to engage on code review feedback and possible eventual merge of PRs such as this one? (I don't want to be a bottleneck on this project, and won't have the spare time to help review changes like this. If there are other active committers such as @awasum @ptuomola @xurror or others reading this who want to engage on this PR, please don't let me hold you up / wait for me - I'll ignore this one, and try to help on others.)

**Comment by vorburger** [comment]
@fynmanoj this PR needs to have a JIRA issue on the ASF JIRA, instead of referencing an issue from an issue tracker that is now a downstream redistribution of Fineract.

**Review by avikganguly01 — CHANGES_REQUESTED** [review]
https://travis-ci.org/github/apache/fineract/builds/713293884 - Can you look at why the deadlock for financial activity type is being caused?

**Comment by avikganguly01** [comment]
Corresponding backoffice community app UI changes are at [link](https://github.com/openMF/community-app/pull/3259).

**Review by avikganguly01 — APPROVED** [review]

**Comment by avikganguly01** [comment]
Deadlock for financial activity type is being caused by a different flaky test and it seems to happen rarely, even in the absence of this PR.

**Pull request merged**
