### PR TITLE
Fix granting privileges to MySQL root-user (FINERACT-1284)

### PR DESCRIPTION
**Pull request by BLasan**
## Description
FINERACT-1284 Fixed privileges granting query.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by BLasan** [comment]
@awasum Travis build fails
Screenshot from 2021-01-05 21-10-09

**Comment by BLasan** [comment]
@vorburger please review.

**Comment by vorburger** [comment]
@BLasan thanks for making a first time contribution to Fineract! FYI the build here failed due to FINERACT-887, please watch that issue, and then rebase this PR once that's solved.

**Comment by BLasan** [comment]
> @BLasan thanks for making a first time contribution to Fineract! FYI the build here failed due to [FINERACT-887](https://issues.apache.org/jira/browse/FINERACT-887), please watch that issue, and then rebase this PR once that's solved.

will solve it sir :) @vorburger

**Comment by vorburger** [comment]
@BLasan if you still want this, you can rebase it and the build should now pass. Do read my comment in FINERACT-1284 as well though.

**Comment by BLasan** [comment]
> @BLasan if you still want this, you can rebase it and the build should now pass. Do read my comment in [FINERACT-1284](https://issues.apache.org/jira/browse/FINERACT-1284) as well though.

I think we could close this PR :)  See my comment [FINERACT-1284](https://issues.apache.org/jira/browse/FINERACT-1284)

**Comment by vorburger** [comment]
@BLasan the "culture" (here and in open source in general) is that YOU and not "we" (me) would close anything that you opened... :-) if you "retract" a proposed change. Will you close this PR?

**Comment by BLasan** [comment]
> @BLasan the "culture" (here and in open source in general) is that YOU and not "we" (me) would close anything that you opened... :-) if you "retract" a proposed change. Will you close this PR?

Ok sir, I'll close this :)

**Pull request closed without merging**
