### PR TITLE
Introduce ImageResizer to simplify ImageData (FINERACT-1201)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-1201

### CODE REVIEW

**Comment by vorburger** [comment]
Draft until I double check if the changes here are covered by an integration test.

**Comment by vorburger** [comment]
Draft until I double check if the changes here are covered by an integration test using #1464 (will rebase when that one is merged).

**Comment by vorburger** [comment]
@ptuomola would you be willing to review this PR re. FINERACT-1201, and merge it if it LGTY?

FYI I've locally ensured that the (new) `ImageTest` and `DocumentTest` still pass with these changes.

**Comment by vorburger** [comment]
@ptuomola just FYI this PR intentionally contains 4 separate commits which are easier to review individually.

**Review by ptuomola — APPROVED** [review]
LGTM

**Pull request merged**
