### PR TITLE
upgrade Gradle (wrapper) from 6.1 to 6.4 (FINERACT-945)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-945

### CODE REVIEW

**Comment by vorburger** [comment]
Draft - this (first) requires FINERACT-947 ...

**Comment by vorburger** [comment]
FYI #838 (FINERACT-946) will _prove_ that the binary `gradle-wrapper.jar` which I'm contributing here is not malicious!

**Comment by vorburger** [comment]
This failed due to FINERACT-855, which #848 ignores - unrelated to Gradle upgrade.

**Comment by vorburger** [comment]
@awasum @xurror @ptuomola this fully passed the build now, and I've assumed no objections to self merging this.

**Comment by xurror** [comment]
Fine with me

**Pull request merged**
