### PR TITLE
Remove jul-to-slf4j exclusion (FINERACT-1199)

### PR DESCRIPTION
**Pull request by vorburger**
see FINERACT-1199

### CODE REVIEW

**Comment by vorburger** [comment]
@ptuomola you'll like this? :smiley:

**Comment by ptuomola** [comment]
Looks promising! :-) Let me try if it works as expected...

**Comment by vorburger** [comment]
> Looks promising! :-) Let me try if it works as expected...

does for me! But "[doppelt genäht hält besser](https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=doppelt%20gen%C3%A4ht%20h%C3%A4lt%20besser)" - please do verify! :smiling_imp:

**Comment by ptuomola** [comment]
Tried this locally - and confirmed that this fixes the logging output from embedded Tomcat and JAX RS etc. Great news!

**Review by ptuomola — APPROVED** [review]
LGTM

**Pull request merged**
