### PR TITLE
Upgrading Spring Framework BOM to 5.2.9

### PR DESCRIPTION
**Pull request by ptuomola**
Not sure why this was not done automatically by Renovate...? 

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by vorburger** [comment]
@ptuomola interesting that Renovate didn't "see" this... @rarkins could this interest you? :smiling_imp: 

@vidakovic keep this in mind re. more BOM usage discussed in FINERACT-1171

**Comment by vorburger** [comment]
(Let us not merging this just yet and keeping it open a week or so to give @rarkins a chance to check out if he can perhaps automate it.)

**Comment by vidakovic** [comment]
@vorburger will do, syncing the branch with git fetch upstream every couple of days

**Comment by zharinov** [comment]
I haven't found this dependency in Gradle extraction report, so not sure it can be fixed easily at manager level.
But here is [quick config-level fix](https://github.com/zharinov/fineract/blob/develop/renovate.json#L14) that can help:
```
  "regexManagers": [
    {
      "fileMatch": ["\\.gradle(\\.kts)?$"],
      "matchStrings": ["[\\s\\n{](mavenBom)\\s*['\"](?<depName>[a-zA-Z][-_a-zA-Z0-9.]*?:[a-zA-Z][-_a-zA-Z0-9.]*?):(?<currentValue>[a-zA-Z0-9][-.a-zA-Z0-9]*?)['\"]"],
      "datasourceTemplate": "maven",
      "versioningTemplate": "gradle"
    }
  ]
```
Note `mavenBom` regex group: it can be extended for another words having similar problems. 
Also here is [example PR](https://github.com/zharinov/fineract/pull/1).

**Review by vorburger — CHANGES_REQUESTED** [review]
@zharinov neat!! Looks magic, but if this does the trick (as your PR seems to prove it will), we'll do this! See #1385 for FINERACT-1192. Next Steps: 
1. Merge #1385
1. Wait for a PR similar to https://github.com/zharinov/fineract/pull/1 on this repo
1. Close this (manual) PR

**Comment by zharinov** [comment]
I'll research more on the problem at gradle manager level, maybe we can do this magic automatically soon.

UPD. So if I can fix the main cause, #1385 can be reverted back after some future Renovate release.

**Comment by ptuomola** [comment]
Closing this as the Renovate bot now knows how to raise updates to Maven BOM

**Pull request closed without merging**
