### PR TITLE
FINERACT-1054 fix error at repayment

### PR DESCRIPTION
**Pull request by francisguchie**
## Description
https://issues.apache.org/jira/browse/FINERACT-1054

## Checklist
see https://github.com/apache/fineract/pull/1148

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by francisguchie** [comment]
@awasum 
I will need your guidance on how to get the build to pass the travis test

**Comment by francisguchie** [comment]
i only  added these lines below 


sqlBuilder.append("   GROUP BY ls.duedate");
--
sqlBuilder.append(",ls.principal_amount,ls.principal_completed_derived,ls.principal_writtenoff_derived");
sqlBuilder.append(",ls.interest_amount,ls.interest_completed_derived,ls.interest_waived_derived,ls.interest_writtenoff_derived");
sqlBuilder.append(",ls.fee_charges_amount,ls.fee_charges_completed_derived,   ls.fee_charges_writtenoff_derived, ls.fee_charges_waived_derived");
sqlBuilder.append(",ls.penalty_charges_amount,   ls.penalty_charges_completed_derived, ls.penalty_charges_writtenoff_derived,   ls.penalty_charges_waived_derived");

**Comment by awasum** [comment]
Please, I will look at this tomorrow m don't worry, we will figure this out and get this reviewed and possibly merged.

**Comment by xurror** [comment]
Hey, you need to run: `./gradlew spotlessApply` locally before pushing to prevent this build error from popping up

**Comment by awasum** [comment]
Ok.. Goto the branch for the PR and do: `git pull --rebase upstream develop` then do `./gradew spotlessApply` and commit your changes and push them. (there are 2 gradle wrappers, one for window and the other for linux, use the right one)

**Comment by francisguchie** [comment]
@xurror  i did this locally in two different ways

1- I did this at the PR Branch - ./gradew spotlessApply  i did this after making the Develop branch uptodate by git pull --rebase upstream develop (while at the develop branch) - after my changes i applied the spotless and tested with a build all with a success and then i raised the PR

2- I  was on the develop branch and i ran git pull --rebase upstream develop then i ran ./gradew spotlessApply and checked the spotless and also ran a build it was all fine then i created a branch from this spotlessApplied develop made changes and went ahead to ./gradew spotlessApply  in this new edited branch went ahead to check and also run a build it was all fine 

@awasum  
how do i know which gradle wrapper is for windows or linux  when i am using gitbash on my desktop ? Please help

**Comment by francisguchie** [comment]
@awasum 

i am going to try this below

**Ok.. Goto the branch for the PR and do: git pull --rebase upstream develop then do ./gradew spotlessApply and commit your changes and push them. (there are 2 gradle wrappers, one for window and the other for linux, use the right one)**

let me try to find which wrapper is for windows before i venture

**Comment by awasum** [comment]
I pulled your changes and applied the spotless....See : https://github.com/awasum/fineract/tree/francisguchie-fixSqlErrorAtLoanRepayment

**Comment by awasum** [comment]
Can you pull that down to your branch and this PR will be updated automatically?

**Comment by francisguchie** [comment]
i just did but this PR is for another branch   called  fixErrorFineract1054
i closed the PR raised for this branch i just pulled from your repo

**Comment by francisguchie** [comment]
> I pulled your changes and applied the spotless....See : https://github.com/awasum/fineract/tree/francisguchie-fixSqlErrorAtLoanRepayment

i followed the steps but to no avail please see https://github.com/apache/fineract/pull/1148

**Comment by francisguchie** [comment]
Closing this PR as it is addressed here https://github.com/apache/fineract/pull/1154

**Pull request closed without merging**
