### PR TITLE
FINERACT-1780: Introduce Lombok to workingdays module

### PR DESCRIPTION
**Pull request by balancehero-neal**
## Description

[FINERACT-1780](https://issues.apache.org/jira/browse/FINERACT-1780)

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by balancehero-neal** [comment]
Hello, @hmg65 .
Firstly, sorry that I'm not sure about this workflow 🙇‍♂️  
Please close this request, If I'm following the wrong workflow of the project. 
I will learn contributor-guide again 😅 

p.s.
I'm a totally new joiner to this project. 
I'm an engineer developing the business with this project in some fintech company.
So, I hope to contribute to this project as an individual contributor.

**Review by mohitsinha — APPROVED** [review]
LGTM.
I am not sure if should instead use `@Data` wherever we have used both `@Setter, @Getter` on the class.

**Comment by mohitsinha** [comment]
@balancehero-neal No worries. 
Your build is failing because there are certain formatting and coding conventions that we follow. 
You can have a look at the failed [reports](https://github.com/apache/fineract/actions/runs/4653887904/jobs/8238223849?pr=3111) 

To fix it, try `./gradlew spotlessApply`

**Comment by balancehero-neal** [comment]
Thank you @mohitsinha 
I applied spotless 🙇‍♂️ 
> Should I make single squashed commit, or we  can do it with merge option?

**Comment by mohitsinha** [comment]
@balancehero-neal Try to squash both these into 1 commit.

**Comment by balancehero-neal** [comment]
@mohitsinha 
Sure, done 🙆‍♂️

**Comment by balancehero-neal** [comment]
> I am not sure if should instead use @Data wherever we have used both @Setter, @Getter on the class.

I wanted to add Lombok with only What we need first. 🙇‍♂️  Instead of carrying `@ToString` / `@EqualsAndHashCode` by `@Data`

**Review by mohitsinha — APPROVED** [review]

**Pull request merged**
