### PR TITLE
FINERACT-805  Spring BOM version numbers 

### PR DESCRIPTION
**Pull request by percyashu**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket https://issues.apache.org/jira/browse/FINERACT-805

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by awasum** [comment]
@percyashu , Some (Advice) Please, Next time, when you make a change, try to build the software with ./gradlew clean tomcatRunWar and ./gradlew clean integrationTest, when these pass, then you can be sure everything will likely pass Travis.

**Comment by vorburger** [comment]
Build Failures are due to compilation failures re. `com.jayway.restassured`.

Try undoing the `com.jayway.restassured:rest-assured:2.3.3` dependency to `io.rest-assured:rest-assured:+` change from this PR. I suspect that will help. You could then investigate that one more separately.

In general, like @awasum said, try first building locally. I also encourage you to propose smaller more incremental changes - just go step by step, one dependency at a time, and gradually raise separate PRs. It's often easier.

**Comment by awasum** [comment]
@percyashu , see this: https://issues.apache.org/jira/browse/FINERACT-809
https://issues.apache.org/jira/browse/FINERACT-810
I created these 2 issues for Flyway and Rest assured which you already tried to upgrade. After this PR is merged, you can go ahead and do those two issues. After that create issues to track dependencies that you want to upgrade. Start small as @vorburger says. I hope this helps.

Welcome to the community and keep sending in PRs.

@xurror Pick other dependencies, create issues for them and upgrade(send PRs) if you are interested.

**Comment by percyashu** [comment]
@vorburger could you review this. I replaced the following dependency version with their respective Spring BOM version.
GSON 
Joda Time 
junit:junit (dropped junit-dep)
commons-lang3 
org.apache.httpcomponents:httpclient
org.apache.activemq:activemq-broker
javax.validation:validation-api
Quartz Scheduler
ehcache

@awasum I will raise separate PRs  for Flyway and Rest assured after this PR is merged. 
And thanks will keep sending in PRs

**Review by vorburger — APPROVED** [review]

**Pull request merged**
