### PR TITLE
FINERACT-1457: Change Kubernetes set-up to use MariaDB

### PR DESCRIPTION
**Pull request by ptuomola**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by ptuomola** [comment]
@vorburger at least for me this fixes the Kubernetes set-up. Had to make some other minor changes as well to get this to run on Rancher/k3s on OSX as for some reason it did not like some of the config / scripts..

**Comment by awasum** [comment]
I am wondering if we should support and test on MySQL 8.x vs MariaDD as our user base are more familiar with MySQL than mariadb. Mariadb might be a drop in replacement but I wonder if we are making a conscious decision that we want to be testing and developing on mariadb exclusively? Do you see some issue going forward. I was looking at this: https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/ and having a few doubts based on the face that the Fineract Community has always use MySQL.

**Comment by vorburger** [comment]
I'm personally actually generally in favor of "pushing" for MariaDB. I also
believe that it is (probably) much more about "recent versions" - of either
one. We didn't break MySQL - I bet it also still works just fine - just not
on an ancient 5.6 version. But it's just easier for the project to stick to
recommending just one, and I'm personally in favor of that being MariaDB
instead of MySQL.

**Comment by francisguchie** [comment]
@vorburger  I have not used MariaDB that much but the last time i did (2017-2018), fineract "misbehaved" and being new to production usage of Apache-Fineract, i chose to stick with what every one was using. But then i learnt of the acquisition of MySQL https://en.wikipedia.org/wiki/MariaDB. 

And am thinking this might lead us into a situation like the one that forced us into a situation of  ["Fineract-Pentaho"](https://issues.apache.org/jira/browse/FINERACT-1127) due to licensing issues 

**That said, I will vote for "pushing" for MariaDB. I like the comfort of knowing am using one of the "best tools available in town" and not worrying about having to change that "tool" in future**

**Comment by ptuomola** [comment]
FWIW - a lot of large companies have switched / are switching from MySQL to MariaDB due to the licensing concerns. I know many banks running thousands of MariaDB instances in production. So I think it's very much "ready for prime time". 

In terms of the compatibility issues, I haven't come across anything major assuming we don't use the latest and greatest features (which exist in MariaDB but not in MySQL). But I don't think we use (or plan to use) any such features in Fineract.

**Comment by awasum** [comment]
Thank you all for your comments. I agree, lets use MariaDB and make it the default going forward. We will deal with whatever issues if any arise. Thanks @ptuomola for doing this.

**Pull request merged**
