### PR TITLE
FINERACT-699 - new configuration parameters 'fromEmail' and 'fromName'

### PR DESCRIPTION
**Pull request by aasaru**

### CODE REVIEW

**Comment by vorburger** [comment]
@aasaru following https://issues.apache.org/jira/browse/FINERACT-697 would you be able to rebase this so that a build run on it?

**Review by vorburger — CHANGES_REQUESTED** [review]
This PR, as-is, would actually breaks the build, see #522, therefore, please do not merge...

**Comment by aasaru** [comment]
I had forgotten to commit changes to this file, sorry about that mistake. I added missing code and after that realized that @vorburger had already done the job and added missing code in pull request #522. So #522 can be dropped.

**Comment by aasaru** [comment]
@vorburger could the "changes requested" flag be now removed?

**Pull request merged**
