### PR TITLE
Fix: Loan Collateral for multi disbursement

### PR DESCRIPTION
**Pull request by BLasan**
## Description

See [FINERACT-1424](https://issues.apache.org/jira/browse/FINERACT-1424?filter=-1)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by BLasan** [comment]
@ptuomola @awasum  Non related tests are failing. Before repushing (without any new changes) it was a test related to `ShareAccount`
```
  Test testDateFormat() FAILED (3.9s)
  java.lang.AssertionError: 1 expectation failed.
  Expected status code <202> but was <500>.
      at org.apache.fineract.integrationtests.SchedulerJobsTest.testDateFormat(SchedulerJobsTest.java:74)
```

**Comment by ptuomola** [comment]
@BLasan Let's try again - many of the other builds have passed today without this error, so it would be very strange if only this one keeps failing...

**Review by ptuomola — APPROVED** [review]
LGTM

**Comment by BLasan** [comment]
@ptuomola Thanks for the review. Build succeeded :)

**Pull request merged**
