### PR TITLE
FINERACT-1594: Create setenv.sh file for Tomcat installations

### PR DESCRIPTION
**Pull request by vidakovic**
## Description

Script to give Tomcat users the same convenience as Docker Compose users.

### CODE REVIEW

**Comment by vidakovic** [comment]
Note: I am adding more documentation on how to use this with FINERACT-1470

**Comment by galovics** [comment]
@vidakovic it's missing the license header. It looks good but I'm not really sure I like the idea of providing an example setenv.shand here's why. 
I feel like people use what's available and I honestly think people will try to use the setenv.sh file as it is. And the thing is, it contains hardcoded values for the docker-compose MySQL setup (hostname, password, etc).
What I'd really like instead of it is having a documentation section for Tomcat deployments where we provide all the environment variables described with example values, so instead of people copy pasting stuff, they have to read through it and configure it for their environment.
Maybe I'm overthinking this, not sure.

**Comment by vidakovic** [comment]
To stay with your argument: you could say the same of the docker compose file in the root folder. That said: I am not too religious about where to put it. But even as documentation people will copy and paste and you'll end up in the same place. And: if they have nothing in place they end up with the default the default values anyway... which are exactly the same as in this setenv.sh.
Something though needs to be done, because there are more WAR users out there that don't know how to translate the Docker env vars for their deployments.
I would leave it in place, add it to documentation and emphasize that this is an example config.

**Comment by galovics** [comment]
@vidakovic alright.

**Review by galovics — APPROVED** [review]

**Review by galovics — APPROVED** [review]

**Pull request merged**
