### PR TITLE
FINERACT-1101 [Backport PR] Swagger Codegen build using Gradle

### PR DESCRIPTION
**Pull request by Grandolf49**
## Description
This is a backport PR for `1.4.0`. This solves FINERACT-1101 issue. Refer #1271 for more details.

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by vorburger — CHANGES_REQUESTED** [review]
@Grandolf49 it seems curious that the (currently) 9 commits on this PR include the 3 commits from #1272 (which are already in 1.4.0), that doesn't quite right... do you want to fix that? You perhaps didn't fetch / pull the latest current 1.4.0 locally? 

Also, why include (cherry-pick) Dependabot Mockito and Spotless upgrades? It's unrelated. I wouldn't.

Do you want to fix both, and force push again?

But I'll let @vidakovic review and merge this, and now step back from this PR.

**Comment by vidakovic** [comment]
@vorburger agree... would exclude the Dependabot related commits... they have verification issues and seem to be unrelated to this specific PR

**Comment by Grandolf49** [comment]
@vorburger @vidakovic  I have raised a new PR #1285 for this. I mistakenly messed up the commits in my branch. I'll close this PR. Sorry for the inconvenience .

**Comment by vorburger** [comment]
> @vorburger @vidakovic I have raised a new PR #1285 for this. I mistakenly messed up the commits in my branch. I'll close this PR. Sorry for the inconvenience .

FYI for the future you can actually just work on a branch with the same name and force push, to re-use the same PR; it's both simpler for you, and easier for maintainers to have everything together in a single PR.

**Comment by Grandolf49** [comment]
Sure @vorburger I'll keep that in mind next time.

**Comment by awasum** [comment]
@vidakovic  and @vorburger .. Will it be a bad idea for us to just merged everything on develop now and tomorrow and then rebase 1.4.0 branch on develop and freeze the release code? and everything then in develop after that goes into the next release. I feel we may get confused here and miss something. I may be wrong here.

**Comment by vidakovic** [comment]
@awasum  Cherry picking is obviously just meant to be used for a short time... so I'd say we give it until the end of this week and then we should draw a line and do the release. The way that @vorburger does the backports makes sure that these things are trackable and only merged PRs (aka stuff that landed in develop) is considered.

Rebasing with current develop could be  - I think - a bit problematic. We are piling more and more features into this release; maybe some of the PRs that landed in develop after the release branch was created will still need some work and/or are not tested entirely. Adding those with a rebase would just further delay things.

Next time we can avoid this by having more feedback when the release is announced (my guess is that mid-August is maybe not the best time to do this, because a lot of people might be on vacation); this time the mailing list was really quiet despite multiple reminders.

**Comment by awasum** [comment]
@alexivanov You are right and I understand you. Keep up the good work. We will get better at doing this in the future. I am also learning.

**Pull request closed without merging**
