### PR TITLE
FINERACT-1780: Introduce Lombok to workingdays module

### PR DESCRIPTION
**Pull request by uditdamare**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by uditdamare** [comment]
I dont have access to fineract jira
About that [Liquibase error for mysql for file "0043_add_external_event_table.xml"](https://github.com/apache/fineract/pull/3029/commits/b175e5a847dacb53f2163394dd6271f8f2745f8a)
Me and @josehernandezfintecheandomx connected on call on slack and for mysql, error was thrown for this xml, thus the changes for the solution.
I have gradle bootrun the project and no errors were thrown

**Comment by adamsaghy** [comment]
Unfortunately we cannot modify already pushed changes. Anyone who has already executed the liquibase will get validation error if we are changing something like this :/

Usually the proper way is creating a brand new changeset which modify the existing (if possible, by not losing or modifying the data) or creating new columns and do the changes to use the old if set and use the new if set (backward compability).

Kindly asking you to create a bug ticket for this in Fineract jira (@bharathgowda27 can help you with that, please reach him out) and try to share some details why it was failing for you. Under that ticket we can investigate this issue and discuss the details of the fix. your PR is a good starting point however these fixes should be assigned to a Fineract ticket and also if we are touching this fields we might wanna even go further and enhance them to support Timestamp with timezone for postgres and datetime for mysql and offsetdatetime at JPA side so we can assure a valid UTC got stored in it as it was doing with many other entities (like: Loan)

**Comment by vidakovic** [comment]
@Subzer0570 can we close this PR then... seems this needs a little bit more thought given the current approach implemented here is not working.

**Comment by vidakovic** [comment]
Also: could you please name the PR according the general pattern we agreed on? Just having the Jira ticket number leaves you here a bit in the dark if not opening the Jira ticket itself. Please use following format (correct one for this PR): "Fineract-1780: Introduce Lombok to workingdays module"... first I thought this is about Liquibase (because of above discussion you had)... but in fact it's a simple Lombok related change... so maybe we can safe this one.
Also: please squash your commits into one.
Thanks again.

**Pull request closed without merging**
