### PR TITLE
escape all `grouping` in SQL files for MySQL 8 compatibility

### PR DESCRIPTION
**Pull request by vorburger**
Indirectly related to https://issues.apache.org/jira/browse/FINERACT-762 - not sure if strictly required, but seems like a good idea anyway at this opportunity, so why not.

As originally on https://github.com/apache/fineract/pull/638/files

### CODE REVIEW

**Comment by vorburger** [comment]
This failed due to what #762 will fix (work around, deactivating test); let's rebase this once that is in.

**Comment by awasum** [comment]
#764 has been merged. lets run this or rebase with develop and see.

**Comment by vorburger** [comment]
This failed to build again, due to flaky test which #761 will comment out...

**Comment by vorburger** [comment]
@awasum review and merge this one? Thanks!

**Review by awasum — APPROVED** [review]
This looks good. Just one question, will this work as it is with MySQL 8.0 and above or we still need some other code changes? I will merged this for now since it passes CI and this: 
https://dev.mysql.com/doc/refman/8.0/en/keywords.html 
'Grouping' added as a keyword: https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-G

Thanks @vorburger

**Comment by vorburger** [comment]
> will this work as it is with MySQL 8.0 and above or we still need some other code changes?

I've actually no idea, I just found it on https://github.com/apache/fineract/pull/638/files and it seemed like a good idea!

**Comment by awasum** [comment]
> > will this work as it is with MySQL 8.0 and above or we still need some other code changes?
> 
> I've actually no idea, I just found it on https://github.com/apache/fineract/pull/638/files and it seemed like a good idea!

Want to switch MySQL version on Travis to 8.0 and see?...Just curious...MySQL 5.5 to 5.7 support is great. Maybe an experiment for another day.

**Comment by awasum** [comment]
> > > will this work as it is with MySQL 8.0 and above or we still need some other code changes?
> > 
> > 
> > I've actually no idea, I just found it on https://github.com/apache/fineract/pull/638/files and it seemed like a good idea!
> 
> Want to switch MySQL version on Travis to 8.0 and see?...Just curious...MySQL 5.5 to 5.7 support is great. Maybe an experiment for another day.

@xurror , @thesmallstar , @percyashu ..Anyone has time to play around with this?

**Comment by vorburger** [comment]
I've created https://issues.apache.org/jira/browse/FINERACT-897 re. MySQL v8.

**Comment by awasum** [comment]
Post Merge Travis Check fail: https://travis-ci.org/github/apache/fineract/builds/676407979
image

Anyone know why? Something might be broken somewhere..Something critical.

**Comment by nemux** [comment]
I started this, during my testing it seems to work fine (CRUD operations over entities) but i think it need to be tested deeply to be shure that nothing is break. One little observation, in when you specify the schema name in the query, you need to add the string ?serverTimezone=UTC this in in files: fineract-provider/src/main/java/org/apache/fineract/infrastructure/core/boot/db/DataSourceProperties.java line 51 

imagen

and I created he file fineract-provider/src/main/resources/sql/migrations/list_db/V1_2__updated_connection_string_option.sql

imagen

Originally in https://github.com/apache/fineract/pull/638

**Comment by awasum** [comment]
> I started this, during my testing it seems to work fine (CRUD operations over entities) but i think it need to be tested deeply to be shure that nothing is break. One little observation, in when you specify the schema name in the query, you need to add the string ?serverTimezone=UTC this in in files: fineract-provider/src/main/java/org/apache/fineract/infrastructure/core/boot/db/DataSourceProperties.java line 51
> 
> imagen
> 
> and I created he file fineract-provider/src/main/resources/sql/migrations/list_db/V1_2__updated_connection_string_option.sql
> 
> imagen
> 
> Originally in #638

Thanks @nemux , Do you want to pick up from this merged PR..and add the required changes to make this work. We will greatly appreciate that. See: https://issues.apache.org/jira/browse/FINERACT-897

Also join the mailing list of Fineract and Mifos: https://mifos.org/resources/community/communications/ so we communicate there.

**Comment by awasum** [comment]
> > I started this, during my testing it seems to work fine (CRUD operations over entities) but i think it need to be tested deeply to be shure that nothing is break. One little observation, in when you specify the schema name in the query, you need to add the string ?serverTimezone=UTC this in in files: fineract-provider/src/main/java/org/apache/fineract/infrastructure/core/boot/db/DataSourceProperties.java line 51
> > imagen
> > and I created he file fineract-provider/src/main/resources/sql/migrations/list_db/V1_2__updated_connection_string_option.sql
> > imagen
> > Originally in #638
> 
> Thanks @nemux , Do you want to pick up from this merged PR..and add the required changes to make this work. We will greatly appreciate that. See: https://issues.apache.org/jira/browse/FINERACT-897
> 
> Also join the mailing list of Fineract and Mifos: https://mifos.org/resources/community/communications/ so we communicate there.

ALso, we cannot completely switch to MySQL JDBC Driver because of License issues... there is a work around proposed here: https://github.com/apache/fineract/pull/760

**Comment by vorburger** [comment]
@nemux could you engage on https://issues.apache.org/jira/browse/FINERACT-901 on the TZ thing?

**Comment by nemux** [comment]
Sure, let me work no that

**Pull request merged**
