### PR TITLE
FINERACT-1837: DelinquencyBucketsIntegrationTest performance

### PR DESCRIPTION
**Pull request by josehernandezfintecheandomx**
## Description

DelinquencyBucketsIntegrationTest.testLoanClassificationStepAsPartOfCOB test is running for 10 mins.

This test need to be refactored to decrease the execution time drastically.

[FINERACT-1837](https://issues.apache.org/jira/browse/FINERACT-1837)

- After enhancement (1m)
Screenshot 2022-12-23 at 0 17 02

- Before enhancement (12m)
Screenshot 2022-12-27 at 13 14 21

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by galovics — APPROVED** [review]

**Comment by galovics** [comment]
@josehernandezfintecheandomx can you please add a screenshot about the time it took originally for the test to run and after your changes?

**Comment by josehernandezfintecheandomx** [comment]
> @josehernandezfintecheandomx can you please add a screenshot about the time it took originally for the test to run and after your changes?

@galovics Done!

**Comment by galovics** [comment]
@josehernandezfintecheandomx can you do a rebase on this PR please? The PostgreSQL tests are failing for the 4th time, maybe a rebase will fix it.

**Comment by galovics** [comment]
@josehernandezfintecheandomx can you do a rebase on this PR please? The PostgreSQL tests are failing for the 4th time, maybe a rebase will fix it.

**Pull request merged**
