### PR TITLE
FINERACT-1432:DropDown-in-ClientDocuments

### PR DESCRIPTION
**Pull request by rrpawar96**
## Description

https://issues.apache.org/jira/browse/FINERACT-1432

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by francisguchie** [comment]
@rrpawar96  

I think we should not hard cord INSERT INTO fineract_default.m_code let it be
INSERT INTO m_code

I started a review of the sql code in file  V284_1__clientdoc-code.sql  please look at it

**Comment by rrpawar96** [comment]
> @rrpawar96
> 
> I think we should not hard cord INSERT INTO fineract_default.m_code let it be INSERT INTO m_code
> 
> I started a review of the sql code in file V284_1__clientdoc-code.sql please look at it

The comment has been addressed.  @francisguchie

**Comment by ptuomola** [comment]
Hi - can you check the failing integration test? I'm assuming this may be a real failure as the change is to client documents and it is failing on client import... but just to check you may want to rerun the integration tests.

**Comment by rrpawar96** [comment]
Hi @ptuomola, The build is been passed now, the cause of the failure was the sequencing of the SQL script. I like to keep scripts after a similar SQL script and some of the test cases fetch the record by id (auto-increment) and not by code-name. So now re-arranged the SQL script by changing the name after the last row of the table got updated and build passed.

**Comment by ptuomola** [comment]
Hi - just wondering: is there a reason why we need a new API for this? Why not just define it as one of the codes (as you are already doing) and get the values for the dropdown using the existing codes API (e.g. codes/xx/codevalues)? We'll end up with a lot of APIs if we define a separate one for each code...

**Comment by rrpawar96** [comment]
@ptuomola, Thanks for reviewing, Comment has been addressed, Removed the newly made API to access code

**Pull request merged**
