### PR TITLE
add "Instructions how to run for local development" to README

### PR DESCRIPTION
**Pull request by vorburger**
hoping to change "tomcatRunWAR" to "bootRun", later (FINERACT-730/FINERACT-764)

### CODE REVIEW

**Comment by awasum** [comment]
Why is this now failing? Just README was updated.. seems strange... Anyone has an idea why?
Am curious...I will pull this to my local dev env and run Integration tests manually and see...
Maybe I just close this and reopen the PR for Travis to run again?

**Comment by mohitsinha** [comment]
@awasum This happens a few times. I have faced this issue myself. I wasn't able to figure out much because it is very difficult to understand from the travis logs, which tests failed. Currently the test report in HTML isn't available for us to debug the issue.

**Comment by awasum** [comment]
@mohitsinha its passing now after closing and reopening.

**Comment by mohitsinha** [comment]
@awasum But the root cause of this infrequent random failure should be found out. Making the test reports public after travis run can be benefecial.

**Comment by vorburger** [comment]
@awasum @mohitsinha re. giving more details about test failures on Travis CI, you may be be interested in reading the comments and linked issues re. the back and forth for `./gradlew test` with and without `--info` [at the end of .travis.yml](https://github.com/apache/fineract/blob/develop/.travis.yml) ...

**Comment by mohitsinha** [comment]
@vorburger Thanks a lot. Now I understand.

**Pull request merged**
