### PR TITLE
FINERACT-1724: Correct descriptions and summary on DELETE and PUT

### PR DESCRIPTION
**Pull request by wkigenyi**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by galovics** [comment]
Please do a `./gradlew spotlessApply` and then the tests will pass.

**Comment by vidakovic** [comment]
@wkigenyi ... could you please create a Jira ticket - a generic one... something like "Ongoing OpenAPI fixes" - for ongoing improvements of the OpenAPI manifest/annotations and format this PR title properly (e. g. "FINERACT-XXXX: Ongoing OpenAPI fixes -  GL Account"; even if we ignore the reference to a Jira ticket (important for changelog when we do releases) then your current title does not give any indication where these changes are applied (we have a lot of DELETE and PUT annotated endpoints). Thanks.

**Comment by wkigenyi** [comment]
Will do in a about 3 hours. Thanks

**Comment by jdailey** [comment]
This isn't linked properly to a Jira ticket .  please correct.

**Review by galovics — APPROVED** [review]

**Pull request merged**
