### PR TITLE
FINERACT-821 Added and Enforced GenericWhitespace Checkstyle

### PR DESCRIPTION
**Pull request by thesmallstar**
Changes needed are already covered in #1055

### CODE REVIEW

**Comment by thesmallstar** [comment]
Regarding change in our formatter-xml, checkstyle and formatter xml did not agree on whether to add space after Generic token (" > " ), I have enforced the formatter to follow checkstyle and I think that is expected to be done in rest of he PRs.

**Review by vorburger — COMMENTED** [review]
@ptuomola do you have any view/preference about this, one way or another? Fine like this for you?

**Comment by thesmallstar** [comment]
For your reference, @vorburger @ptuomola  https://checkstyle.sourceforge.io/config_whitespace.html#GenericWhitespace

**Comment by ptuomola** [comment]
@vorburger I personally (slightly) prefer the no-whitespace option, so looks good to me!

**Pull request merged**
