### PR TITLE
clean-up to remove apparently unused PORT ENV (related to FINERACT-762)

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
In addition to https://issues.apache.org/jira/browse/FINERACT-762, see also future https://issues.apache.org/jira/browse/FINERACT-889 for more background about this.

**Comment by vorburger** [comment]
PR failed due to SchedulerJobsTest > testSchedulerJob (see https://jira.apache.org/jira/browse/FINERACT-852) ... let's close and re-open tomorrow to see if a new build goes through.

**Comment by vorburger** [comment]
This failed due to what #764 will fix (work around, deactivating test..); let's rebase this once that is in.

**Comment by awasum** [comment]
#764 has been merged. lets run this or rebase with develop and see.

**Comment by vorburger** [comment]
@awasum this PR just passed the build, and I'll self merge it, assuming you'll have no objections. (FTR: There are still flaky test problems, this one seems to have passed more by chance, others failed; I'll follow-up.)

**Pull request merged**
