### PR TITLE
FINERACT-1015: Moving OpenJPA Enhance builder from automatic to manual

### PR DESCRIPTION
**Pull request by ptuomola**
## Description
Makes the OpenJPA Enhance builder to be a manually triggered external tool in Eclipse, rather than an automatically triggered builder

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vorburger** [comment]
Build will likely fail here as in other recent PRs due to FINERACT-855 - please help us fix it.

**Comment by vorburger** [comment]
This will have to be re-based after #968 for FINERACT-1016 for the build to pass.

**Comment by ptuomola** [comment]
@vorburger  - rebased. When you get a chance, can you check if this works for you and addresses the issue about frequent runs of enhance?

**Comment by vorburger** [comment]
@ptuomola can I ask, more out of curiosity, why you chose to move the `*.launch` from `fineract-provider/.externalToolBuilders/` out into `config/` and document manually importing it? The way it used to be, but just not `"incremental,auto,"` seemed.. very "smooth", and saves a user the _File->Import->Run/Debug->Launch Configurations_.

**Comment by ptuomola** [comment]
@vorburger For a project builder, you have to choose at least one of the options from: after a clean, during manual builds, during auto builds, during a clean. I thought choosing "during manual builds" should stop the repeated running and still allow the user to trigger this by doing a manual build. 

But when I tried this, the behaviour seemed to be somewhat inconsistent and I wasn't able to find a way to consistently ensure the task was triggered when I wanted it to be. That's why I thought the easiest solution would be just to make it an external builder that you can trigger manually separately from the rest of the build.

But we can also try the option of sticking with a project builder on setting "manual" and seeing if it does consistently do what we expect...

**Comment by ptuomola** [comment]
Not sure if this change is needed afterall. I've been using the automatic builder for a while, and haven't had any major problems with it.

**Comment by vorburger** [comment]
> Not sure if this change is needed afterall. I've been using the automatic builder for a while, and haven't had any major problems with it.

@ptuomola agreed, it seems to actually work not so bad for me as well, now. Do you want to just close this PR then?

**Pull request closed without merging**
