### PR TITLE
Add FineractClientTest.testInvalidOperations (FINERACT-1221)

### PR DESCRIPTION
**Pull request by vorburger**
see FINERACT-1221

### CODE REVIEW

**Review by vidakovic — APPROVED** [review]
LGTM

**Comment by vidakovic** [comment]
@vorburger looks like there are currently some conflicts with upstream. FYI

**Review by ptuomola — APPROVED** [review]
LGTM... happy to merge once the build completes

**Comment by vorburger** [comment]
I'm going to go ahead and self-merge this one, based on the x2 LGTM above.

**Pull request merged**
