### PR TITLE
Fix: Client Family Member editing issue (FINERACT-1314)

### PR DESCRIPTION
**Pull request by BLasan**
## Description

See [FINERACT-1314](https://issues.apache.org/jira/browse/FINERACT-1314)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by BLasan** [comment]
@thesmallstar @Sanyam96 Please review

**Comment by thesmallstar** [comment]
LGTM, did you also test and the given USE case works now?

**Comment by BLasan** [comment]
> LGTM, did you also test and the given USE case works now?

Yuh, tested this. Worked fine. But we can ask @bharathgowda to verify the changes too.

**Comment by bharathcgowda** [comment]
@BLasan  thank you for looking into this swiftly.
It is working fine. I will test it again from develop branch it is merged.

**Comment by BLasan** [comment]
> @BLasan thank you for looking into this swiftly.
> It is working fine. I will test it again from develop branch it is merged.

@thesmallstar

**Comment by thesmallstar** [comment]
LGTM, tests passed. Merging this
Thanks @BLasan

**Pull request merged**
