### PR TITLE
FINERACT-1105 Swagger generates valid Spec File

### PR DESCRIPTION
**Pull request by Grandolf49**
## Description
This is a backport PR of #1270 for adding the changes in Fineract `1.4.0` version 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by vorburger — APPROVED** [review]
Backporting this to 1.4.0 is fine with me, but I'd prefer the Release Manager (RM) @vidakovic to LGTM and merge this, it should be his discretion.

**Comment by vidakovic** [comment]
@vorburger fine with me...  I'll pick this up for 1.4.0

**Comment by vidakovic** [comment]
@vorburger Could you let me know which steps you executed to merge this PR into 1.4.0?

**Comment by vorburger** [comment]
> @vorburger Could you let me know which steps you executed to merge this PR into 1.4.0?

Nothing special, but note how at the very top of this PR, or likewise e.g. on #1278 it says (said) _wants to merge 1 commit into apache:1.4.0_ ? Basically on GitHub when you (anyone) raises a PR, there's a drop-down at the top to choose what branch you are proposing a change for. So for this PR @Grandolf49 (not me) suggested a change for `1.4.0` instead of `develop` to the project, and I'm doing the same in #1273.

To merge it, after you gave your OK in the previous comment, I then just clicked the Rebase and Merge button! :smiley:

**Pull request merged**
