### PR TITLE
Use of Lombok Getter annotation in GroupLevelData

### PR DESCRIPTION
**Pull request by Malaydewangan09**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by Zeyad2003** [comment]
Hi @Malaydewangan09 

I think you missed some instructions from [CONTRIBUTING.md](https://github.com/apache/fineract/blob/develop/CONTRIBUTING.md).
You need to mention the Jira ticket in your PR to be reviewed and track the changes.

Regards!

**Comment by Malaydewangan09** [comment]
Hey @Zeyad2003 
I checked through Jira tickets 
But this was not there, this was me just trying to start it out here.

**Comment by Zeyad2003** [comment]
You can create a sub-task under this [improvement](https://issues.apache.org/jira/browse/FINERACT-1586).
e.g. "Introduce Lombok to group module" 
then refer to it in your PR.

**Comment by Malaydewangan09** [comment]
Okay cool, thanks @Zeyad2003

**Comment by vidakovic** [comment]
@Zeyad2003 Please follow the conventions on how to format the pull request title ("FINERACT-1234: Title of the JIRA ticket")

**Pull request closed without merging**
