### PR TITLE
FINERACT-835: Upgraded Swagger Annotations to Annotations 2.0

### PR DESCRIPTION
**Pull request by ptuomola**
FINERACT-835

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by thesmallstar** [comment]
Travis failed because:
> The job exceeded the maximum log length and has been terminated.

**Comment by ptuomola** [comment]
Yes the resolve task of Swagger plugin for some reason ends up with log level DEBUG and produces a lot of output. Need to find a way to set the log level to something more sensible...

**Comment by ptuomola** [comment]
Ok - think I found a way to sort out the excess logging from :resolve: and :enhance:

Let's see if this build gets through...

**Comment by ptuomola** [comment]
So looks like now it's not failing because of log levels, but because the Swagger resolve task takes so much memory that Docker inside Travis can't handle it and kills the build. Need to see if there's a way to either reduce memory usage by resolve or give Docker more memory...

**Comment by ptuomola** [comment]
Right - seem to have fixed both the Travis logging as well as memory issues with the build

@vorburger Here's a PR ready to update all the Swagger Annotations to 2.0 - after that, majority of the content should be in fineract.json. What's still missing is the overview (beginning of the file) that needs to be passed in as a config file to the plugin, and then finetuning of the output (for example, why do we have attribute descriptions as freetext in the summary rather than in the schemas for each attribute). And of course all the other stuff that was planned (i.e. getting "Try this API" to work etc). But I'm happy to leave that for someone else...

**Comment by vorburger** [comment]
I've resolved the conflicts caused by #1083 and will merge this when it passes the build (or another committer can).

**Review by vorburger — APPROVED** [review]

**Pull request merged**
