### PR TITLE
remove (useless) SenderTest + mockrunner-jms/nekohtml (FINERACT-938)

### PR DESCRIPTION
**Pull request by vorburger**
follow-up to #829

see FINERACT-938

@ptuomola does this LGTY?

### CODE REVIEW

**Comment by awasum** [comment]
@Anh3h Just adding you to review this PR as you also worked on the Notification module. You may have a better view than me.

**Comment by ptuomola** [comment]
@vorburger Definitely great if we can get rid of Mockrunner with its awful dependency tree. What I can't comment on is the value of this test - was it testing anything useful - and whether we had plans to build more tests like it?

**Comment by vorburger** [comment]
> value of this test - was it testing anything useful 

Just from looking at it, I don't see this `SenderTest` doing anything particularly useful. It doesn't `assert` on anything. I doubt this adds any real value in testing Fineract's JMS support; e.g. I don't think this test would reliably catch any possible regressions in Fineract's JMS support. (Which isn't exactly it's top most used feature anyway, as far as I know.)

> and whether we had plans to build more tests like it?

according to [git log history](https://github.com/apache/fineract/commits/develop/fineract-provider/src/test/java/org/apache/fineract/notification/SenderTest.java), it was written 3 years ago, by @adhyans ... Adhyan, if you are still alive and have any interest in Fineract, would be interested to chime in here and let us know if you can still sleep well at night :smile: if we delete this `SenderTest`? It's dependency on `mockrunner-jms` was giving us a hard time (see FINERACT-846 and FINERACT-938), and we don't' see much value in that particular test anymore, compared to the dependency management headache its use of `mockrunner-jms` (which is, at least now, only used in that test), and we'd like to remove it. Do you have any strong objections?

**Comment by vorburger** [comment]
Anyone reading, chime in on FINERACT-944 for a more general discussion re. the Notifications feature.

**Comment by vorburger** [comment]
I've just rebased this and resolved conflicts. @awasum given that we haven't heard back from @Anh3h within 1 week, and that @ptuomola expresses support for _"great if we can get rid of Mockrunner with its awful dependency tree"_ and my explanations about the value of this test, would you have any strong objections to merging this? It's a simplification of our dependencies which we will only be grateful for in the future, at the loss of a IMHO useless test.

**Comment by awasum** [comment]
Please, merge it now. I just wanted someone familiar with the notification
feature to look at it. But we can't keep waiting for that forever. So merge
this ASAP. Thanks and sorry for holding this  that's precious time but it
was for a good reason.

**Pull request merged**
