### PR TITLE
FINERACT-822 enable JdkObsolete error

### PR DESCRIPTION
**Pull request by percyashu**
FINERACT-822

### CODE REVIEW

**Review by vorburger — APPROVED** [review]
LGTM

**Comment by percyashu** [comment]
@xurror @awasum @vorburger merge this?

**Review by xurror — APPROVED** [review]
LGTM. Squash the commits and this will be good to go. That is once the build passes.

**Comment by awasum** [comment]
Woow... @vorburger  Error Prone is an eye opener. Thanks for the recommendation to use this.

For this issue: https://errorprone.info/bugpattern/JdkObsolete

I will never work on a project without first adding code quality checks.

**Review by xurror — COMMENTED** [review]
Awesome

**Comment by vorburger** [comment]
@awasum you should TWEET that at me? ;-) I'll Like it.

**Pull request merged**
