### PR TITLE
FINERACT-1725: Introduce Lombok to JournalEntry module

### PR DESCRIPTION
**Pull request by hmg65**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by galovics** [comment]
@hmg65 PR is conflicting and there are build issues, please check.

**Comment by vidakovic** [comment]
@hmg65 ... is this still a work in progress? Just asking, because the PR seems a bit old (3 weeks) and you have newer PRs queued up. If this is still relevant then maybe fix this one first before you move on to newer stuff. Or, if it's not relevant anymore then please close it.
Also: please format title properly if this PR is still relevant.
Thanks

**Comment by jdailey** [comment]
The Dev needs to make sure there is sufficient test coverage and the design is discussed on list.  If the JIRA Ticket is present, it needs to be linked and the title of the PR needs to be changed.

**Comment by BLasan** [comment]
@hmg65 Please resolve the conflicts

**Pull request closed without merging**
