### PR TITLE
 clean up GLAccountBuilder, following SpotBugs (FINERACT-702) 

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by awasum** [comment]
Which one are you merging first. This or #682 ?

@vorburger thanks very much for taking the time to review and augment the spotbug integration work. I am grateful.

**Comment by vorburger** [comment]
> Which one are you merging first. This or #682 ?

#682 just merged, this one was actually just an extension with 1 more additional commit over that one. There's no real good way to do this better in GitHub (that I know of), so what I "imply" (but should say more clearly?) when I raise a PR like this one for review is to manually click on the last commit of such a PR (in the _Commits_ tab) in review that, instead of everything on the _Files changed_ tab (or use that Changes from drop down on _Files changed_ to review only last commit instead of _from all commits_).

> @vorburger thanks very much 

You are the one to thank, this (that we've finally properly adopted SpotBugs here) is amazing!

If this small PR is OK with you, just go ahead and merge it (use _Rebase and merge_ to avoid the merge commit, because #684 is "parallel"). -- PS: I hope this doesn't fail in Integration Test again due to [FINERACT-820](https://issues.apache.org/jira/browse/FINERACT-820) - as it's Sunday...  if it does, we really should figure out how to fix that problem.. or ask on list if anyone would like to take that on.

**Comment by vorburger** [comment]
>  PS: I hope this doesn't fail in Integration Test again due to [FINERACT-820](https://issues.apache.org/jira/browse/FINERACT-820) - as it's Sunday... if it does, we really should figure out how to fix that problem.. or ask on list if anyone would like to take that on.

It did, this is really annoying.. are you willing to just review and merge this ignoring that `LoanReschedulingWithinCenterTest` failure? Or motivated to investigate how that could be fixed properly once and for all? I'll drop an email to the list as well.

**Comment by awasum** [comment]
This looks good merging now.

**Pull request merged**
