### PR TITLE
Added Empty Statement Check and enforced checkstyle

### PR DESCRIPTION
**Pull request by thesmallstar**
## Description
No functional changes, Code formatting , indent fix and empty statement checktyle enforce :) 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vorburger** [comment]
@thesmallstar this seems to include an (arbitrary?) number of "break lines up" changes - was that intentional? It would perhaps be clearer both for me to review and for you to do if in each PR you only include the changes strictly required to make the respective module (here `EmptyStatement`) pass? Just a thought.

**Comment by thesmallstar** [comment]
@vorburger, agreed on your point,making changes.

**Comment by thesmallstar** [comment]
Not sure why integration tests failed, probably due to other PR? If not, I will give a detailed look tomorrow.

**Comment by vorburger** [comment]
> Not sure why integration tests failed, probably due to other PR? If not, I will give a detailed look tomorrow.

@thesmallstar re. build failure, please subscribe to and watch (or help fix??) #764 and #761 for [FINERACT-852](https://issues.apache.org/jira/browse/FINERACT-852)...

**Comment by vorburger** [comment]
@thesmallstar Following #764 and #761 this will pass the build (or not at least not fail because of integration tests) if you rebase this now.

**Comment by thesmallstar** [comment]
@vorburger , thank you for the update. Sorry, I could not reply to the previous comment, I had been busy in online college exams.
-thanks :)

**Comment by thesmallstar** [comment]
@vorburger the build failed even after rebase, did I miss something? The build passes locally though.

**Comment by vorburger** [comment]
@thesmallstar @awasum see https://issues.apache.org/jira/browse/FINERACT-886 for another test failure

**Comment by vorburger** [comment]
@thesmallstar @awasum see https://issues.apache.org/jira/browse/FINERACT-898 for another test failure - and this one is very very weird...

**Comment by vorburger** [comment]
@thesmallstar please rebase and fix merge conflict from #767.

The build error due to FINERACT-898 hopefully will disappear.

**Comment by vorburger** [comment]
@thesmallstar this failed again due to an IntegrationTest, see [FINERACT-857](https://issues.apache.org/jira/browse/FINERACT-857). Could I suggest that we please proceed as follows from now on: Any integration test failure you see in your (or anyone else's, for that matter...) PR, please from now on just search for the failing test in JIRA, comment on it like I do, and then raise a dedicated small PR to `@Ignore` the respective failing test, with a TODO for that JIRA, similar to e.g. my #761? Do that for you here for FINERACT-857, and also for me for FINERACT-855 for #779? Thanks!  /Cc @awasum FYI.

PS please ignore the failed Build - Summary, and only look at Travis (see [FINERACT-907](https://issues.apache.org/jira/browse/FINERACT-907)).

**Comment by xurror** [comment]
@thesmallstar, any follow up on this?

**Comment by thesmallstar** [comment]
hello @xurror , updating it.
-Thanks
Manthan

**Comment by thesmallstar** [comment]
if the build still fails, I will look into the "flaky" tests.
Edit: The build failed,  fixing it.

**Comment by xurror** [comment]
Does not look like our typical IT tests.

**Comment by thesmallstar** [comment]
thank you @xurror!!
@vorburger you can give the final review :D

-thanks 
Manthan

**Comment by xurror** [comment]
Sure. if this is good for @vorburger, I think this OK to merge.

**Review by vorburger — APPROVED** [review]
LGTM!

**Pull request merged**
