### PR TITLE
Reenable sonarqube scan as GH action

### PR DESCRIPTION
**Pull request by galovics**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by ptuomola** [comment]
Hi - looks like this is failing due to the missing credentials as secrets. Did you try adding the required secrets to GitHub? @vorburger posted the instructions on how to do this earlier but I haven't had a chance to try them yet.

**Comment by vidakovic** [comment]
@ptuomola ... first we would need the credentials... do you have them? BTW: we'll share these things now on 1password... you should have received an invite.

**Comment by galovics** [comment]
@ptuomola yeah, I was trying to figure out what credentials we have configured for the repo since I don't have the access to see that. In addition, as @vidakovic said, we would need to credentials but as soon as those 2 things are resolved and the credentials are configured for the repo, we're free to relieve the Travis build from the duties and switch over completely to GH Actions.

**Comment by ptuomola** [comment]
If I recall @vorburger's explanation correctly, I don't think it's possible to see / configure secrets through the Github GUI - what we need to do is to push the secret using the Github REST API. I think I have the rights now to create a new SonarQube token but I haven't tried pushing any secrets using the REST API, so not sure how easy that is...

**Comment by vidakovic** [comment]
as for setting secrets on Github: if I'm not mistaken we need to place a
Jira ticket in Apache Infrastructure... these guys are the only ones who
have full access...

Having said that: we should investigate these Apache Wiki pages
https://cwiki.apache.org/confluence/display/INFRA/Github+Secrets+and+Tokens

**Comment by vidakovic** [comment]
... as I see it that Sonar token is already defined on an org level for all
Apache projects at Github... so no need to create anything else as I see
it... same for Docker Hub (which is great... because that was the next
thing I needed for the releases)...

**Comment by ptuomola** [comment]
That’s great. Let me see if I can find a way to grant that token an access
to our project

**Comment by galovics** [comment]
@ptuomola any luck so far?

**Comment by ptuomola** [comment]
Sorry - my dev machine died, so have been without access for a while...

However I've just enabled the user gmcdonald with permissions to execute
analysis on our Fineract sonarcloud project.

If I understood the wiki page correctly, this should mean we can now use
the prepopulated sonarcloud token secret to trigger the analysis?

Regards
Petri

**Comment by vidakovic** [comment]
Hi Petri... I came across this issue coincidentally today... I think we are
using the "wrong" project handle on Sonarcloud... because Apache (the org)
has prepared them for all of their projects... the one we are using - as I
understand it - was created "manually"... but there is another one... kind
of the official Sonar project slug for Fineract... if you search for
Fineract you'll see it immediately... the other thing is empty.

Having said that: by default our Github repo should already contain the
secret for our "official" Sonar project... just FYI

**Comment by ptuomola** [comment]
Hi Aleks

The one we've been using is this:

https://sonarcloud.io/project/overview?id=apache_fineract

I believe this was created by Victor (?) and he granted me access to it a
couple of months ago. I've also granted the access to the account with what
the token was created today - so hopefully the secret token should work
now.

There's also a project called "Apache Fineract" in Sonarcloud:

https://sonarcloud.io/project/configuration?id=fineract

I don't know who has access to this and how it had been configured. If it
already has the token authorized we can of course also use that.

Should be pretty easy to try accessing either/both from the GitHub action
with the existing secret token. Maybe someone can give this a go?
Alternatively I can try it when I get my machine back…

Regards
Petri

**Comment by vidakovic** [comment]
aha... now both projects show data... yesterday night one of them was
definitely empty... but the one you just sent seems to be the right one
(under Apache)... we should be good here.

**Comment by galovics** [comment]
guys, I'm kinda lost in the discussion. Are you suggesting the secrets are already configured within GitHub? If so, what are the keys I should reference in the workflow?
Tbh, I'd love to get rid of the Travis builds ASAP because it just takes an enormous amount of time to run them.

**Comment by ptuomola** [comment]
I've created a new pull request that fixes the authentication issue - seems to work at least at first glance. See https://github.com/apache/fineract/pull/2289

**Pull request closed without merging**
