### PR TITLE
Fix broken link in README.md

### PR DESCRIPTION
**Pull request by HarimbolaSantatra**
## Description

There was a broken link in the README.md file. I fixed it.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [X] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by galovics** [comment]
@HarimbolaSantatra please rebase your PR to the latest develop, it's gonna fix the build issues.

**Comment by galovics** [comment]
@HarimbolaSantatra unfortunately you did a merge instead of a rebase. Please ensure you have a single commit in your PR reflecting the changes.

**Comment by HarimbolaSantatra** [comment]
#3766 is a more complete version of this PR. Sorry for the inconvenience 😅

**Comment by HarimbolaSantatra** [comment]
#3766 is a more complete version of this PR. Sorry for the inconvenience 😅

**Pull request closed without merging**
