### PR TITLE
field name issue fixed FINERACT-1382

### PR DESCRIPTION
**Pull request by danishjamal104**
## Description

`unassignedDate` field renamed to `approvedOnDate`, to meet the api expectations.

[JIRA ticket #1382](https://issues.apache.org/jira/browse/FINERACT-1382).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by awasum — DISMISSED** [review]
LGTM. Even though its difficult to test every Swagger API change. This is not risky to merge.

**Comment by awasum** [comment]
JIRA issue: https://issues.apache.org/jira/browse/FINERACT-1382

**Comment by danishjamal104** [comment]
> LGTM. Even though its difficult to test every Swagger API change. This is not risky to merge.

Keeping that in mind, I have created multiple PRs with very small and specific changes. Thanks for the review

**Comment by ptuomola** [comment]
True - there is no risk. But what I was hoping for is that we could create tests for these at the same time...

**Comment by awasum** [comment]
@danishjamal104 , I wonder if you have been able to add any tests as @ptuomola asked in PR: https://github.com/apache/fineract/pull/1828

How difficult is it to add those test to make sure the Swagger Docs are actually correct? see: https://stackoverflow.com/questions/39620552/generate-unit-test-code-from-swagger-api-for-java-rest

@ptuomola  I see your point.

**Comment by ptuomola** [comment]
I think we already have a “stub” for fineract-client test in fineract/fineract-client/src/test/java/org/apache/fineract/client/test - it should be easy to add to this or create more similar tests in the same package. 

My suggestion would be to:

a) for each Swagger API that is fixed, add a test to show that it works
b) add running the tests to integration tests in Travis so that the build fails if these tests fail

That way we could ensure that a) the fixes are correct and b) the code works not just now but also in the future...

**Comment by danishjamal104** [comment]
@ptuomola , please check I have added the test case for testing the `savings account` activation part using the fineract client.
Thanks

**Comment by thesmallstar** [comment]
@danishjamal104 travis tests failing..

**Comment by danishjamal104** [comment]
> @danishjamal104 travis tests failing..

I have made changes in `SavingsAccountsApiResourceSwagger.java` and added new test SavingsAccountsTest.java in integration module. But the travis build is failing because of `SchedulerJobsTest > testDateFormat()`, check out below SS `line 2363`. So what possible may be the cause of this build failed, @ptuomola and @awasum could you please take a look. Thanks

Screenshot 2021-08-29 at 8 13 54 PM

**Comment by ptuomola** [comment]
Sometimes the tests may be a bit "flaky" - you may want to retrigger a build to see if that works better...

**Comment by danishjamal104** [comment]
> Sometimes the tests may be a bit "flaky" - you may want to retrigger a build to see if that works better...

do other contributors have option to trigger the build without pushing new commit to this PR??

**Comment by danishjamal104** [comment]
> > Sometimes the tests may be a bit "flaky" - you may want to retrigger a build to see if that works better...
> 
> do other contributors have option to trigger the build without pushing new commit to this PR??

okay, I got it. I closed and opened the PR for triggering it again.

**Review by ptuomola — APPROVED** [review]
LGTM... ideally the integration tests should not depend on each other - i.e. if you need a ID for a savings account, then in the same test create the account to get one - don't rely on another test having created it. But having this test is much better than having no tests, so I'll merge this...

**Pull request merged**
