### PR TITLE
FINERACT-111 Do not update charges amount paid if loan transaction is accruals

### PR DESCRIPTION
**Pull request by thesmallstar**
## Description
I found this issue with a small task, I am not sure about the background this needs to be verified.
https://issues.apache.org/jira/projects/FINERACT/issues/FINERACT-111?filter=allopenissues

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by xurror** [comment]
This needs functional review, @emmanuelnnaa  please can you check this.
Aside from that, I think this is OK.

**Comment by vorburger** [comment]
@emmanuelnnaa can you confirm this is good to merge? @xurror can you ping someone to confirm?

@awasum do you know anyone we can get to sign off on this?

Otherwise I suggest we just merge it in 2 weeks, based on "trust".

**Comment by awasum** [comment]
> @emmanuelnnaa can you confirm this is good to merge? @xurror can you ping someone to confirm?
> 
> @awasum do you know anyone we can get to sign off on this?
> 

I don't know. maybe @nazeer1100126 , @vishwasbabu  or @avikganguly01 can help us?

> Otherwise I suggest we just merge it in 2 weeks, based on "trust".

Fine with me

**Comment by vorburger** [comment]
Nobody seems to be willing to step up for functional testing, so I'm just merging this..

**Pull request merged**
