### PR TITLE
Net Disbursal Amount Feature (FINERACT-1321)

### PR DESCRIPTION
**Pull request by Cadreia**
## Description

* Implements the net disbursal amount feature.
* Details of this issue can be found on this [Apache Fineract JIRA ticket](https://issues.apache.org/jira/browse/FINERACT-1321).
* An [article]( https://research.muellners.org/adding-nda-logic/) has been written on this.
* Corresponding UI change is [here](https://github.com/openMF/community-app/pull/3421).

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by awasum** [comment]
This looks interesting. Thanks for the PR @Cadreia , Can you update the PR to fix the merge conflicts? Sorry for the delay.
@francisguchie and @bharathc27 , Please can you help us test functionally test this? You can ask all the relevant questions here.

@Cadreia  Does this change have or need a corresponding UI change or PR?

**Review by ptuomola — APPROVED** [review]
LGTM

**Comment by ptuomola** [comment]
Hi @Cadreia - code looks all good, but looks like the build is failing and there are some merge conflicts. Could you resolve these, squash the commits, put the JIRA issue number into the commit message please, and we can then merge this in? Thanks!

**Comment by Cadreia** [comment]
Conflicts have been resolved and build passes now. Please review. Link to the PR for the corresponding UI change is in the description above.

**Review by xurror — APPROVED** [review]
LGTM

**Pull request merged**
