### PR TITLE
Added One Statement per line check and Enforced checkstyle

### PR DESCRIPTION
**Pull request by thesmallstar**
## Description
This will probably have a merge conflict with #763, depending upon which is merged first. Will solve the conflict accordingly.

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vorburger** [comment]
@thesmallstar re. build failure, please subscribe to and watch (or help fix??) #764 and #761 for [FINERACT-852](https://issues.apache.org/jira/browse/FINERACT-852)...

**Comment by vorburger** [comment]
@thesmallstar Following #764 and #761 this will pass the build (or not at least not fail because of integration tests) if you rebase this now.

**Comment by thesmallstar** [comment]
@vorburger , thank you for the update. Sorry, I could not reply to the previous comment, I had been busy in online college exams.
-thanks :)

**Comment by vorburger** [comment]
@thesmallstar @awasum see https://issues.apache.org/jira/browse/FINERACT-899 for another random test failure

**Pull request merged**
