### PR TITLE
executeAndAwaitJob() instead executeJob() in un-ignored FixedDepositTest [FINERACT-950]

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-950

### CODE REVIEW

**Comment by vorburger** [comment]
Build failure here is FINERACT-855 (has nothing to do with this PR for FINERACT-950).

**Comment by vorburger** [comment]
This will have to be re-based after #968 for FINERACT-1016 for the build to pass.

**Comment by vorburger** [comment]
@ptuomola @awasum @xurror does this one LGTY, merge?

**Review by xurror — APPROVED** [review]
It's fine for me. I'll merge this in a few hours if there are no objections.

**Pull request merged**
