### PR TITLE
Fineract-953 - Upgrade ical4j from ancient version 1.0.7 to current 3.0.18

### PR DESCRIPTION
**Pull request by nnatarajan**
FINERACT-953

### CODE REVIEW

**Comment by xurror** [comment]
@nnatarajan We have a classpath duplicate error.

**Comment by xurror** [comment]
Maybe try to exclude groovy-all in dependencies.gradle.

**Comment by vorburger** [comment]
@nnatarajan if stuck/unclear on this, it's totally OK (for me) if you first look at another issue, and come back to this later after someone else had a chance to look at this problem more closely? As @xurror said it probably needs some exclusion, but it's not always very obvious which.. BTW someone could write up a short paragraph for the README with some guidance about how to do these upgrades - anyone interested?

**Comment by nnatarajan** [comment]
@xurror 

I ran the integration test, but this specific error did not come up. How do I duplicate this specific error on my end: **classpath duplicate error**?

**Comment by vorburger** [comment]
It's a unit test (that I wrote..), not an integration test. You can even
easily run that test in your IDE, it should give you the same result?

>

**Comment by nnatarajan** [comment]
Sounds good. Please let me know the best way to access the test.

**Comment by vorburger** [comment]
Find the exact name of that failing test on the Travis CI build log, open
it in your IDE, run it.

>

**Comment by vorburger** [comment]
> Maybe try to exclude groovy-all in dependencies.gradle.

@xurror in this particular case, the problem was different - #911 should hopefully fix it.

**Comment by vorburger** [comment]
There are actually 2 totally separate problems here - the  #911 business (solved), but also some weird incompatibility between this upgrade and the Spotbugs Gradle problem... :sob: @nnatarajan this isn't exactly the greatest "starter issue"... :smiling_imp:  Would anyone else reading this want to help with figuring out the Spotbugs Gradle problem here? /Cc @thesmallstar if you are interested by this sort of thing...

**Comment by vorburger** [comment]
I wonder if that Spotbugs Gradle problem may just disappear with #913 ... worth a rebase, after that's in.

**Comment by awasum** [comment]
#913 and #911 have now been merged.

**Comment by awasum** [comment]
Also see PR https://github.com/apache/fineract/pull/910 which has just been merged for some help.

**Comment by awasum** [comment]
> /rebase

Ohhh..this actually works now? Where was it fixed? What was the problem? Just curious.

**Comment by awasum** [comment]
@nnatarajan ...This now looks more friendly and may be easier to fix? See Travis Log: https://travis-ci.org/github/apache/fineract/builds/689183927
Something about redundant Casting to "Class"

**Comment by vorburger** [comment]
That new problem is just due to the meanwhile merged #908 and should, hopefully, be trivial to resolve... almost there with this one!!

**Comment by nnatarajan** [comment]
@vorburger , is a more experienced dev taking this on? I will remove myself from the ticket if that is the case.

**Comment by vorburger** [comment]
@nnatarajan no no no, you're almost there with this one, we'd love you to finish this off! I've fixed unrelated problems, and you now just need to rebase, fix the latest (new) problem re. the cast, and this should be good to merge very soon! Let's get it done today? Ask if unclear. Sorry for any confusion caused!

**Comment by nnatarajan** [comment]
I removed the casting, but now, within Travis an error is thrown. What is the best way to resolve?:

Verification failed: SpotBugs execution thrown exception

**Comment by vorburger** [comment]
Hm #913 was supposed to fix that. Did you git rebase it from latest develop? It passed here because if you type slash rebase then then the remote branch of the PR gets rebased by a bot, but if you locally fix something and force push, without having rebased locally also, then that remote rebase is overwritten and lost. Does that make sense? Try to locally rebase, ./gradlew build, and if PK, then force push again, it will probably turn green.

**Comment by nnatarajan** [comment]
I had rebased before pushing up modifications and #913 in showing in the code. When I ran locally ./gradlew build -- showing same error.

Does it matter if I running on Java 11?

**Comment by vorburger** [comment]
Curious. You can either try to dig into it, or (totally fine me!) move on to another issue and let me or someone else have a closer look into this some other time.

**Comment by vorburger** [comment]
> I had rebased before pushing up modifications and #913 in showing in the code. 

Ok, great.

> Does it matter if I running on Java 11?

Fineract does not support Java 8 anymore, only Java 11.

> When I ran locally ./gradlew build -- showing same error.

yeah, I just locally pulled this PR, and likewise, I could locally reproduce it as well. Looking into `build/reports/spotbugs/main.html`, we can see that SpotBugs actually picked up on a real subtle but important bug breaking functionality that we would have introduced had we merged this PR as it is currently - thank God for SpotBugs! @nnatarajan will you look into and fix that particular problem here to get this PR to be green.

FINERACT-989 will look into the more general issue (not directly related to this PR) of SpotBug reporting.

**Comment by vorburger** [comment]
While investigating FINERACT-989, I have learnt that @xurror just fixed this problem in FINERACT-986, and I expect the currently running rebased Travis will now show the error much more clearly.

@xurror I don't know if FINERACT-986 was a coincidence, but if it was related to you also investigating this, please do feel free to chime in and leave a comment on any PR next time you help like this - you're great!

**Comment by nnatarajan** [comment]
@vorburger - This morning, I made additional changes to the file. It appears all checks have passed. In addition to yesterday's casting errors, similarly, I found other type errors. I hope this is resolved.

**Review by vorburger — APPROVED** [review]
LGTM!

**Pull request merged**
