### PR TITLE
Idempotency Support (FINERACT-1420)

### PR DESCRIPTION
**Pull request by ptuomola**
## Description

Rebased version of #1951 

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by avikganguly01** [comment]
@ptuomola @IOhacker (cc: @fynmanoj) : If there's anything that we can do to help with idempotency, let us know!

**Comment by awasum** [comment]
I think what is left to be done is to reopen a PR for this..Fix merge conflicts and test to make sure it works. This might be useful for someone. I think no one is working on this at the moment.

**Comment by ptuomola** [comment]
The two things I think would be good to address / test are:

1. Backward compatibility: I don't think we want to add a new mandatory parameter to every single API signature. It would be better if the parameter was optional, and everything would work as-is if the parameter is not passed in
2. Optionality: I don't think everyone wants to set up and manage a new Redis database just to support this feature. So it should be possible to switch this on / off depending on whether this feature is required or not

**Comment by galovics** [comment]
@ptuomola just FYI, I'm going to tackle this in a couple of weeks.

**Pull request closed without merging**
