### PR TITLE
FINERACT-1004 Resolved NPE in AddressWritePlatformServiceImpl.updateC…

### PR DESCRIPTION
**Pull request by nnatarajan**
FINERACT-1004

### CODE REVIEW

**Comment by vorburger** [comment]
Build failure here is FINERACT-855 - please help us fix it.

**Comment by vorburger** [comment]
This will have to be re-based after #968 for FINERACT-1016 for the build to pass.

**Comment by nnatarajan** [comment]
rebased

**Review by vorburger — CHANGES_REQUESTED** [review]
while this would probably fix FINERACT-1004, it would "hide" a real problem.. have a closer look at the related code - when would `clientAddressObj` be null? That should probably be handled and cause an error (throw an exception, but the right one...), with a clear message.

**Review by vorburger — APPROVED** [review]
LGTM

**Pull request merged**
