### PR TITLE
Fix runreports (FINERACT-1345)

### PR DESCRIPTION
**Pull request by josemakara2**
## Description

See FINERACT-1345

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by josemakara2** [comment]
@ptuomola Code review please. Thank you

**Comment by ptuomola** [comment]
@vorburger I wonder if you might have time to take a quick look at this? At first glance this looks like a regression introduced by the earlier refactoring, but I wonder if there's a better way to fix this - e.g. by having findReportingProcessService return DatatableReportingProcessService? But I'm not that familiar with this part of the code so would value your thoughts...

**Comment by josemakara2** [comment]
@ptuomola 
I have updated the pull request. 
Do you think this can go in and when @vorburger gets a chance to look - if he will be wanting us to refactor further then we can always open another PR? Thank you.

**Comment by ptuomola** [comment]
Thanks @josemakara2 

I'm really not familiar with the code & refactoring done here earlier... but let me take a closer look this weekend. If your change seems to fit into the overall pattern I'll merge it in then.

Thanks

**Comment by bharathcgowda** [comment]
@BLasan  and I were able to test it, and functionality-wise, it fixes the issue.
Could we get the code review done and merge it ASAP, as it is a blocker for reporting needs.
@edcable  FYI

**Comment by ptuomola** [comment]
Ok - had a look at this and fully agree with the fix. 

However can I suggest we keep the logic so that the selection of report type is in getReportType() and not split between two different places. Also we should keep the return value from findReportingProcessService() as the generic type, not specific to DatatableReportingProcessService, as otherwise this may break the possible plug-ins for this (e.g. Pentaho reporting plugin). 

To move forward with this, I've made the proposed changes in a separate PR: https://github.com/apache/fineract/pull/1734. Can you check if this fixes the issue for you, and if yes I can then merge it?

**Comment by josemakara2** [comment]
> To move forward with this, I've made the proposed changes in a separate PR: #1734. Can you check if this fixes the issue for you, and if yes I can then merge it?

:thumbsup: +1:  for program to interface, not implementation. 
Tested that in my PR ([see changes](https://github.com/apache/fineract/pull/1693/files))  and yes #1734 can be merged after the `format fix` and then we close this PR. I prefer merge squash to re basing. 
Many thanks

**Comment by josemakara2** [comment]
Closing this in favour of #1734

**Pull request closed without merging**
