### PR TITLE
Fix "Reporting meta-data entry not found" (FINERACT-1306)

### PR DESCRIPTION
**Pull request by vorburger**
see FINERACT-1306

This is a "cleaned up counter-proposal" 😃  to #1620.

@francisguchie @rrpawar96 @ptuomola @vidakovic does this look good to you?

### CODE REVIEW

**Comment by vorburger** [comment]
The 5 commits here are intentionally not squashed exceptionally, to "give attribution" to the work done by others than me here.

**Review by vidakovic — APPROVED** [review]
LGTM

**Comment by vidakovic** [comment]
@vorburger you want more eyes on this or should we merge?

**Comment by vorburger** [comment]
> @vorburger you want more eyes on this or should we merge?

Go ahead and merge it; thanks!

**Comment by v3ss0n** [comment]
Same problem happen on loan reports  latest on current commit.

**Comment by francisguchie** [comment]
@v3ss0n this  issue was solved in the apache-fineract, what you need is to update the libraries of [fineract-pentaho](https://github.com/openMF/fineract-pentaho)

**Comment by v3ss0n** [comment]
@francisguchie  thanks , so even if i am generating Table reports , fineract-pentaho is needed?

**Comment by francisguchie** [comment]
> @francisguchie thanks , so even if i am generating Table reports , fineract-pentaho is needed?
@v3ss0n  No its not needed table reports work like a charm always with no issues as far back as fineract 1.2 that i first used when i joined this noble community

**Comment by v3ss0n** [comment]
Then we have a problem , we tried table reports for loans , they end up with same error as this.
`https://community.fineract.test.com/fineract-provider/api/v1/runreports/Active%20Loans%20-%20Details`

`Possibly unhandled rejection: {"data":{"developerMessage":"The requested resource is not available.","httpStatusCode":"404","defaultUserMessage":"The requested resource is not available.","userMessageGlobalisationCode":"error.msg.resource.not.found","errors":[{"developerMessage":"Reporting meta-data entry not found.","defaultUserMessage":"Reporting meta-data entry not found.","userMessageGlobalisationCode":"error.msg.report.name.not.found","parameterName":"id","value":null,"args":[{"value":"Report Name: Active Loans \\- Details"}]}]},"status":404,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"https://community.fineract.test.com/fineract-provider/api/v1/runreports/Active%20Loans%20-%20Details","params":{"R_officeId":"1","R_loanPurposeId":"-1","R_currencyId":"MMK","R_fundId":"-1","R_loanOfficerId":"-1","R_loanProductId":"-1"},"headers":{"Accept":"application/json, text/plain, */*","Fineract-Platform-TenantId":"default","Authorization":"Basic ooooo="}},"statusText":"","xhrStatus":"complete","resource":{}}
`

**Pull request merged**
