### PR TITLE
Introduce Lombok to accountnumberformat module (FINERACT-1727)

### PR DESCRIPTION
**Pull request by abhinav7sinha**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@abhinav7sinha Please dont forget to run a checkstyle check before committing any new code. It is failing with checkstyle errors as of now.
You can run it by ` ./gradlew spotlessApply`

**Comment by abhinav7sinha** [comment]
> @abhinav7sinha Please dont forget to run a checkstyle check before committing any new code. It is failing with checkstyle errors as of now. You can run it by ` ./gradlew spotlessApply`

Understood, thanks. Doing so now

**Comment by adamsaghy** [comment]
@abhinav7sinha Please dont forget to squash the commits!

**Comment by abhinav7sinha** [comment]
> @abhinav7sinha Please dont forget to squash the commits!

done!

**Comment by adamsaghy** [comment]
@abhinav7sinha Unfortunately, it is not correct as you have merged other people PRs into your PR!
Please try to rebase instead of merge.

**Comment by abhinav7sinha** [comment]
> @abhinav7sinha Unfortunately, it is not correct as you have merged other people PRs into your PR! Please try to rebase instead of merge.

got it @adamsaghy 
I'm converting it to a draft while I test the changes some more

**Comment by abhinav7sinha** [comment]
> > @abhinav7sinha Unfortunately, it is not correct as you have merged other people PRs into your PR! Please try to rebase instead of merge.
> 
> got it @adamsaghy I'm converting it to a draft while I test the changes some more

@adamsaghy I've marked this as ready for review now, thanks!

**Comment by abhinav7sinha** [comment]
checkStyle thinks that AccountNumberFormatEnumerations has a public/default constructor, but I'm using a lombok annotation to explicitly create a Private constructor @NoArgsConstructor(access = AccessLevel.PRIVATE)

[ERROR] /home/runner/work/fineract/fineract/fineract-provider/src/main/java/org/apache/fineract/infrastructure/accountnumberformat/domain/AccountNumberFormatEnumerations.java:35:1: Utility classes should not have a public or default constructor.

Additionally, running spotlessCheck on my local mac didn't reveal this issue. 

Do you have any ideas on how I could resolve this? Or do you think I may be missing something here?
@adamsaghy

**Comment by galovics** [comment]
> Do you have any ideas on how I could resolve this? Or do you think I may be missing something here?

Don't use lombok for that. That's all.

**Pull request closed without merging**
