### PR TITLE
FINERACT-1460 update SZL and add SSP

### PR DESCRIPTION
**Pull request by francisguchie**
## Description

Describe the changes made and why they were made. 
[Read](https://issues.apache.org/jira/browse/FINERACT-1460)

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/2017).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by vidakovic** [comment]
@francisguchie ... can you run `./gradlew spotlessApply` and commit again? That should fix the error.

**Comment by francisguchie** [comment]
> @francisguchie ... can you run `./gradlew spotlessApply` and commit again? That should fix the error.
@vidakovic  thanks, i think i ran it on a different branch / project file. Then i forgot when i was done with this one. Doing it now

**Comment by francisguchie** [comment]
@awasum  here is the PR as requested

**Comment by ikimbra** [comment]
Thanks, @francisguchie for the update. I will test it and get back

**Comment by rrpawar96** [comment]
Hi @francisguchie, the commit in the PR is required as one, So need to squash it into one commit.

**Comment by francisguchie** [comment]
@rrpawar96  thanks for his advise let me squash the commits into 1

**Review by vidakovic — APPROVED** [review]
LGTM

**Pull request merged**
