### PR TITLE
FINERACT-1277-Message-Gateway-webhook

### PR DESCRIPTION
**Pull request by fynmanoj**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by avikganguly01 — APPROVED** [review]

**Review by avikganguly01 — APPROVED** [review]

**Comment by awasum** [comment]
@avikganguly01 , Will you like to assign this issue to @fynmanoj  and close the issue on JIRA: https://issues.apache.org/jira/browse/FINERACT-1277

That way we dont have open JIRA issues with merged PRs.

**Comment by awasum** [comment]
Also, I was wondering if any of you will like to write documentation around how to use this together with the front end. How is this used? Code alone without a doc on how end users can use this will not lead to mass adoption. cc @francisguchie , @bharathc27 and @edcable

**Comment by francisguchie** [comment]
@awasum, you are right about this. And even the [Issue on Jiira](https://issues.apache.org/jira/browse/FINERACT-1277) is not detailed for anyone to follow. I am still struggling with a number of issues in the Fineract simply because documentation is not provided. I will be great someone starts, and i can do functional testing (what i do best following documentation) and we can then improve the documents are we test and make conclusions

**Comment by avikganguly01** [comment]
@awasum @francisguchie : Updated the ticket with additional context on how message gateway is used. Message Gateway (https://github.com/openMF/message-gateway) readme and Fineract Webhook Confluence documentation has additional details on how to use it as well.

In FINCN JIRA, I am able to open, close and assign issues to others but I am not able to assign them to Manoj. In Fineract  JIRA, I am not able to assign issues to anyone (including me) and resolve issues which are not reported by me.

**Comment by awasum** [comment]
Sorry to hear that @avikganguly01 ... Please email me your JIRA and Confluence username for Apache Fineract JIRA...and I will  give you permission.. For @fynmanoj , We need to also add him to the right role as a contributor so we can fix this...I already did that for Fineract CN JIRA as I saw that you could not assign him to issues so he takes credit.. Let Manoj email me his Apache JIRA details too...

**Pull request merged**
