### PR TITLE
FINERACT-1991: Added search feature to antora generated documentation site 

### PR DESCRIPTION
**Pull request by jogathogo**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by jogathogo** [comment]
See screencast below for a preview of the feature 

https://github.com/apache/fineract/assets/8235531/b02a8bbc-208c-4126-9115-b8b892bb573e

**Comment by taskain7** [comment]
@jogathogo builds are failing with the following: Apache Rat audit failure - 421 unapproved licenses, please check and fix this.
Also, please squash the commits into only 1 commit.

**Comment by vidakovic** [comment]
Please don't merge this one before we've created release 1.9.0. Let's target 1.10.0. Jira tickets updated.

**Comment by jogathogo** [comment]
Bringing some side conversations back to this PR, see below

Hello James,

I managed to run RAT which identified the licenses it deems
incompatible. In my opinion, this is a false positive, here is the
license message. It allows for Redistribution and use in source and
binary forms, with or without modification.

Therefore I think we can go ahead. Let me know what you think.

Copyright (c) Felix Böhm
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

THIS IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by jogathogo** [comment]
If this is the only rat error, then yes

I think this is a BSD clause 2 and therefore a Category A license 

https://www.apache.org/legal/resolved.html#category-a

Github should tell you what license it is.  

Sent from Gmail Mobile

**Comment by jogathogo** [comment]
> Please don't merge this one before we've created release 1.9.0. Let's target 1.10.0. Jira tickets updated.

@vidakovic now that 1.9 is out, can we resume this? This PR is purely documentation related and does not contain any fineract code and therefore should be safe to merge without breaking anything.

**Comment by jdailey** [comment]
I would like to commit this.  
LGTM

**Pull request closed without merging**
