### PR TITLE
Add FineractClientTest for Fineract SDK REST Client (FINERACT-1216)

### PR DESCRIPTION
**Pull request by vorburger**
and introduce handy `Calls` utilitiy

see also discussion in FINERACT-1216

### CODE REVIEW

**Comment by vorburger** [comment]
@vidakovic @ptuomola @Grandolf49 is this cool, or what?! :ringed_planet:

**Comment by vidakovic** [comment]
You beat me on this one... 😉 had one implemented, but not pushed... slightly different approach... will comment... 
Good to see how it works this way!

**Review by ptuomola — APPROVED** [review]
That's great - looks really cool, and can't wait for us to be able to use this for Integration Test as well. I'm happy to merge this unless @vidakovic also wants to review?

**Review by vidakovic — APPROVED** [review]
LGTM. Note: I've removed my attempt to create a similar example/test; my code was quite a bit longer, this here looks better.

**Pull request merged**
