### PR TITLE
make SchedulerJobsTest preserve scheduler and job states (FINERACT-922)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-922

### CODE REVIEW

**Comment by vorburger** [comment]
Anyone willing to review this one? @nemux @awasum @xurror @ptuomola @trackcc LGTY?

**Comment by vorburger** [comment]
The current failure here is totally unrelated to this PR, and another "flaky" test, see FINERACT-828.

**Comment by vorburger** [comment]
It sounds like nobody seems to have any strong objections to this one, so I'd like to "self merge" it tomorrow.

**Comment by ptuomola** [comment]
The code itself looks good to me. I haven't hit this particular problem myself, so can't comment on whether it fixes the issue - but it does look like a sensible thing to do.

**Comment by awasum** [comment]
This looks clean..But i dont understand completely whats happening here. @vorburger Go ahead and self merge. You know what you are doing.

Minor update..seems there is a merge conflict?

**Comment by xurror** [comment]
I have little knowledge about this but I trust the changes are OK.

**Pull request merged**
