### PR TITLE
fix broken build due to small logging error detected by SpotBugs

### PR DESCRIPTION
**Pull request by vorburger**
significant reformatting due to Eclipse auto-save action (someone really
needs to finish the Checkstyle uniform formatting)

see https://github.com/apache/fineract/pull/592

### CODE REVIEW

**Comment by vorburger** [comment]
@awasum if you see it before I'm looking again next, could you merge this to as soon as build passed? Tx!

**Comment by thesmallstar** [comment]
> significant reformatting due to Eclipse auto-save action (someone really
> needs to finish the Checkstyle uniform formatting)

On it :P

**Comment by awasum** [comment]
> @awasum if you see it before I'm looking again next, could you merge this to as soon as build passed? Tx!

Travis fails.. @vorburger ... Anyone wants to fix this please?

**Comment by awasum** [comment]
We have a Flyway migration problem as a result of the merged on the Rates module..It seems..I have not looked deeply and might be wrong... #592 ...Seems we merged with a conflicting flyway migration problem...Sorry I cannot debug more. @thesmallstar , @xurror ...Please can you check this? Its breaking the build.

**Pull request closed without merging**
