### PR TITLE
Fineract-753 fix overdraft account balance

### PR DESCRIPTION
**Pull request by andrew-dzak**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vorburger** [comment]
The build may fail just because of [FINERACT-800](https://issues.apache.org/jira/browse/FINERACT-800). Will you rebase this when #657 has been merged?

**Comment by awasum** [comment]
@andrew-dzak Rebase this now as #657  has been merged. Thanks.

**Comment by awasum** [comment]
Seems, 8 integration Tests are failing. Would you like to look at that? @andrew-dzak

**Comment by andrew-dzak** [comment]
closed

**Review by andrew-dzak — COMMENTED** [review]
fix test cases

**Comment by andrew-dzak** [comment]
Hi,
    Issue fixed all integration tests are passing now

**Comment by vorburger** [comment]
==> #659

**Pull request closed without merging**
