### PR TITLE
FINERACT-821 Added NoLineWrap Checkstyle

### PR DESCRIPTION
**Pull request by thesmallstar**
Refer: https://issues.apache.org/jira/browse/FINERACT-821

### CODE REVIEW

**Review by vorburger — APPROVED** [review]
LGTM, but needs a rebase now?

**Comment by thesmallstar** [comment]
@vorburger  @xurror  merge this?

**Review by xurror — APPROVED** [review]
LGTM.

**Comment by xurror** [comment]
Great work.

**Pull request merged**
