### PR TITLE
client: GSON TypeAdapter<LocalDate> Fineract API Format [2009,1,1] (FINERACT-1220)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-1220

### CODE REVIEW

**Comment by vorburger** [comment]
@vidakovic this fixes FINERACT-1220. If this LGTY, go ahead and merge it.. then you could follow-up with a PR for FINERACT-1231 if you like (know how).

**Comment by vidakovic** [comment]
@vorburger maybe we should change that Checkstyle setting for asterisk imports? As you saw before I went with adding all imports... but that gets awfully long. Other than that looks good.

**Comment by vorburger** [comment]
> @vorburger maybe we should change that Checkstyle setting for asterisk imports? As you saw before I went with adding all imports... but that gets awfully long. Other than that looks good.

It's consistent, and we would have to change it everywhere. My IDE just changed it without me realizing - I've just changed the respective Setting that it doesn't happen again to me. Push coming up.

PS: The bigger problem is FINERACT-1226.. chime in there?

**Comment by vidakovic** [comment]
@vorburger Just added a comment on FINERACT-1226... I think that should work with no effort at all.

**Comment by vorburger** [comment]
@vidakovic will you review and merge this when you get a chance? (Build is green.)

**Comment by vorburger** [comment]
@vidakovic actually what we really should do is FIRST merge #1453 (when green), then rebase this - to make sure no broken build.

**Comment by vorburger** [comment]
@ptuomola @vidakovic build now passed, this is ready for review.

**Review by vidakovic — APPROVED** [review]
LGTM

**Pull request merged**
