### PR TITLE
make all Platform Exceptions always have a message [FINERACT-1062]

### PR DESCRIPTION
**Pull request by vorburger**
indirectly related to FINERACT-942, as per code review discussion in PR #1079.

see FINERACT-1062

### CODE REVIEW

**Comment by vorburger** [comment]
@thesmallstar @ptuomola would you like to code review this PR?

**Comment by ptuomola** [comment]
@vorburger Looks good to me - and nicely cleans up the code!

**Review by thesmallstar — APPROVED** [review]
LGTM!

**Pull request merged**
