### PR TITLE
Added Version Badge & Badge Logo

### PR DESCRIPTION
**Pull request by atharwa-24**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by vorburger — CHANGES_REQUESTED** [review]
Hello! Thanks for contributing. This proposes to add a "shield" for GitHub Releases, only, right? The thing is that this project doesn't release on GitHub, but to http://fineract.apache.org, so that "shield" probably won't actually work...

**Comment by atharwa-24** [comment]
Oh got it. Thanks

**Comment by vorburger** [comment]
Would you like to close this PR? Or perhaps add any other useful badges
instead?

>

**Comment by atharwa-24** [comment]
ok

**Pull request closed without merging**
