### PR TITLE
Use of Azul Zulu JDK 11 LTS (FINERACT-1416)

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

Use of Azul Zulu JDK 11 LTS (FINERACT-1416) in Dockerfile, Travis-CI file and a entrypoint was added to have a better control when starting Fineract for checking the DB service status (Fineract was booting before the DB Server using the docker-compose command).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [X] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [X] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by ptuomola** [comment]
Change looks good to me. Did you manage to work out how to squash commits? If yes, can you please squash the commits on this PR as well (so that there is only one commit). I can then merge this for you.

**Comment by IOhacker** [comment]
Hello,

When running 

$ git rebase -i HEAD~5

victor@cerberus:~/git/mifos/fineract$ git log
commit 784a82f5d60c9885863707fad1c31caab394cc53 (HEAD -> azul_zulu_jdk11)
Author: Victor Romero <victor.romero@fintecheando.mx>
Date:   Sat Oct 23 13:11:02 2021 -0500

    Use of Azul Zulu JDK 11 LTS (FINERACT-1416)

commit 4e672b3f583481c50c1a5e735db6470cc76fb0d3
Author: ankita10r <92036361+ankita10r@users.noreply.github.com>
Date:   Thu Oct 21 16:35:37 2021 +0530

    Fineract-1410 Allow Payment types to map to all types of Ledgers (#1917)

commit 2c9e5323abab2744e99f381f8565794c53b6207e
Author: Renovate <bot@renovateapp.com>
Date:   Thu Oct 21 07:58:43 2021 +0000

I got the interactive screen showing the following list:

 GNU nano 4.8 /home/victor/git/mifos/fineract/.git/rebase-merge/git-rebase-todo              
pick 81d816f11 Update build.gradle
pick e4b270c0f Feat: Node aware job scheduler (#1886)
pick dfd69f39e Upgrade JaCoco version to 0.8.7 for supporting JDK 17
pick 32fae2b12 FINERACT-1410 :Allow Payment types to map to all types of Ledgers (#1894)
pick 9ba63ef7f Support for SonarQube Analysis on ASF's SonarCloud (#1893)
pick 50367f36d Revert "FINERACT-1410 :Allow Payment types to map to all types of Ledgers (#18>
pick 2deabc7dc chore(deps): update dependency org.springframework:spring-framework-bom to v5.>
pick f520c2e62 chore(deps): update dependency org.ehcache:ehcache to v3.9.7
pick a4d5bc7a8 chore(deps): update dependency org.apache.tomcat:tomcat to v9.0.54
pick 3c7333986 chore(deps): update dependency io.swagger:swagger-core to v1.6.3
pick 98c4cd08d chore(deps): update dependency org.junit:junit-bom to v5.8.1
pick f6ec2a141 chore(deps): update dependency io.github.classgraph:classgraph to v4.8.128
pick 727767a50 chore(deps): update dependency com.puppycrawl.tools:checkstyle to v9.0.1
pick b4658533a chore(deps): update dependency com.github.spotbugs:spotbugs-annotations to v4.>
pick d1e3a86ae chore(deps): update dependency io.swagger.core.v3:swagger-annotations to v2.1.>
pick 29a5ebda4 chore(deps): update okhttpversion to v4.9.2
pick d039e141a chore(deps): update dependency org.webjars.npm:swagger-ui-dist to v3.52.5
pick ccee9458b chore(deps): update dependency io.swagger:swagger-annotations to v1.6.3
pick d0d338030 chore(deps): update dependency com.google.cloud.sql:mysql-socket-factory-conne>
pick 0ba4b2a79 chore(deps): update dependency com.github.spotbugs:spotbugs to v4.4.2
pick fe28ce921 chore(deps): update plugin io.swagger.core.v3.swagger-gradle-plugin to v2.1.11
pick c9304f006 chore(deps): update plugin org.barfuin.gradle.taskinfo to v1.3.1


And I am not sure if this will be the right/safe way to squash the commits (mabe there are more commits because they are merge)

**Comment by IOhacker** [comment]
Closing the PR because it is now a mess

**Comment by ptuomola** [comment]
> Hello,
> 
> When running
> 
> $ git rebase -i HEAD~5
> 
> victor@cerberus:~/git/mifos/fineract$ git log commit 784a82f5d60c9885863707fad1c31caab394cc53 (HEAD -> azul_zulu_jdk11) Author: Victor Romero [victor.romero@fintecheando.mx](mailto:victor.romero@fintecheando.mx) Date: Sat Oct 23 13:11:02 2021 -0500
> 
> ```
> Use of Azul Zulu JDK 11 LTS (FINERACT-1416)
> ```
> 
> commit 4e672b3f583481c50c1a5e735db6470cc76fb0d3 Author: ankita10r [92036361+ankita10r@users.noreply.github.com](mailto:92036361+ankita10r@users.noreply.github.com) Date: Thu Oct 21 16:35:37 2021 +0530
> 
> ```
> Fineract-1410 Allow Payment types to map to all types of Ledgers (#1917)
> ```
> 
> commit 2c9e5323abab2744e99f381f8565794c53b6207e Author: Renovate [bot@renovateapp.com](mailto:bot@renovateapp.com) Date: Thu Oct 21 07:58:43 2021 +0000
> 
> I got the interactive screen showing the following list:
> 
> GNU nano 4.8 /home/victor/git/mifos/fineract/.git/rebase-merge/git-rebase-todo pick [81d816f](https://github.com/apache/fineract/commit/81d816f116ddc698c18be2cdce88d3a27f3d824a) Update build.gradle pick [e4b270c](https://github.com/apache/fineract/commit/e4b270c0f5be571d7268a87a2cd612acd4ef84d8) Feat: Node aware job scheduler (#1886) pick [dfd69f3](https://github.com/apache/fineract/commit/dfd69f39e96363d7c17a16491b94397a0579036a) Upgrade JaCoco version to 0.8.7 for supporting JDK 17 pick [32fae2b](https://github.com/apache/fineract/commit/32fae2b1274e494c9b53ceefbbc997931c685b7e) [FINERACT-1410](https://issues.apache.org/jira/browse/FINERACT-1410) :Allow Payment types to map to all types of Ledgers (#1894) pick [9ba63ef](https://github.com/apache/fineract/commit/9ba63ef7f7bc7a796587cc337fdfd3f9b8ecb611) Support for SonarQube Analysis on ASF's SonarCloud (#1893) pick [50367f3](https://github.com/apache/fineract/commit/50367f36d8037f203e5e8db002ce0291af0e600d) Revert "[FINERACT-1410](https://issues.apache.org/jira/browse/FINERACT-1410) :Allow Payment types to map to all types of Ledgers (#18> pick [2deabc7](https://github.com/apache/fineract/commit/2deabc7dccb55e45ba75d2294539f80963a1c27f) chore(deps): update dependency org.springframework:spring-framework-bom to v5.> pick [f520c2e](https://github.com/apache/fineract/commit/f520c2e62cc7a5274d5f459b3f67e220145e520f) chore(deps): update dependency org.ehcache:ehcache to v3.9.7 pick [a4d5bc7](https://github.com/apache/fineract/commit/a4d5bc7a8e129cae4089055838034b7c459407db) chore(deps): update dependency org.apache.tomcat:tomcat to v9.0.54 pick [3c73339](https://github.com/apache/fineract/commit/3c7333986f6e73a506eafa820a87c3b1fa70004c) chore(deps): update dependency io.swagger:swagger-core to v1.6.3 pick [98c4cd0](https://github.com/apache/fineract/commit/98c4cd08d40e3956503292c71b9a2b3b9971f0a0) chore(deps): update dependency org.junit:junit-bom to v5.8.1 pick [f6ec2a1](https://github.com/apache/fineract/commit/f6ec2a14110dba2d3e34bbeb744ce0a7764784e0) chore(deps): update dependency io.github.classgraph:classgraph to v4.8.128 pick [727767a](https://github.com/apache/fineract/commit/727767a50336e3f066fd10b80ab1afc6439d323a) chore(deps): update dependency com.puppycrawl.tools:checkstyle to v9.0.1 pick [b465853](https://github.com/apache/fineract/commit/b4658533ad83498bd4ad87e8775398fc0d40d542) chore(deps): update dependency com.github.spotbugs:spotbugs-annotations to v4.> pick [d1e3a86](https://github.com/apache/fineract/commit/d1e3a86aef1e068463b3b6f6aa2908339ada6995) chore(deps): update dependency io.swagger.core.v3:swagger-annotations to v2.1.> pick [29a5ebd](https://github.com/apache/fineract/commit/29a5ebda48113d54bd432d26c94f7b82bc9adf88) chore(deps): update okhttpversion to v4.9.2 pick [d039e14](https://github.com/apache/fineract/commit/d039e141a3c0b983940599e96b3ecb0c113f7070) chore(deps): update dependency org.webjars.npm:swagger-ui-dist to v3.52.5 pick [ccee945](https://github.com/apache/fineract/commit/ccee9458b5cd1f4dc71fb81e9c85be93f745e430) chore(deps): update dependency io.swagger:swagger-annotations to v1.6.3 pick [d0d3380](https://github.com/apache/fineract/commit/d0d338030c415011e032ee51b544b58140153d87) chore(deps): update dependency com.google.cloud.sql:mysql-socket-factory-conne> pick [0ba4b2a](https://github.com/apache/fineract/commit/0ba4b2a79410c36cf8989b7a64f1be89d06f9379) chore(deps): update dependency com.github.spotbugs:spotbugs to v4.4.2 pick [fe28ce9](https://github.com/apache/fineract/commit/fe28ce9214252ff722e042b0a42268e74f474c41) chore(deps): update plugin io.swagger.core.v3.swagger-gradle-plugin to v2.1.11 pick [c9304f0](https://github.com/apache/fineract/commit/c9304f0063021150cbe7d82ea9cdf70e94703505) chore(deps): update plugin org.barfuin.gradle.taskinfo to v1.3.1
> 
> And I am not sure if this will be the right/safe way to squash the commits (mabe there are more commits because they are merge)

Yes that doesn't look right. Was your PR up to date wrt develop? Ie did you fetch all the changes from upstream to your develop branch and rebase your PR branch on your develop branch?

The squashing works if you have all of your own changes one after another in git log:

My commit 3
My commit 2 
My commit 1 
Master commit x
Master commit x-1
etc

**Pull request closed without merging**
