### PR TITLE
Glim gsim rebased

### PR DESCRIPTION
**Pull request by rrpawar96**
This is the latest rebased pull request for glim_gsim requirement.

https://github.com/apache/fineract/pull/504.

### CODE REVIEW

**Comment by vishwasbabu** [comment]
@rrpawar96 : Great job on taking up such a significant piece of functionality 👍 

While this pr probably works fine as of now, the absence of any integration tests for the functionality introduced would make it unmaintainable from a community perspective (especially given that going forward, we will likely not be having much/any manual QA before shipping releases).

**Comment by rrpawar96** [comment]
@vishwasbabu,  I will write test cases and notify community once done.

**Comment by vishwasbabu** [comment]
Thanks @rrpawar96 👍 . I will close this pr for now

**Comment by edcable** [comment]
@rrpawar96 I wanted to follow up on the writing of test cases and whether or not you'd be able to open up another PR soon. I think we'd target this for the 1.5 release.

**Comment by rrpawar96** [comment]
yes @edcable, I am planning to finish writing the testcases in December.

**Pull request closed without merging**
