### PR TITLE
FINERACT-659 Account Id issue while importing loan transaction

### PR DESCRIPTION
**Pull request by ShruthiRajaram**

### CODE REVIEW

**Comment by MexinaD** [comment]
Hello @ShruthiRajaram 
It seems you have handled during uploading the system to allow the Account id with Long datatype so as to accommodate the big number.

But i have see other case where if the loan accounts have account preferences the system don't allow to download since they are in a format like "MFL000000021"  which is not a number.

I think its better to handle these issues together.

**Comment by ShruthiRajaram** [comment]
@MexinaD thanks for the input. I will try to include that modification as well

**Comment by ShruthiRajaram** [comment]
Hi @MexinaD I have made changes that fixes both download and upload of bulk loan repayment transaction (with/without account number preferences enabled) . Kindly review.

**Comment by MexinaD** [comment]
Hello @ShruthiRajaram
I tested and it worked fine.

**Comment by ShruthiRajaram** [comment]
@MexinaD Can you review and provide feedback/approve the PR?

**Comment by MexinaD** [comment]
Reviewed and can be merged

**Pull request merged**
