### PR TITLE
Fineract-1043 Removed street field from address

### PR DESCRIPTION
**Pull request by nikpawar89**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by maektwain** [comment]
Should we get this merged....? @vorburger

**Comment by vorburger** [comment]
@nikpawar89 in an ideal world, an Integration Test (IT) for this entire client address business would be great.. enabling _global configuration value of "Enable-Address"_.

Would you be willing to contribute an IT for FINERACT-1043 in (a) this PR,  (b) a follow-up PR if we merge this ASAP,  (c) not really, no time? Just asking! :smile:

**Comment by nikpawar89** [comment]
@vorburger I will do it myself or collaborate with GSOC intern @rrpawar96 .
But can't promise timeline.

@rrpawar96 can you add this in TODO list of our project.

**Review by vorburger — APPROVED** [review]
@nikpawar89 @rrpawar96 perhaps a fixed bug (FINERACT-1043) without an IT is better than a not fixed bug... :smile_cat: 

I'll already merge this (as soon as we have fixed a currently failing IT, see FINERACT-1016), and you can send a new PR for an IT.

BTW https://github.com/apache/fineract/pull/1100/files from @thesmallstar could interest you to see how to write an IT?

**Pull request merged**
