### PR TITLE
rewrite MultiException to actually contain all causes (FINERACT-858)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-858, useful for debugging FINERACT-922

### CODE REVIEW

**Comment by vorburger** [comment]
@ptuomola how do you like this?

**Comment by vorburger** [comment]
> @ptuomola how do you like this?

@ptuomola and now this actually even builds green :smiley_cat: 

@maektwain @awasum @xurror anyone else review this - LGTY?

**Comment by vorburger** [comment]
It sounds like nobody seems to have any strong objections to this one, so I'd like to "self merge" it tomorrow.

**Comment by ptuomola** [comment]
Looks good to me - much cleaner than the previous code

**Pull request merged**
