### PR TITLE
Use of Azul Zulu JDK 11 LTS (FINERACT-1416)

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

Use of Azul Zulu JDK 11 LTS (FINERACT-1416) in Dockerfile, Travis-CI file and a entrypoint was added to have a better control when starting Fineract for checking the DB service status (Fineract was booting before the DB Server using the docker-compose command).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [X] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [X] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by IOhacker** [comment]
Closing without changes

**Comment by IOhacker** [comment]
Opening without changes

**Comment by IOhacker** [comment]
Closing without changes

**Comment by IOhacker** [comment]
Opening without changes

**Comment by IOhacker** [comment]
@ptuomola @awasum now it passed the tests and 1 commit.

**Comment by ptuomola** [comment]
LGTM - great work!

**Comment by awasum** [comment]
JIRA issue https://issues.apache.org/jira/browse/FINERACT-1416 closed as this has been merged. Thanks Everyone.

**Comment by vorburger** [comment]
This caused FINERACT-1454.

**Pull request merged**
