### PR TITLE
remove logback.xml [FINERACT-888]

### PR DESCRIPTION
**Pull request by vorburger**
Read e.g. https://12factor.net/logs for why we don't want to log
to a fineract-platform.log file anymore by default.  Of course, anyone
could still customize logging as they see fit for their own deployments.

see FINERACT-888

### CODE REVIEW

**Comment by vorburger** [comment]
@ptuomola @awasum @xurror what is your view on going this way?

**Comment by xurror** [comment]
Build is failing

**Comment by vorburger** [comment]
> Build is failing

==> FINERACT-828 but it's unrelated to this change, can still review

**Comment by vorburger** [comment]
#918 raised to ignore failing test

**Review by xurror — APPROVED** [review]
LGTM

**Pull request merged**
