### PR TITLE
FINERACT-632 Make description field non mandatory in saving product

### PR DESCRIPTION
**Pull request by m-sameer**
Make description field non-mandatory in saving product.

### CODE REVIEW

**Comment by santoshconflux** [comment]
@avikganguly01 , Could you review this if time permits?

**Comment by edcable** [comment]
I have Rahul and Sanyam trying to review as well.

**Review by ShruthiRajaram — COMMENTED** [review]
the description field of the savings product table doesn't accept null values. So I believe it will throw exception. Can you test the change that you have made and confirm.

**Comment by m-sameer** [comment]
@ShruthiRajaram Sorry for the late reply. If I remove the description field the request is completed successfully and I'm also able to retrieve the product.

I'm unable to find the class where the saving product table is created. Can you please help me with that?

- Creating a product without description:
screenshot from 2018-11-30 13-19-25

- Retrieving the created product:
screenshot from 2018-11-30 13-22-28

**Comment by m-sameer** [comment]
I have found 3 instances where a table called `m_savings_product` is being created with the **description** column marked with `NOT NULL` constraint. The instances reside in the following files:
- fineract/fineract-provider/src/main/resources/sql/migrations/core_db/V1__mifosplatform-core-ddl-latest.sql
- fineract/fineract-provider/src/main/resources/sql/migrations/sample_data/barebones_db.sql
- fineract/fineract-provider/src/main/resources/sql/migrations/sample_data/load_sample_data.sql

**Comment by ShruthiRajaram** [comment]
@m-sameer the solution proposed by you is working because by default an empty string is getting assigned to description field in SavingsProductAssembler. So this is not the right way to fix the issue. I would say a migration script should be written to alter the m_savings_product and make description field to accept the null value. Then in the SavingsProduct class make appropriate change. And on top of all these, change proposed by you should be applied.

**Comment by m-sameer** [comment]
@ShruthiRajaram If writing the migration script is part of this PR, can you please guide me how to write it? :)

**Comment by ShruthiRajaram** [comment]
@m-sameer goto location fineract-provider\src\main\resources\sql\migrations\core_db in your system.  choose the next number available. Follow the naming convention and name your file containing the script to alter the savings product table. On the next server start this script will execute and will alter the table. If the script didn't execute  check the file name or if the table is not modified check the query.

**Comment by m-sameer** [comment]
@ShruthiRajaram I have updated the PR. I have tested the changes on RESTClient, now there is no description field with an empty string in the case when no description is provided on product creation. Please review.

Thank you once again!

**Comment by ShruthiRajaram** [comment]
@m-sameer changes look good. But someone has already raised a PR with V344. So can you use V346 as your migration script number and resend the PR. I will merge.

**Comment by m-sameer** [comment]
@ShruthiRajaram The next version will be V345 instead of V346, which one should I use?

**Comment by ShruthiRajaram** [comment]
V345 is already merged. Use V346

**Comment by m-sameer** [comment]
@ShruthiRajaram Done!

**Comment by ShruthiRajaram** [comment]
@m-sameer use '-' (underscore) instead of '-' in the migration script name. I should have told this before, Sorry for that. We faced issue when we tried to modify the file containing hyphen before.

**Comment by m-sameer** [comment]
@ShruthiRajaram No problem. I have made the changes.

**Comment by m-sameer** [comment]
@ShruthiRajaram Any updates?

**Review by ShruthiRajaram — APPROVED** [review]

**Comment by ShruthiRajaram** [comment]
@m-sameer good job :)

**Comment by m-sameer** [comment]
@ShruthiRajaram Thanks! :smiley:

**Pull request merged**
