### PR TITLE
FINERACT-613:500 Internal Server Errors on Data Tables

### PR DESCRIPTION
**Pull request by lingalamadhukar**

### CODE REVIEW

**Comment by wkk91193** [comment]
@lingalamadhukar  when this was merged to develop, pentaho reports keep failing with the following [stacktrace](https://pastebin.com/2ku8GEe7) could you please look into this

**Comment by ippezshelby** [comment]
@wkk91193 , i faced the same but it seems it was because of maria-db driver. Make sure you are using mysql server. Please check this https://gist.github.com/odan/c799417460470c3776ffa8adce57eece

Confirm this by running `mysql -uroot -pmysql` from command line and please paste your result

**Comment by wkk91193** [comment]
@Ippezrobert  yes, I'm using the MySQL server

**Comment by lingalamadhukar** [comment]
@wkk91193 this pull request is still open and not merged into develop branch.
Correct me if am wrong, I think we cannot run or execute Pentaho reports in apache/fineract code base, you need to use openMF/incubator-fineract repository code to execute Pentaho reports.

**Comment by wkk91193** [comment]
@lingalamadhukar  where can I get the latest source code for Mifosx 18.03.01?

**Comment by lingalamadhukar** [comment]
@wkk91193 you can find the same under releases, https://github.com/openMF/incubator-fineract/releases

**Comment by edcable** [comment]
@avikganguly01 @conradsp @nazeer1100126 @nikpawar Can we get this merged in so we can ship the point release that contains this hot fix?

**Comment by conradsp** [comment]
I have merged this PR.

**Comment by conradsp** [comment]
I have merged this PR.
Thanks,
Steve

**Comment by dawoodjee** [comment]
Ok guys. Kindly guide on how I update my fineractplatform-18.03.01.RELEASE from this point?

**Comment by abangsihar** [comment]
Hi,
I still face this issue. When load the datatable still got the error 500.

Thanks.

**Comment by eadjeidjan** [comment]
> mysql -uroot -pmysql
 can you share the war file you used too?
C:\tomcat\bin>mysql -uroot -pmysql
Warning: Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 39
Server version: 5.6.46-log MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

**Comment by kamlesh-bafna** [comment]
i am using the fineract-provider 1.4 and still seem to be getting this error when querying any data tables. Any idea how to debug further.

**Pull request merged**
