### PR TITLE
Add client IDs for selfservice user in auth credentials (FINERACT-1340)

### PR DESCRIPTION
**Pull request by josemakara2**
## Description

Details in Apache Fineract JIRA ticket FINERACT-1340

Client IDs to be returned ONLY for self service calls. `https://localhost:8443/fineract-provider/api/v1/self/authentication`

Below one won't return client IDs in JSON and will continue working as it has been
`https://localhost:8443/fineract-provider/api/v1/authentication`
```
curl \
  --header "Content-Type: application/json" \
  --header "Authorization: Basic bWlmb3M6cGFzc3dvcmQ=" \
  --header "Fineract-Platform-TenantId: default" \
  --request POST \
  --data  '{"username":"mifos", "password":"password"}' \
  https://localhost:8443/fineract-provider/api/v1/authentication --insecure
```

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by josemakara2** [comment]
@ptuomola 
If you could please have a look at this, FINERACT-1340, when you have a moment ?
Many thanks.

**Comment by ptuomola** [comment]
Hi

The comment says "Below one won't return client IDs in JSON and will continue working as it has been
https://localhost:8443/fineract-provider/api/v1/authentication"

But after this change, it would seem that the client IDs are if the attribute user.isSelfServiceUser() is set. 

Given that this is read from the database (m_app_user.is_self_service_user), doesn't this mean that if someone calls /v1/authentication for a user for whom  m_app_user.is_self_service_user=1, the /v1/authentication will also return the clients? Which was not the intention.

My suggestion would be instead to pass a boolean flag (i.e. returnClientList) to call of authenticate() from SelfAuthenticationApiResource and use that to determine whether clients should be included in the response.

**Comment by josemakara2** [comment]
> My suggestion would be instead to pass a boolean flag (i.e. returnClientList) to call of authenticate() from SelfAuthenticationApiResource and use that to determine whether clients should be included in the response.

Thanks. I have added commit a94f353ba1a81c10a14b271bad27d328722b11c8

**Review by ptuomola — APPROVED** [review]
LGTM

**Pull request merged**
