### PR TITLE
FINERACT-1141: Backport FINERACT-1135 to 1.4.0 Error at Loan Repaymen…

### PR DESCRIPTION
**Pull request by vidakovic**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vidakovic** [comment]
@francisguchie please have a look at this when you have a moment

**Comment by vidakovic** [comment]
@francisguchie @vorburger @ptuomola could one of you please verify this PR if you have a moment and merge it if it's ok? Thanks.

**Comment by francisguchie** [comment]
> @francisguchie @vorburger @ptuomola could one of you please verify this PR if you have a moment and merge it if it's ok? Thanks.

@vidakovic , i have looked at the changes made and they are ok to me. 
and i do agree to to the merge as i recall there were users of 1.4 that complained about the SQL Group By error. (https://github.com/apache/fineract/pull/1166)
This PR addresses the sql error and caters for 1.4 users who use mySQL 5.7 that demands full GROUP BY SQL statements

**Comment by vidakovic** [comment]
@francisguchie thanks a ton for taking the time... @ptuomola @vorburger can one of you take over the merge please as per new rules for PR merges? Thanks again.

**Pull request merged**
