### PR TITLE
FINERACT-241

### PR DESCRIPTION
**Pull request by maektwain**
@Ippezrobert please confirm with this PR

### CODE REVIEW

**Comment by nazeer1100126** [comment]
Changes are OK. But it is having two commits.

**Comment by ippezshelby** [comment]
@nazeer1100126 , how about validation in SavingsAccountTransactionDataValidator class? Not necessary?

**Comment by nazeer1100126** [comment]
@Ippezrobert can you give some more details? What validations should we do in SavingsAccountTransactionDataValidator ?

**Comment by ippezshelby** [comment]
_final String note = this.fromApiJsonHelper.extractStringNamed(noteParamName, element);
        baseDataValidator.reset().parameter(noteParamName).value(note).notExceedingLengthOf(1000);_

Because i tried the above PR locally here but doesn't work still throws error below from Web App

_field is required
The parameter `note` has been passed and is not supported for this request._ 

OR
Could it be that some changes need to be done at the community-app too?

**Comment by nazeer1100126** [comment]
ah got it. He didn't add noteParamName in supported parameter list

**Comment by ippezshelby** [comment]
@nazeer1100126 , I added the above validation as in this commit https://github.com/Ippezrobert/incubator-fineract/commit/e329b5d9fad3325217ff1c4e556250ae592d19eb but still community-app throws the error 

_> field is required
> The parameter note has been passed and is not supported for this request._

Could you please try this at your side maybe you will see where the error is.
Thanks

**Comment by nazeer1100126** [comment]
@Ippezrobert You need to add that note parameter to SavingsApiConstants.SAVINGS_ACCOUNT_TRANSACTION_REQUEST_DATA_PARAMETERS

**Comment by ippezshelby** [comment]
@nazeer1100126, I got it working now. Thank you for guiding me
You can close this PR as i send a new working PR with all the necessary changes

**Pull request closed without merging**
