### PR TITLE
FINERACT-724: upgrade Spring boot to 2.1.7 

### PR DESCRIPTION
**Pull request by awasum**
## Description
FINERACT-724: upgrade Spring boot to 2.1.7. Intial PR (contributed by  @ivan333m) and reviews (by @vorburger ) here: https://github.com/apache/fineract/pull/642

This just makes sure the commit history is consistent as specified here: https://github.com/apache/fineract/pull/642#pullrequestreview-321923274 and 
https://github.com/apache/fineract/pull/642#issuecomment-557822708

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by awasum** [comment]
@vorburger , i think this fixes the problem identified in the initial PR.  @ivan333m, you authorship is still captured here. I hope this solves the weird commit history problem in https://github.com/apache/fineract/pull/642

**Comment by awasum** [comment]
Over the pass few days, I have notice travis fail with a:  `The job exceeded the maximum log length, and has been terminated.` exception. Meaning, we are exhausting our 4M limit for log file.

How do we deal with this?

I think if we replace running the license tasks and just use a single ./gradlew clean build or maybe just omit it altogether, we might fix this problem. It seems like the test and integration tests tasks will run license check before moving forward. I will try to do this soon and see if we can have travis passing again.

**Comment by awasum** [comment]
> Over the pass few days, I have notice travis fail with a: `The job exceeded the maximum log length, and has been terminated.` exception. Meaning, we are exhausting our 4M limit for log file.
> 
> How do we deal with this?
> 
> I think if we replace running the license tasks and just use a single ./gradlew clean build or maybe just omit it altogether, we might fix this problem. It seems like the test and integration tests tasks will run license check before moving forward. I will try to do this soon and see if we can have travis passing again.

I think the bulk of console logs are coming from the integrationTest. How do we reduce them. Also related, See: https://github.com/apache/fineract/pull/653#issuecomment-557868214 and here: https://github.com/travis-ci/docs-travis-ci-com/issues/281

**Comment by ivbond** [comment]
I have downloaded logs from two builds (with and without upgrade changes).
Spring Boot :: (v1.2.8.RELEASE) https://api.travis-ci.org/v3/job/599081380/log.txt 
Spring Boot :: (v2.1.9.RELEASE) https://api.travis-ci.org/v3/job/616120017/log.txt

I used following `grep` command for the analysis:
`grep -o -E "(DEBUG|INFO|WARN|TRACE) ........\S*" ./log_old.txt | sort | uniq -c | sort -n`

I had following results:
With upgrade:
```
     ...
     34 INFO  o.s.s.quartz.SchedulerFactoryBean
     81 DEBUG o.a.f.p.a.s.AccountAssociationsReadPlatformServiceImpl
    102 INFO  org.quartz.impl.StdSchedulerFactory
    238 INFO  org.quartz.core.QuartzScheduler
    350 INFO  o.a.f.c.p.CommandHandlerProvider
    374 INFO  c.g.flyway.core.command.DbMigrate
    630 INFO   [Daemon
   1260 INFO   [Execution
   4781 INFO  o.s.b.a.audit.listener.AuditListener
   5111 INFO  o.a.f.i.s.f.TenantAwareBasicAuthenticationFilter
```
Without upgrade:
```
     ...
     37 INFO  o.s.s.quartz.SchedulerFactoryBean
     81 DEBUG o.a.f.p.a.s.AccountAssociationsReadPlatformServiceImpl
    105 INFO  org.quartz.impl.StdSchedulerFactory
    250 INFO  org.quartz.core.QuartzScheduler
    350 INFO  o.a.f.c.p.CommandHandlerProvider
    375 INFO  c.g.flyway.core.command.DbMigrate
   1260 INFO   [Daemon
   1260 INFO   [Execution
   4755 DEBUG o.s.b.a.audit.listener.AuditListener
   5085 INFO  o.a.f.i.s.f.TenantAwareBasicAuthenticationFilter 
```

At the same time I did not found large diff messages with Exceptions:
> grep -E -o "Exception..................\S* " ./log_old.txt | sort | uniq -c | sort -n
```
      1 Exception, class org.apache.fineract.infrastructure.campaigns.sms.domain.SmsCampaignStatusEnumerations, 
      1 Exception, class org.apache.fineract.portfolio.savings.domain.SavingsEvent, 
      1 Exception, class org.apache.fineract.useradministration.domain.AppUserRepositoryWrapper, 
      1 ExceptionIfPossible(EntityManagerFactoryUtils.java:407) 
      1 ExceptionTranslationFilter]; 
      1 ExceptionTranslationFilter@1b7baa1, 
      2 Exception: Account not found 
      3 ExceptionIfPossible(EntityManagerFactoryUtils.java:415) 
      4 Exception(BrokerImpl.java:2363) 
      4 Exception(BrokerImpl.java:2374) 
      4 Exception(DBDictionary.java:4963) 
      4 Exception: Duplicate entry '50-MSISDN' 
      4 ExceptionIfPossible(EntityManagerFactoryUtils.java:404) 
      4 Exceptions.getStore(SQLExceptions.java:133) 
      4 Exceptions.getStore(SQLExceptions.java:75) 
      7 ExceptionIfPossible(AbstractEntityManagerFactoryBean.java:417) 
      7 ExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) 
      7 ExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147) 
      7 ExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59) 
      8 Exception: An optimistic lock 
      8 ExceptionIfPossible(DefaultJpaDialect.java:122) 
      9 Exception could not be mapped 
      9 ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) 
     12 Exception: Deadlock found when 
     28 Exception: Optimistic locking 
     28 Exception: The transaction has 
```
> grep -E -o "Exception..................\S* " ./log_new.txt | sort | uniq -c | sort -n
```
      1 Exception, class org.apache.fineract.infrastructure.campaigns.email.domain.EmailMessageAssembler, 
      1 Exception, class org.apache.fineract.portfolio.calendar.domain.CalendarRemindBy, 
      1 Exception, class org.apache.fineract.portfolio.client.domain.ClientTransactionRepositoryWrapper, 
      1 Exception, class org.apache.fineract.portfolio.note.domain.NoteType, 
      1 ExceptionTranslationFilter]; 
      1 ExceptionTranslationFilter@25e03459, 
      4 Exception: Duplicate entry '50-MSISDN' 
      8 Exception: An optimistic lock 
     10 Exception could not be mapped 
     16 Exception: Deadlock found when 
     28 Exception: Optimistic locking 
     35 Exception: The transaction has 
```

So as we can see there is no dramatic changes in the numbers.
Log before upgrade is about 4.2 MB, it is very close to the limit (As I understand limit is about 4 - 4.5 MB).
I would propose to increase limit to 5 MB.

**Comment by awasum** [comment]
> I have downloaded logs from two builds (with and without upgrade changes).
> Spring Boot :: (v1.2.8.RELEASE) https://api.travis-ci.org/v3/job/599081380/log.txt
> Spring Boot :: (v2.1.9.RELEASE) https://api.travis-ci.org/v3/job/616120017/log.txt
> 
> I used following `grep` command for the analysis:
> `grep -o -E "(DEBUG|INFO|WARN|TRACE) ........\S*" ./log_old.txt | sort | uniq -c | sort -n`
> 
> I had following results:
> With upgrade:
> 
> ```
>      ...
>      34 INFO  o.s.s.quartz.SchedulerFactoryBean
>      81 DEBUG o.a.f.p.a.s.AccountAssociationsReadPlatformServiceImpl
>     102 INFO  org.quartz.impl.StdSchedulerFactory
>     238 INFO  org.quartz.core.QuartzScheduler
>     350 INFO  o.a.f.c.p.CommandHandlerProvider
>     374 INFO  c.g.flyway.core.command.DbMigrate
>     630 INFO   [Daemon
>    1260 INFO   [Execution
>    4781 INFO  o.s.b.a.audit.listener.AuditListener
>    5111 INFO  o.a.f.i.s.f.TenantAwareBasicAuthenticationFilter
> ```
> 
> Without upgrade:
> 
> ```
>      ...
>      37 INFO  o.s.s.quartz.SchedulerFactoryBean
>      81 DEBUG o.a.f.p.a.s.AccountAssociationsReadPlatformServiceImpl
>     105 INFO  org.quartz.impl.StdSchedulerFactory
>     250 INFO  org.quartz.core.QuartzScheduler
>     350 INFO  o.a.f.c.p.CommandHandlerProvider
>     375 INFO  c.g.flyway.core.command.DbMigrate
>    1260 INFO   [Daemon
>    1260 INFO   [Execution
>    4755 DEBUG o.s.b.a.audit.listener.AuditListener
>    5085 INFO  o.a.f.i.s.f.TenantAwareBasicAuthenticationFilter 
> ```
> 
> At the same time I did not found large diff messages with Exceptions:
> 
> > grep -E -o "Exception..................\S* " ./log_old.txt | sort | uniq -c | sort -n
> 
> ```
>       1 Exception, class org.apache.fineract.infrastructure.campaigns.sms.domain.SmsCampaignStatusEnumerations, 
>       1 Exception, class org.apache.fineract.portfolio.savings.domain.SavingsEvent, 
>       1 Exception, class org.apache.fineract.useradministration.domain.AppUserRepositoryWrapper, 
>       1 ExceptionIfPossible(EntityManagerFactoryUtils.java:407) 
>       1 ExceptionTranslationFilter]; 
>       1 ExceptionTranslationFilter@1b7baa1, 
>       2 Exception: Account not found 
>       3 ExceptionIfPossible(EntityManagerFactoryUtils.java:415) 
>       4 Exception(BrokerImpl.java:2363) 
>       4 Exception(BrokerImpl.java:2374) 
>       4 Exception(DBDictionary.java:4963) 
>       4 Exception: Duplicate entry '50-MSISDN' 
>       4 ExceptionIfPossible(EntityManagerFactoryUtils.java:404) 
>       4 Exceptions.getStore(SQLExceptions.java:133) 
>       4 Exceptions.getStore(SQLExceptions.java:75) 
>       7 ExceptionIfPossible(AbstractEntityManagerFactoryBean.java:417) 
>       7 ExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) 
>       7 ExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147) 
>       7 ExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59) 
>       8 Exception: An optimistic lock 
>       8 ExceptionIfPossible(DefaultJpaDialect.java:122) 
>       9 Exception could not be mapped 
>       9 ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) 
>      12 Exception: Deadlock found when 
>      28 Exception: Optimistic locking 
>      28 Exception: The transaction has 
> ```
> 
> > grep -E -o "Exception..................\S* " ./log_new.txt | sort | uniq -c | sort -n
> 
> ```
>       1 Exception, class org.apache.fineract.infrastructure.campaigns.email.domain.EmailMessageAssembler, 
>       1 Exception, class org.apache.fineract.portfolio.calendar.domain.CalendarRemindBy, 
>       1 Exception, class org.apache.fineract.portfolio.client.domain.ClientTransactionRepositoryWrapper, 
>       1 Exception, class org.apache.fineract.portfolio.note.domain.NoteType, 
>       1 ExceptionTranslationFilter]; 
>       1 ExceptionTranslationFilter@25e03459, 
>       4 Exception: Duplicate entry '50-MSISDN' 
>       8 Exception: An optimistic lock 
>      10 Exception could not be mapped 
>      16 Exception: Deadlock found when 
>      28 Exception: Optimistic locking 
>      35 Exception: The transaction has 
> ```
> 
> So as we can see there is no dramatic changes in the numbers.
> Log before upgrade is about 4.2 MB, it is very close to the limit (As I understand limit is about 4 - 4.5 MB).
> I would propose to increase limit to 5 MB.

Is there a way to increase log size on Travis free version? I have not been able to find it. 

Also there is the typical 50 minutes timeout for Travis free version. If our build runs for more than 50 minutes..then everything fails as Travis will run into a timeout. See here: https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts

**Comment by ivbond** [comment]
There are 4755 messages in the log from `org.springframework.boot.actuate.audit.listener.AuditListener`.
Example:

> 05:13:16.686 [SimpleAsyncTaskExecutor-41580] DEBUG o.s.b.a.audit.listener.AuditListener - AuditEvent [timestamp=2019-11-23T23:43:16.686Z, principal=mifos, type=AUTHENTICATION_SUCCESS, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null}]

They are not so useful (by my opinion).
 We can switch log level to INFO for this class in travis build by following command: 

`.... licenseTest licenseIntegrationTest test  &&  ./gradlew -Dlogging.level.org.springframework.boot.actuate.audit.listener.AuditListener=INFO --console=plain  integrationTest`

As result the log file will be 1.5 MB smaller.

**Comment by vorburger** [comment]
@awasum thanks for having done this (PR with more consistent commit history). I will now (finally, sorry it took SO LONG!) merge this as is now; let's deal with the log issue separately, as it really doesn't have anything to do with this upgrade. @ivan333m thank you very very much for your contribution (and patience with us). We would very much love to see many more contributions coming from you!

**Comment by awasum** [comment]
> There are 4755 messages in the log from `org.springframework.boot.actuate.audit.listener.AuditListener`.
> Example:
> 
> > 05:13:16.686 [SimpleAsyncTaskExecutor-41580] DEBUG o.s.b.a.audit.listener.AuditListener - AuditEvent [timestamp=2019-11-23T23:43:16.686Z, principal=mifos, type=AUTHENTICATION_SUCCESS, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null}]
> 
> They are not so useful (by my opinion).
> We can switch log level to INFO for this class in travis build by following command:
> 
> `.... licenseTest licenseIntegrationTest test && ./gradlew -Dlogging.level.org.springframework.boot.actuate.audit.listener.AuditListener=INFO --console=plain integrationTest`
> 
> As result the log file will be 1.5 MB smaller.

Please, @ivan333m , You can send this as a PR. It will help alot moving forwards. Thanks again for your contributions.

**Comment by vorburger** [comment]
PS: Re. the excessive logging issue on Travis, see #657 for [FINERACT-800](https://issues.apache.org/jira/browse/FINERACT-800).

**Pull request merged**
