### PR TITLE
Updated Java to Azul Zulu jdk17

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

Dockerfile was Updated Java to Azul Zulu jdk17

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [X] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [X] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by BLasan** [comment]
@IOhacker Please squash the commits. Also build is failing

```
  Test verifyConcurrentLoanRepayments() FAILED
  java.lang.AssertionError: 1 expectation failed.
  Expected status code <200> but was <500>.
      at org.apache.fineract.integrationtests.ConcurrencyIntegrationTest.verifyConcurrentLoanRepayments(ConcurrencyIntegrationTest.java:75)
```

BTW, what's the exact use of updating to jdk 17 ?

**Comment by IOhacker** [comment]
Hello BLasan, 

The usage is for extending the EOL which is reported here to be until 2026 

https://www.oracle.com/java/technologies/java-se-support-roadmap.html

On the other hand I had to test which were the errors were causing the compiling failure which includes now fixes:

- The version of JaCoco is now 0.8.7 (now it supports JDK 17)
- Including the JDK API now secured (it is a workaround for passing the JDK_JAVA_OPTS parameters)
- The Travis CI script now should be upgraded to support the JDK 17.

I notice the validation test which were failing, which is a matter of review.

Thank you

**Comment by BLasan** [comment]
> Hello BLasan,
> 
> The usage is for extending the EOL which is reported here to be until 2026
> 
> https://www.oracle.com/java/technologies/java-se-support-roadmap.html
> 
> On the other hand I had to test which were the errors were causing the compiling failure which includes now fixes:
> 
> * The version of JaCoco is now 0.8.7 (now it supports JDK 17)
> * Including the JDK API now secured (it is a workaround for passing the JDK_JAVA_OPTS parameters)
> * The Travis CI script now should be upgraded to support the JDK 17.
> 
> I notice the validation test which were failing, which is a matter of review.
> 
> Thank you

Changes look ok to me. Btw, could you please run the integration tests locally and check the report generated? Or else try reopening the PR with squashed commits

**Comment by IOhacker** [comment]
Yes, I will do a testing on a local Jenkins, trying to emulate as muchs as posible the testing environment, because the Travis CI is not free anymore.

**Comment by xurror** [comment]
Great effort here;

The one problem I see here is that the project itself might not be quite java_17 ready or maybe it is cause I've not personally tested yet but I recall not so long ago, it took quite some struggle to migrate the project to java_11(https://github.com/apache/fineract/pull/820). I'm not sure what causes your build to fail but maybe the work done here: https://github.com/apache/fineract/pull/820 on Java_11 migration can help you resolve it.

And I think we should probably discuss more migrating to Java 17 now.  For example; Gradle does not cover Java 17 yet (https://docs.gradle.org/current/userguide/compatibility.html).

**Comment by fintecheando** [comment]
@xurror it is compiling, It is at testing time when the error occurs, it is running (booting the fineract, without any issue but all the tests must be passed). 

Test verifyConcurrentLoanRepayments() FAILED
  java.lang.AssertionError: 1 expectation failed.
  Expected status code <200> but was <500>.
      at org.apache.fineract.integrationtests.ConcurrencyIntegrationTest.verifyConcurrentLoanRepayments(ConcurrencyIntegrationTest.java:75)

I will continue the research as soon as the tools add support to JDK 17 i.e. Gradle has a RC for JDK 17 support

https://docs.gradle.org/7.3-rc-1/release-notes.html

Also I will take a look at the tickets with Springboot updates.

Regards

**Comment by BLasan** [comment]
@IOhacker Could you please squash the commits?

**Comment by awasum** [comment]
@IOhacker Good work picking this up and making some progress. Another minor feedback, please read: https://github.com/apache/fineract#pull-requests on how we send PRs and write commit messages to always include the FINERACT-ISSUE, that way, the PRs will show up in the JIRA ticket and will ease product management and QA efforts. Do you understand what I am trying to say?

**Comment by awasum** [comment]
> @xurror it is compiling, It is at testing time when the error occurs, it is running (booting the fineract, without any issue but all the tests must be passed).
> 
> Test verifyConcurrentLoanRepayments() FAILED java.lang.AssertionError: 1 expectation failed. Expected status code <200> but was <500>. at org.apache.fineract.integrationtests.ConcurrencyIntegrationTest.verifyConcurrentLoanRepayments(ConcurrencyIntegrationTest.java:75)
> 
> I will continue the research as soon as the tools add support to JDK 17 i.e. Gradle has a RC for JDK 17 support
> 
> https://docs.gradle.org/7.3-rc-1/release-notes.html
> 
> Also I will take a look at the tickets with Springboot updates.
> 
> Regards

For an open source project like ours with few volunteers, lets try to use only GA (Generally Available) releases which are stable and easy to maintain. So lets keep doing the other things required to get this codebase to Java 17 but wait for Gradle 7.3 if that is what supports JDK 17. Do you agree with the above opinion?

**Comment by IOhacker** [comment]
Yes, thank you, I will include that tag for making sure it is
display properly.

Thank you.

**Comment by IOhacker** [comment]
I agree, I have read in the gradle site that it will be available during
this month. So I will wait for this Gradle GA. Also I am checking the code
that is failing to make sure it can pass the test.

Regards

**Comment by IOhacker** [comment]
Yes, Gradle 7.3 has been released.

**Comment by IOhacker** [comment]
I will close this PR, because I have tested the latest update of Spring 2.6.0 and there are less issues. I will submit another PR

**Pull request closed without merging**
