### PR TITLE
Add readiness & liveness probes to fineract-server deployment 

### PR DESCRIPTION
**Pull request by BLasan**
## Description

See[ FINERACT-1296](https://issues.apache.org/jira/browse/FINERACT-1296)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by BLasan** [comment]
@xurror @vidakovic @vorburger  Please review

**Comment by BLasan** [comment]
```
FixedDepositTest > testPrematureClosureAmountWithPenalInterestForWholeTerm_With_360() FAILED
    org.opentest4j.AssertionFailedError: Verifying Pre-Closure maturity amount ==> expected: <true> but was: <false>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:193)
        at org.apache.fineract.integrationtests.FixedDepositTest.testPrematureClosureAmountWithPenalInterestForWholeTerm_With_360(FixedDepositTest.java:1505)
Now running org.apache.fineract.integrationtests.FixedDepositTest#testPrematureClosureAmountWithPenalInterestForWholeTerm_With_365()...
```
@ptuomola Is this due to the changes I've made?

**Comment by vidakovic** [comment]
Anyone has an idea why the build is failing? Can't see why this would be connected to the code changes here...

**Comment by BLasan** [comment]
@xurror Would you mind reviewing this?

**Comment by xurror** [comment]
My guess is that this failing because of the end of the month. There was an issue reported for some tests failing at the end of the month.
I'll close and reopen this to trigger a build. I think it will pass from there.

**Review by xurror — APPROVED** [review]
This PR looks good though.

**Comment by BLasan** [comment]
```
        livenessProbe:
          httpGet:
            path: /fineract-provider/actuator/health/liveness
            port: 8080
          initialDelaySeconds: 400
          periodSeconds: 80
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /fineract-provider/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 400
          periodSeconds: 80
          failureThreshold: 5
```
@xurror For the minikube cluster I created with cpus=4,memory=7GB needs this configurations in order to run the fineract server properly. This will get changed according to the cpu power and other resources you allocate to the cluster. No issue with the approach. Just mentioning :)

**Pull request merged**
