### PR TITLE
Fixed Typo errors in README.md

### PR DESCRIPTION
**Pull request by muskankhedia**
## Description
Fixed typo errors in README.md

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by vorburger — APPROVED** [review]

**Comment by vorburger** [comment]
muskankhedia@ thanks for this contribution! Please keep more coming... :smile_cat:

**Comment by awasum** [comment]
@vorburger , @myrle-krantz Will you be able to help review this? A possible new contributor probably participating in HacktoberFest. 

@muskankhedia  Are you participating in HacktoberFest? https://hacktoberfest.digitalocean.com

**Comment by awasum** [comment]
> @vorburger , @myrle-krantz Will you be able to help review this? A possible new contributor probably participating in HacktoberFest.
> 
> @muskankhedia Are you participating in HacktoberFest? https://hacktoberfest.digitalocean.com

I wrote this a few seconds after the PR had been merged. I did not see this..Sorry.

**Comment by muskankhedia** [comment]
> @vorburger , @myrle-krantz Will you be able to help review this? A possible new contributor probably participating in HacktoberFest.
> 
> @muskankhedia Are you participating in HacktoberFest? https://hacktoberfest.digitalocean.com

@awasum No, I found this project interesting and wanted to contribute to it. Can I please know the platform for discussion with other members of the community on issues?

**Comment by awasum** [comment]
> > @vorburger , @myrle-krantz Will you be able to help review this? A possible new contributor probably participating in HacktoberFest.
> > @muskankhedia Are you participating in HacktoberFest? https://hacktoberfest.digitalocean.com
> 
> @awasum No, I found this project interesting and wanted to contribute to it. Can I please know the platform for discussion with other members of the community on issues?

@muskankhedia here is the website for the project: http://fineract.apache.org/

Here to join the mailing list and participate in discussions: http://fineract.apache.org/#contribute
 
If you use, build on top of, deploy or are building contributions and modifications to Apache Fineract, this is the list for you.
To subscribe, send a blank email to dev-subscribe@fineract.apache.org

There is the Fineract JIRA here: https://issues.apache.org/jira/projects/FINERACT/issues/

Join the mailing list, introduce yourself and say hi. Ask any questions on the list and we will try to respond. You will learn the rest as you move along.

Welcome to Apache Fineract, @muskankhedia

**Comment by muskankhedia** [comment]
@awasum. Thank you for the help.

**Comment by muskankhedia** [comment]
> > > @vorburger , @myrle-krantz Will you be able to help review this? A possible new contributor probably participating in HacktoberFest.
> > > @muskankhedia Are you participating in HacktoberFest? https://hacktoberfest.digitalocean.com
> > 
> > 
> > @awasum No, I found this project interesting and wanted to contribute to it. Can I please know the platform for discussion with other members of the community on issues?
> 
> @muskankhedia here is the website for the project: http://fineract.apache.org/
> 
> Here to join the mailing list and participate in discussions: http://fineract.apache.org/#contribute
> 
> If you use, build on top of, deploy or are building contributions and modifications to Apache Fineract, this is the list for you.
> To subscribe, send a blank email to [dev-subscribe@fineract.apache.org](mailto:dev-subscribe@fineract.apache.org)
> 
> There is the Fineract JIRA here: https://issues.apache.org/jira/projects/FINERACT/issues/
> 
> Join the mailing list, introduce yourself and say hi. Ask any questions on the list and we will try to respond. You will learn the rest as you move along.
> 
> Welcome to Apache Fineract, @muskankhedia

@awasum Does fineract have any discussion channel in gitter or slack or any chat or networking medium.

**Comment by awasum** [comment]
> > > > @vorburger , @myrle-krantz Will you be able to help review this? A possible new contributor probably participating in HacktoberFest.
> > > > @muskankhedia Are you participating in HacktoberFest? https://hacktoberfest.digitalocean.com
> > > 
> > > 
> > > @awasum No, I found this project interesting and wanted to contribute to it. Can I please know the platform for discussion with other members of the community on issues?
> > 
> > 
> > @muskankhedia here is the website for the project: http://fineract.apache.org/
> > Here to join the mailing list and participate in discussions: http://fineract.apache.org/#contribute
> > If you use, build on top of, deploy or are building contributions and modifications to Apache Fineract, this is the list for you.
> > To subscribe, send a blank email to [dev-subscribe@fineract.apache.org](mailto:dev-subscribe@fineract.apache.org)
> > There is the Fineract JIRA here: https://issues.apache.org/jira/projects/FINERACT/issues/
> > Join the mailing list, introduce yourself and say hi. Ask any questions on the list and we will try to respond. You will learn the rest as you move along.
> > Welcome to Apache Fineract, @muskankhedia
> 
> @awasum Does fineract have any discussion channel in gitter or slack or any chat or networking medium.

Most Discussions about Fineract happen on the mailing list. That is where you will get the most help. I advice you to use the mailing list.

**Pull request merged**
