### PR TITLE
FINERACT-1515 Allow multi-disbursements without setting up expected tranche details

### PR DESCRIPTION
**Pull request by John-Woodlock**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by vidakovic** [comment]
@johnw65 ... code changes look good to me... only thing complaining here are the style checks (tabs vs. spaces, curly braces position etc.). Executing the following command should help with most (if not all) of them:
```
./gradlew spotlessApply
```
The only thing (I am aware of) that is not solved automatically are "badly" formatted imports (aka Asterisk imports like `org.apache.fineract.*`). Just saying, if you come across those then you have to fix them manually (or use your IDE formatter with proper configuration if available).

I guess you use Eclipse? Here are some useful configs you can use with respective Eclipse plugins:

- Checkstyle: https://github.com/apache/fineract/blob/develop/config/checkstyle/checkstyle.xml
- Eclipse code formatter: https://github.com/apache/fineract/blob/develop/config/fineractdev-formatter.xml

**Comment by John-Woodlock** [comment]
I'm closing this for now unless the checks pass and will re-issue later

**Comment by John-Woodlock** [comment]
CI now passes with code reformating

**Comment by vidakovic** [comment]
You want to open the PR again?

**Comment by John-Woodlock** [comment]
I've done another pull request

**Pull request closed without merging**
