### PR TITLE
PART 2 - Use prepared statements instead of string concatenated SQL everywhere (FINERACT-1343)

### PR DESCRIPTION
**Pull request by josemakara2**
## Description

See FINERACT-1343
Work in progress .. 

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by josemakara2** [comment]
Hi Fineract community members,
I would like feedback on this particular commit. It is introducing a new project library dependencies
https://github.com/apache/fineract/pull/1687/commits/2d8f3f0a326992e1804757e27a6f884d582754e5
_Use ESAPI, `The OWASP Enterprise Security API`, Escaping where Prepared Statements with Parameterized Queries is not feasible to mitigate SQL Injection (FINERACT-1343)_
Partly blocked by FINERACT-1343

**Comment by awasum** [comment]
Woow... This looks like valuable work. @ptuomola , @vorburger . Have time to take a look?

**Comment by ptuomola** [comment]
@josemakara2 This looks really good and would definitely be in favour of merging this... just wondered if you had more work planned for this? The description says "Work in progress" and there's also a TODO in the code...

**Comment by awasum** [comment]
@ptuomola  Maybe we should just merge this one if it Look Good. Than to let the bot auto close it again.

**Comment by ptuomola** [comment]
@awasum Yes, at a quick glance this looks good. I just didn't do anything on this as the comment says "Work in progress". Also the build seems to be failing (could be unrelated) and the comments would need to be squashed. @josemakara2  would you have a chance to finish this off, and we can then merge?

**Comment by BLasan** [comment]
@josemakara2 Can you resolve the build failure?
`Still running (12 of 60): ./gradlew -q --no-daemon --console=plain licenseMain licenseTest check build test --fail-fast doc
The command ./gradlew -q --no-daemon --console=plain licenseMain licenseTest check build test --fail-fast doc exited with 1.`

**Comment by ptuomola** [comment]
Let's see if we can get the build to pass...

**Comment by ptuomola** [comment]
Looks like this is failing because of classpath duplicates. Need to see if we can fix those...

**Comment by awasum** [comment]
This still looks important... @fynmanoj , @galovics , @ptuomola , @vidakovic ...Anyone interested to make this happen?

**Comment by ptuomola** [comment]
I tried to fix this earlier but kept getting some strange classpath conflicts. But a lot has changed since then, so probably worth trying again...

**Comment by vidakovic** [comment]
Closing because it looks abandoned.

**Comment by awasum** [comment]
Looking this one... if someone rebased and made it pass the build.. it will fix some of the issues seen here: https://github.com/apache/fineract/security/code-scanning

**Pull request closed without merging**
