### PR TITLE
add (obvious) rebase step to PR Help in README

### PR DESCRIPTION
**Pull request by vorburger**
#782 follow-up

### CODE REVIEW

**Comment by vorburger** [comment]
@awasum @xurror @nikpawar89 makes sense?

Hopefully this will make it clearer e.g. for #769, #749, #737 ...

**Review by xurror — APPROVED** [review]
LGTM

**Comment by nikpawar89** [comment]
+1

**Comment by maektwain** [comment]
This itself is failing. :)

**Comment by vorburger** [comment]
#790 raised for that failing test; I'll rebase this one once that one successfully built and is merged.

**Comment by vorburger** [comment]
awaiting #800, then rebase

**Pull request merged**
