### PR TITLE
Fix possible NPE when uploading Documents & Images (FINERACT-1036)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-1036

### CODE REVIEW

**Comment by vorburger** [comment]
@ptuomola (or @vidakovic) I'm sure this is OK for you? Asking more pro-forma; I'll self merge this one in 24h if you don't get to it.

**Review by vidakovic — APPROVED** [review]
LGTM

**Comment by ptuomola** [comment]
Hi @vorburger - is there a reason why you didn't use the "usual" DataValidatorBuilder/BaseDataValidator pattern for this check? I'm sure this works - but that would have been more consistent with the rest..

**Comment by vorburger** [comment]
> is there a reason why you didn't use the "usual" DataValidatorBuilder/BaseDataValidator pattern for this check?

Good point. I can't find `BaseDataValidator` (:question:), but the `DataValidatorBuilder` seems to be more used in `.services.` and `.command.`.. I can't find a single instance of it in an `.api.` - but I guess there is no reason why not to? I'll leave this PR as is, and will raise a separate alternative one, for comparison. Who knows, I may even use this as the opportunity to write DOC - imagine that, an open source project with real technical framework documentation!! :smile:

**Comment by vorburger** [comment]
#1456

**Pull request closed without merging**
