### PR TITLE
SchedulerJobsTestResults(FINERACT-923, FINERACT-924, FINERACT-925)

### PR DESCRIPTION
**Pull request by maektwain**
Flaky Test Issues 

https://issues.apache.org/jira/browse/FINERACT-923?jql=text%20~%20%22testApplyHolidaysToLoansJobOutcome%22

 #796

### CODE REVIEW

**Comment by maektwain** [comment]
@vorburger Here is the PR as suggested by the Readme.

**Comment by maektwain** [comment]
```
testApplyAnnualFeeForSavingsJobOutcome
```

This failed I don't see any PR or Issue?

**Comment by vorburger** [comment]
> testApplyAnnualFeeForSavingsJobOutcome This failed I don't see any PR or Issue?

@maektwain just iteratively follow the process described on https://github.com/apache/fineract#pull-requests ... :smiling_imp: (so add that to this PR as well). If this could be written more clearly in the README, then improve it. smiley_cat

**Comment by maektwain** [comment]
Failed again at

```
 testApplyPenaltyForOverdueLoansJobOutcome
```

This is crazy.

**Comment by maektwain** [comment]
@vorburger  could we get this merged?

**Comment by vorburger** [comment]
@ptuomola @awasum FYI

**Pull request merged**
