### PR TITLE
more clean up in SchedulerJobsTest (re. FINERACT-922)

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@awasum @ptuomola does this LGTY? It's ongoing clean-up, while I get familiar with this code...

**Comment by awasum** [comment]
This fails again due to the Scheduler problem.  Other than that...Coding to Interface as you done and other clean ups are relevant. @vorburger . Maybe we should assemble a couple of these scenarios for new contributors and our upcoming GSoC students so they use as starter issues.

This LTGM except we want to add a line to ignore the failing test. if not related to these changes.

**Comment by vorburger** [comment]
#815 adds an ignore to the IT that failed here.

**Comment by vorburger** [comment]
@awasum OK, thanks for super quick review, I've merged this now one.   @ptuomola FYI.

**Pull request merged**
