### PR TITLE
remove old constructor from SchedulerJobHelper (related to FINERACT-922)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-922

### CODE REVIEW

**Comment by vorburger** [comment]
This will have to be re-based after #968 for FINERACT-1016 for the build to pass.

**Comment by vorburger** [comment]
@xurror if after you've merged #959 (do that one first, please) this has no conflicts, would you like to then merge this one as well? (If the merge of #959 causes conflicts on this one, then I'll fix them, later.)

**Comment by xurror** [comment]
@vorburger, there is some conflict here.

**Comment by vorburger** [comment]
This PR was much too big and contained a number of clean-up changes which should not be part of this. I've cleaned it up and dropped everything but the removal of the old constructor now. @xurror please merged whenever build passed - thanks!

**Review by xurror — APPROVED** [review]

**Pull request merged**
