### PR TITLE
Francisguchie fix sql error at loan repayment: FINERACT-1054

### PR DESCRIPTION
**Pull request by awasum**
## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by thesmallstar** [comment]
Needs  a ./gradlew spotlessApply 
Are you  facing some issues with spotless? I saw many PRs failed due to that? Is it not working in this case?

**Comment by awasum** [comment]
> Needs a ./gradlew spotlessApply
> Are you facing some issues with spotless? I saw many PRs failed due to that? Is it not working in this case?

@francisguchie , was facing issues.. I think we should make Spotless to do `spotlessApply` before compiling. So we dont need to even do a check before compilation... Is that a good idea? Or apply and check before the compile task..so that people..stop having problems with it?

**Comment by thesmallstar** [comment]
> @francisguchie , was facing issues.. I think we should make Spotless to do `spotlessApply` before compiling. So we dont need to even do a check before compilation... Is that a good idea? Or apply and check before the compile task..so that people..stop having problems with it?

-> Interesting idea, I will try to do that and make a PR if that works ;)

**Comment by awasum** [comment]
@francisguchie ..See this for your PR.

**Comment by francisguchie** [comment]
yes i see , thanks @awasum  and @thesmallstar

**Comment by awasum** [comment]
@francisguchie .. I want you to pull this PR down to your local codebase on a separate branch. Then send a PR from your own repo. I want to make sure you get this right so review comments can be addressed by you.

next time, before you commit and push code, make sure you have run `./gradlew clean build` for bulding, `.gradlew bootRun` to test you changes functionally and makes sure they work from an end user POV and then run ./gradlew integrationTest to make sure integration Tests are all passing before you commit and push your changes. Go back to all your PRs and makes sure they are in good shape, they don;t have incompatible and corrupted git history etc. It is your responsibility (read the README too) to make sure your PR is passing build before we can review. Please help us help you make more contributions. Read up whatever you don't yet know and ask questions and we will try to help. I hope you now understand why your PR was not passing?

**Comment by francisguchie** [comment]
@awasum 
Thanks for the guidance and support. 

I do not not have rights to pull this PR down. So i will raise another one as guided.
please pull this PR down

**Comment by awasum** [comment]
If you went to the top of the PR here: 
image

You will see the branch where the PR originates : https://github.com/awasum/fineract/tree/francisguchie-fixSqlErrorAtLoanRepayment

Please..always run your changes and make sure the tests pass locally before pushing.

**Comment by awasum** [comment]
Closing this in favour of: https://github.com/apache/fineract/pull/1166,  I was only trying to help @francisguchie  here.

**Comment by francisguchie** [comment]
Thanks @awasum. Your help was such a boost to my efforts

**Pull request closed without merging**
