### PR TITLE
Removed Console output and added checkstyle module

### PR DESCRIPTION
**Pull request by thesmallstar**
## Description
There were many TODOs, to get started and learn the correct method I thought this would be the easiest one.
The build is passing but I would require following confirmations:
1. Is this the correct approach, should I continue the same way for other TODOs.
2. Since we are removing the console outputs, was it expected to log it?
3. In Listener.java the build failed if the method msg.getText() is not invoked, current implementation seems like a temporary fix, what is the correct way?
4. Removed Console outputs and replaced them with a new line(blank line) any suggestions on this? 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by thesmallstar** [comment]
The build is failing probably #732 will fix it.

**Comment by awasum** [comment]
Try to fix root cause of build generally failing... Will you like to help? Please check flyway mismatch numbering problem with latest merge...

**Comment by vorburger** [comment]
@thesmallstar rebase this, and we'll review it when build passed!

**Comment by thesmallstar** [comment]
@vorburger the build looks good now :)

**Review by vorburger — CHANGES_REQUESTED** [review]
> Is this the correct approach, should I continue the same way for other TODOs.

YES! Please. That's exactly the right way to do this!

> Since we are removing the console outputs, was it expected to log it?

It's only in integration tests.. where it probably can be useful to debug failing tests. If you have the time to change them to LOG.info statements, I think that would be better.

I've only really reviewed it now, sorry for not noticing before.

>  In Listener.java the build failed if the method msg.getText() is not invoked, current implementation seems like a temporary fix, what is the correct way?

LOG.debug()

> Removed Console outputs and replaced them with a new line(blank line) any suggestions on this?

I didn't understand what you meant here.

**Comment by thesmallstar** [comment]
> I didn't understand what you meant here.

@vorburger , I just realized that was a repeated question, I meant if the method implemented in this PR is correct( turns out it is ).

Replacing with LOG statements, thank you for the review.

**Comment by thesmallstar** [comment]
@vorburger I have replaced System.out with LOG statements, but Spotbug is bothered with log performance and suggesting some changes, Is there a way to solve this rather than going individually through all 200-250 lines?

**Comment by vorburger** [comment]
> @vorburger I have replaced System.out with LOG statements, but Spotbug is bothered with log performance and suggesting some changes, 

Yeah, that's due to the JUST introduced #716, see [FINERACT-696](https://issues.apache.org/jira/browse/FINERACT-696) for background.

 > Is there a way to solve this rather than going individually through all 200-250 lines?

I pulled this locally and noticed there are 270 violations... too many to manually fix up? :smile: Do a bunch every day, instead of all together?

Alternatives I can think of could be to configure Checkstyle to not run this particular check on src/test and only src/main, but I think that will be a PITA to configure (you would need separate configuration files, and somehow tell the Gradle plugin to run different configs for different dirs; I'm not sure that's possible), and also confusing for future developers, so I wouldn't do that and keep it simple.

In terms of best use of time, what I would probably do if I were you is maybe pause this one, and first move on to gradually activating other Checkstyle checks, and then come back to this one later / at the end.

**Comment by thesmallstar** [comment]
@vorburger agreed, actually, I manually added those logger variables to 93 files(each one being unique with class name) and hoped for the reward of merged PR  😸 
I would go for editing this daily then, should be done in a week without being bored :P 

-thanks

**Comment by thesmallstar** [comment]
@vorburger I am planning to add This into my GSOC proposal, Adding all check-style modules and working on removing concatenated SQL strings(using SQL builder) and solving other security issues that are confirmed by the plugin, along with solving some pending bugs on Jira. 
Considering the amount of work, I thought this is a would-be a worthy candidate I have also discussed the same with @awasum  who liked the idea. 

What do think? Do you think this is a good and worthy Idea?

**Comment by vorburger** [comment]
> What do think? Do you think this is a good and worthy Idea?

absolutely, please go for it. (I'm not sure it's a full GSoC project, but I would say start with this; I expect you'll probably be able to complete it sooner than you think - and then you can look for more work!)

**Comment by awasum** [comment]
Status on this?

**Comment by thesmallstar** [comment]
@awasum fixed a part of it, will be done soon :)

**Comment by thesmallstar** [comment]
This will be covered in other PR(closing this one).

**Pull request closed without merging**
