### PR TITLE
Make it possible to customize JDBC URLs in Docker Image at run-time instead of at build (FINERACT-773)

### PR DESCRIPTION
**Pull request by vorburger**
see [FINERACT-773](https://issues.apache.org/jira/browse/FINERACT-773)

### CODE REVIEW

**Comment by vorburger** [comment]
@Anh3h @conradsp please review (once the build passes) and merge if OK for you... this is the follow-up to the earlier #593, #595 and #625.

I've locally tested this, but if you want to be sure that `docker compose` still works, we can first get #644 merged and then rebase this one on that, to "prove" it does (because Travis CI will verify these changes, after #644).

**Comment by vorburger** [comment]
@awasum if you have time & interest, perhaps you'd also like to review this one?

**Comment by edcable** [comment]
@awasum Are you able to review this PR?

**Comment by vorburger** [comment]
@awasum @Anh3h @conradsp would you like to review this?  I'd love to still see this make it into 1.4.0.

**Comment by awasum** [comment]
> @awasum @Anh3h @conradsp would you like to review this? I'd love to still see this make it into 1.4.0.

On..it...let Travis run.

**Comment by awasum** [comment]
Why is this failing? Seems the actuator health endpoint is not found?

**Comment by vorburger** [comment]
> Why is this failing? Seems the actuator health endpoint is not found?

very curious, because locally it works (I've just re-tested it).  But I just had a "fun" idea how we'll (hopefully) be able to see the real reason for such failures much more easily (by adding `|| docker logs`) - let's see if that helps to clarify why this fails on Travis - build is currently running...

**Comment by vorburger** [comment]
@awasum huh, now it passed... review? :smile: May be that 30s isn't (always) enough.. if this happens more often, then we should increase that. (But the new `|| docker logs` still seems like a neat idea, to help understand future problems, so I'm leaving that in.)

**Comment by awasum** [comment]
Thanks for fixing this Mike, Merging now.

**Comment by vorburger** [comment]
This actually broke more than it improved but #690 fixes it again.

**Pull request merged**
