### PR TITLE
fix error at loan repayment fineract-1054

### PR DESCRIPTION
**Pull request by francisguchie**
## Description
https://issues.apache.org/jira/browse/FINERACT-1054

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by awasum — CHANGES_REQUESTED** [review]
Don't change anything in the Gradle properties file.

**Comment by awasum** [comment]
Fix build failure by running './gradlew :spotlessApply' to fix these violations. See error logs on Travis: https://travis-ci.org/github/apache/fineract/builds/704389208

**Comment by awasum** [comment]
> Don't change anything in the Gradle properties file.

Also dont touch this file: https://github.com/apache/fineract/blob/develop/fineract-provider/gradle/wrapper/gradle-wrapper.properties

Allow it to be automatically updated. So just use take the latest changes in the above file and put in yours. I dont know if you understand me?

**Comment by francisguchie** [comment]
@awasum , Let me make raise another PR

**Comment by awasum** [comment]
No, adjust it here on this branch and pr , u don't need to raise a separate pr to fix this one. Just commit to this branch on your fork..please... Do you understand me?

**Pull request closed without merging**
