### PR TITLE
Fix to charge fees when total amount changed during approval.

### PR DESCRIPTION
**Pull request by tangemicioglu**
The issue is currently at https://github.com/openMF/community-app/issues/1719 but the problem was in Fineract instead of the community-app.

### CODE REVIEW

**Comment by nazeer1100126** [comment]
If the loan is enabled with Multi disbursements, recalculateAllCharges() method will be called twice while approving a loan with this change.

**Comment by tangemicioglu** [comment]
Would it be a better alternative to put it between the multi disbursement and approved loan amount blocks? It would run every time the approve loan function is called but it would run once.

**Comment by nazeer1100126** [comment]
@Eiliries Yes it is good to moving existing call from multidisbursement if condition.

**Comment by tangemicioglu** [comment]
@nazeer1100126 I've changed it so that it's called once and it works without any problems.

**Pull request merged**
