### PR TITLE
Create Client doesn't giving error on submit without filling form #3069

### PR DESCRIPTION
**Pull request by habile-technologies**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by ptuomola** [comment]
Hi - as per the schema, it should be OK for legalForm to be null:

    @Column(name = "legal_form_enum", nullable = true)
    private Integer legalForm;

Is there a reason why this should be made mandatory?

**Comment by bharathcgowda** [comment]
Hi, @ptuomola  Making this field mandatory will enforces users to select the legal form which they want to create (person or an entity)  which is the correct way to create a client. (suggested by many organizations as well)
Which helps the accuracy of the data storage and reporting data as well.
Also, helps when any new legal form is introduced in the future.

**Comment by BLasan** [comment]
@habile-technologies Build fails

```
InteropTest > testInteroperation() FAILED
    java.lang.AssertionError: 1 expectation failed.
    Expected status code <200> but was <403>.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
        at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1656)
        at jdk.internal.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1267)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:818)
        at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
        at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1661)
        at jdk.internal.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1267)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:818)
        at groovy.lang.GroovyObject.invokeMethod(GroovyObject.java:39)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
        at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy:175)
        at io.restassured.internal.RequestSpecificationImpl.post(RequestSpecificationImpl.groovy)
        at org.apache.fineract.integrationtests.common.Utils.performServerPost(Utils.java:160)
        at org.apache.fineract.integrationtests.common.ClientHelper.createClient(ClientHelper.java:86)
        at org.apache.fineract.integrationtests.common.ClientHelper.createClient(ClientHelper.java:80)
        at org.apache.fineract.integrationtests.common.ClientHelper.createClient(ClientHelper.java:75)
        at org.apache.fineract.integrationtests.interoperation.InteropTest.createClient(InteropTest.java:125)
        at org.apache.fineract.integrationtests.interoperation.InteropTest.testInteroperation(InteropTest.java:113)
```

**Comment by bharathcgowda** [comment]
@habile-technologies  could you please check and resend this PR?

**Comment by Charulathakarthikeyan** [comment]
@BLasan  I added only two validation and tested it . I'd checked now also  ,i can build both war and jar file .Can i get your build comment which you using .Or can you please recheck it again  .

**Comment by bharathcgowda** [comment]
@Charulathakarthikeyan @habile-technologies  Travis Check Failed, could you please check the details and make the necessary changes.

**Comment by bharathcgowda** [comment]
@Charulathakarthikeyan  @habile-technologies 
image

**Comment by bharathcgowda** [comment]
@habile-technologies @Charulathakarthikeyan  did you get a chance to look into this PR?

**Comment by ptuomola** [comment]
Code looks ok - need to see why build is failing

**Comment by BLasan** [comment]
@habile-technologies Can you run the tests locally and check the built report for tests?

```
org.apache.fineract.integrationtests.ConcurrencyIntegrationTest
  Test verifyConcurrentLoanRepayments() FAILED
  java.lang.AssertionError: 1 expectation failed.
  Expected status code <200> but was <403>.
      at org.apache.fineract.integrationtests.ConcurrencyIntegrationTest.verifyConcurrentLoanRepayments(ConcurrencyIntegrationTest.java:73)
```

**Comment by bharathcgowda** [comment]
@habile-technologies  can you try what @BLasan suggested once?

**Comment by awasum** [comment]
@habile-technologies  please take look at this, fix issue making Travis to fail. Also rebase your changes ontop of develop branch and fix merge conflicts please. This can be merged soon as you do the above.

**Comment by ptuomola** [comment]
Let's see if the build passes now...

**Comment by ptuomola** [comment]
This change makes half of the integration tests to fail... that needs to be investigated / fixed before merging

**Comment by ptuomola** [comment]
Let's see if we can get this build to pass now..

**Comment by ptuomola** [comment]
This was implemented in a separate PR #1979

**Pull request closed without merging**
