### PR TITLE
FINERACT-610 - Post Interest As On Permision

### PR DESCRIPTION
**Pull request by MexinaD**

### CODE REVIEW

**Comment by ShruthiRajaram** [comment]
As it is related to front end, closing the PR

**Comment by MexinaD** [comment]
Hello @ShruthiRajaram 
The issue is in back end and not front end, since the permissions are created by schema and not through front end.

**Comment by ShruthiRajaram** [comment]
Hi @MexinaD , I understand that permissions are stored in db. But the logic for the post as on date is present under a different class with different permission. 
And the permission which were referred in the front end was invalid as there is no handler for that permission. So we corrected the permission in the front end to work properly.

**Comment by MexinaD** [comment]
Hello @ShruthiRajaram 
Thank you for that clarifications

**Pull request closed without merging**
