### PR TITLE
[WIP] require Java 11 [WIP]

### PR DESCRIPTION
**Pull request by vorburger**
This has a number of pre-requisites, and this PR as is today does not work.

As other PRs get merged over the coming days & weeks, we'll eventually be able to get this to pass.

### CODE REVIEW

**Comment by vorburger** [comment]
> This has a number of pre-requisites

including #608, and possibly https://github.com/radcortez/openjpa-gradle-plugin/issues/8 (although strangely I didn't run into that issue; curious).

**Comment by lingocoder** [comment]
> (although strangely I didn't run into that issue; curious)

Hey @vorburger. Are you referring to the *`:enhance`* issue? Or the *`:metamodel`* issue? Apologies for the confusion between the two. 

The *`:enhance`* issue that I referred to [*here*](https://github.com/vorburger/fineract/pull/1#issuecomment-509453457) and the *`:metamodel`* issue that I referred to [*here*](https://github.com/radcortez/openjpa-gradle-plugin/issues/8#issue-464995001), are separate issues — *though on the same plugin* — discovered under separate scenarios. It is very likely, I suspect, that the two issues are related somehow.

I discovered the *`:enhance`* issue immediately after I cloned the fineract project. The very first thing I did as a sanity check, was run *`gradle check`* on the project. That failed, [*producing this stack trace*](http://bit.ly/RadCrtzNhnc). However, I proceeded with [*my`api/implementation` changes*](http://bit.ly/FinerPR1) regardless, by working around that. I simply excluded the problematic task with *`gradle -x :enhance ...`* whenever I needed to build the project.

After I was finished, I was still curious why the *`:enhance`* task had failed. So I investigated by creating a simple, stripped-down standalone project that only applied the *`com.radcortez.gradle:openjpa-gradle-plugin:3.0.0`*. That simple project did not include any of the other dependencies that fineract has. 

It was under that scenario that I discovered the radcortez plugin's *`:metamodel`* issue.  [*Here's the stack trace I encountered*](https://github.com/radcortez/openjpa-gradle-plugin/files/3368461/openjpa-gradle-plugin.issue.8.a.txt) in that scenario. 

It's possible that the reason you have not encountered [*the `:metamodel` issue*](http://bit.ly/RadCrtz8) in the fineract project, might be because [*the `:metamodel` task/extension*](http://bit.ly/RadCrtzMeta) must be explicitly ran/configured in order to reproduce [*the issue I reported*](http://bit.ly/RadCrtz8). Whereas, the *`:enhance`* task is automatically ran as part of any Gradle build that includes Gradle's built-in *`classes`* task; such as the *`gradle :check`* task.

Or is it possible that some admixture of all of the dozens of different dependencies in the fineract project affects the behavior of the radcortez plugin? Could it be that some combination of direct dependencies and transitive dependencies in fineract are masking or eliminating the radcortez plugin issue for you? Or maybe I'm only seeing issues on my machine because of development environment-related differences? Like OS or whatever? I'm on Windows 7 Professional 64 bit.

**Comment by vorburger** [comment]
> > This has a number of pre-requisites
> 
> including #608, and possibly [radcortez/openjpa-gradle-plugin#8](https://github.com/radcortez/openjpa-gradle-plugin/issues/8)

most importantly, this will require #525 to get done first, which we should focus on... @lingalamadhukar what I did when I started this PR was locally merge #525 into it (I just didn't want to push that onto this PR), then the problems re. OpenJPA you describe above are gone (for me). Sorry if this wasn't made clear enough here.

So what I'd like to do is finish up #525 without Java 11, and only then get back to this. As for the other purely Java 11 related point you raised over in #525, some feedback:

> > how weird that I didn't hit this...
> 
> P.S. @vorburger , [_The apache#609 CI failure_](http://bit.ly/Trvs609J11) is most likely due to the last change to [_fineract-provider/gradle/wrapper/gradle-wrapper.properties_](http://bit.ly/GrdlWrpr210) being four+ years ago. Version 2.10 of the wrapper needs to be updated to at least 5.2.x I believe.

Nah, that's solved by the 2nd commit currently on this PR which switches Travis CI to build using Java 11 instead of 8.

**Comment by vorburger** [comment]
Note to self: Once this actually works, the `./Dockerfile` needs to be updated for Java 11 as well.

**Comment by vorburger** [comment]
@awasum this one won't pass the Travis CI build, and requires more work from me (when I have time).

**Comment by xurror** [comment]
From what I see from the docker-compose.yaml file, the docker instance only creates the databases but does not populate them with sample data(Well atleast I think that's what it does) but I have the feeling that the server needs sample data in the DB inorder to connect/load properly. Not sure if I'm right about this

**Comment by awasum** [comment]
Maybe, we put this up for GSOC or Outreachy. Is this big enough to cover a 3 months internship by a student? @vorburger

**Comment by awasum** [comment]
See: https://issues.apache.org/jira/browse/FINERACT-846

**Comment by maektwain** [comment]
Hey, folks what is the status on this ,I would like put some time on it @awasum

**Comment by maektwain** [comment]
In first instance I failed with below errors 

```
> Task :compileIntegrationTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :spotbugsIntegrationTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

> Task :spotbugsMain
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

> Task :spotbugsTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Users/maektwain/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.9/4222eafca660d01a44682c3fe4c629005728973/groovy-2.5.9.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release


```

**Comment by maektwain** [comment]
I don't think this is an issue because of JAVA 11
 
```
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [META-INF/testNotificationContext.xml]; nested exception is java.lang.NoClassDefFoundError: org/w3c/dom/ls/DocumentLS
```

**Comment by awasum** [comment]
@maektwain ..Go ahead..If you can fix it soonest...we can look for something else to put up for GSoC or Outreachy 2020. Do you want to maybe mentor this project?

**Comment by maektwain** [comment]
@vorburger Shouldn't we moving for independent gradle rather then shipping one with the repo.

**Comment by maektwain** [comment]
@vorburger Shouldn't we moving for independent gradle rather then shipping one with the repo.

Another thing in the future also if we move ahead with other version of the JAVA we should ship it feature like 

``` gradle upgradeDependency ```

**Comment by maektwain** [comment]
So, I could build the solution but without tests so we need to workaround upgrading tests dependencies @awasum could you help

**Comment by vorburger** [comment]
No, removing the Gradle wrapper is bad idea; it's useful to have the
"official" (tested) version in a project, this saves many headaches. Anyone
locally can still try use another Gradle version, of course. Also, this had
nothing to do with Java 11 and this PR.

Using gradle upgradeDependency seems interesting. But the best way to
contribute to open source is not to post this as a comment on an existing
PR, but to just go ahead and try it, in a small new PR, focused on changing
just the minimum possible, and then evolve, step by step. If it passes the
build, we'll review and merge it.

Re. helping to continue the work here, I propose you start a separate PR,
based on this. If it passes the build, we'll review and merge it. And  you
obviously cannot just disable all tests, no - that wouldn't be any fun...
;-)

**Comment by vorburger** [comment]
#820 by @ptuomola is picking this up... I'll close this PR when that is merged.

**Pull request closed without merging**
