### PR TITLE
[FINERACT-1875] Support postgresql compatibility when retrieveAllTaxGroups

### PR DESCRIPTION
**Pull request by balancehero-neal**
## Description

Issue: [FINERACT-1875](https://issues.apache.org/jira/browse/FINERACT-1875)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by balancehero-neal** [comment]
I'm a little bit worried.
To solve this issue, Is it okay to just add PreparedStatementCreator(feat. ResultSet.TYPE_SCROLL_SENSITIVE) in the particular query? 😅

Because there are many codes related to a similar issue.

**Review by galovics — CHANGES_REQUESTED** [review]
First things first, please add an integration test to cover this use-case, otherwise it can break anytime.

**Comment by balancehero-neal** [comment]
@galovics 
I'm checking Integration Test Structure. It will require some time.

**Comment by galovics** [comment]
@balancehero-neal is this being worked on or abandoned?

**Pull request closed without merging**
