### PR TITLE
FINERACT-2106: fix the misuse of `ToApiJsonSerializer`

### PR DESCRIPTION
**Pull request by Zeyad2003**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by vidakovic** [comment]
Can you give a bit more context what is supposedly wrong here? The Jira ticket doesn't give too much (no) context!

**Comment by Zeyad2003** [comment]
> Can you give a bit more context what is supposedly wrong here? The Jira ticket doesn't give too much (no) context!

There are 2 `ToApiJsonSerializer` in the service for serializing `Map<String, Object>` and `CommandProcessingResult` datatypes.

**toApiResultJsonSerializer** should serialize `CommandProcessingResult` datatype and **toApiJsonSerializer** should serialize `Map<String, Object>`

The usage is reversed in the code so I switched it.

**Comment by vidakovic** [comment]
That would be a rather major mistake... can you explain why non of the tests seem to be failing with the mixup in place?

**Comment by Zeyad2003** [comment]
@vidakovic 

The reason is that we're ultimately serializing an `Object`, not a specific generic type (T). Here’s the current code:

```java
    @Override // Used to serialize the CommandProcessingResult
    public String serializeResult(final Object object) {
        return this.commandProcessingResultSerializer.serialize(object);
    }

    @Override // Used to serialize the Map
    public String serialize(final Object object) {
        return this.excludeNothingWithPrettyPrintingOff.serialize(object);
    }
```

With this setup, we could technically use a single ToApiJsonSerializer for both cases, and it would still work. However, if we were to switch the method signatures to use generics, the code would likely fail. This is why I swapped the places.

> [!NOTE]
> Here's the final executed code for serializing (left for `CommandProcessingResult` and right for `Map<String, Object>`):
> Screenshot from 2024-07-15 21-49-53

**Comment by adamsaghy** [comment]
@Zeyad2003 @vidakovic what's the latest status regarding this?

**Comment by Zeyad2003** [comment]
> @Zeyad2003 @vidakovic what's the latest status regarding this?

It's finished and it's not related to the GSoC project, just a small swapping for the usage of `ToApiJsonSerializer`.

Explained above why this is done.

**Pull request merged**
