### PR TITLE
FINERACT-2005: Prohibit password re-use

### PR DESCRIPTION
**Pull request by hero78**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@hero78 Please rebase your PR!
Also please have only 1 commit only! If you need you can squash them locally before!

**Comment by hero78** [comment]
Thanks @adamsaghy , Will do so

**Comment by hero78** [comment]
@adamsaghy  It's Done. Kindly review. Thanks

**Review by adamsaghy — CHANGES_REQUESTED** [review]
@hero78 I have taken a look on the FINERACT-2005 and your implementation and i find major differences... Kindly asking you to review what the story is about and make the necessary changes:
- Enabling / disabling "reuse password configuration": If it is disabled we should not check it, but that is not mean we cannot change password or reset password.
- Number of previous password should be configurable: no it is hardcoded

**Comment by hero78** [comment]
@adamsaghy , Yes the number of previous passwords is configurable but we have a hardcoded values to act like a default.When the configuration is disabled. On assumption a user won't hit. So the change password on enable/disable will keep checking but since we have a default with a high cap. This won't catch him

**Comment by adamsaghy** [comment]
> @adamsaghy , Yes the number of previous passwords is configurable but we have a hardcoded values to act like a default.When the configuration is disabled. On assumption a user won't hit. So the change password on enable/disable will keep checking but since we have a default with a high cap. This won't catch him

I dont like the hardcoded value. If the functionality is disabled, then there should be **no** any check for previous passwords.
The new configuration should be **turned on by default** and you might wanna set it for a higher number if you think 3 is not reasonable.

If the reuse is disabled, we shall not throw an error if the user wanna update its password.

**Comment by hero78** [comment]
@adamsaghy  Thanks. I will Update as required.

**Comment by adamsaghy** [comment]
@hero78 Please rebase and squash your commits!

**Comment by hero78** [comment]
@adamsaghy . Kindly review. I have fixed the issues.
Thanks

**Review by adamsaghy — APPROVED** [review]
LGTM

**Comment by adamsaghy** [comment]
@hero78 Please fix the conflict and check why the tests were failing!

**Pull request closed without merging**
