### PR TITLE
FINERACT-1414 :Added subEntityType in global search result

### PR DESCRIPTION
**Pull request by sheminanto**
## Description

Added sub entity type in global search result in order to view fixeddeposit, savings, recurring deposit in their corresponding pages.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by awasum** [comment]
Hello @sheminanto .. one tests is failing.. Please can you help fix it so Travis can pass? https://app.travis-ci.com/github/apache/fineract/builds/240240273

**Comment by awasum** [comment]
Travis is refusing to run. @IOhacker , @ptuomola any ideas?

**Comment by awasum** [comment]
Please, dont merge this.. Tests have not passed.

**Comment by IOhacker** [comment]
Now checking

**Comment by IOhacker** [comment]
Adding travis_wait variable to SonarQube analysis (FINERACT-1409)

https://github.com/apache/fineract/pull/1922

**Comment by IOhacker** [comment]
Hello,

Now the building is completed. I will check the message about the SonarQube
Analysis about this message:

Quality Gate failed


[image: Failed condition]
<https://sonarcloud.io/dashboard?id=apache_fineract&branch=develop> [image:
0.0%] <https://sonarcloud.io/dashboard?id=apache_fineract&branch=develop> 0.0%
Security Hotspots Reviewed on New Code (is less than 100%)
[image: Failed condition]
<https://sonarcloud.io/dashboard?id=apache_fineract&branch=develop> [image:
0.0%] <https://sonarcloud.io/dashboard?id=apache_fineract&branch=develop> 0.0%
Coverage on New Code (is less than 80%)

**Comment by ptuomola** [comment]
> Travis is refusing to run. @IOhacker , @ptuomola any ideas?

There was a problem earlier with Apache's account with Travis - some quota exceeded. Let me try to close/reopen to see if it works now.

**Comment by ptuomola** [comment]
Ok now a Travis build got triggered. Let's see if it succeeds.

**Comment by awasum** [comment]
Travis taking 84 minutes to build or is it counting queue period? Or did I misunderstand?

**Comment by awasum** [comment]
I wonder if there is a test for Global search? @sheminanto  will you like to add one?

**Review by awasum — APPROVED** [review]
LGTM. 

Does this look Ok to you? @ptuomola , @IOhacker , @avikganguly01 

@ptuomola merge if it looks Ok to you.

**Review by ptuomola — APPROVED** [review]
LGTM

**Comment by awasum** [comment]
Closing JIRA issue as this has been merged: https://issues.apache.org/jira/browse/FINERACT-1414
Thank you @sheminanto  for the fix.

**Pull request merged**
