### PR TITLE
Creditbureau configuration module

### PR DESCRIPTION
**Pull request by nikpawar89**
This PR contains code for creditbureau configuration

### CODE REVIEW

**Comment by nazeer1100126** [comment]
@nikpawar89 Please follow coding style defined by https://google.github.io/styleguide/javaguide.html

**Comment by nazeer1100126** [comment]
@nikpawar89 Please let me know whether I understood correctly. With this implementation, I can define credit bureau, credit bureau products and map them to a loan product. So where is actual credit bureau high level check implementation so that anybody can attach specific provider implementation?

**Comment by nikpawar89** [comment]
@nazeer1100126  This module is intended for configuring the credit bureau. Once the credit bureau is mapped to a specific loan product, i'll be using this configuration to map the credit check request with specific credit bureau.The code for mapping credit check with credit bureau is not included in this module, it will be included with each specific implementation of the credit bureau in CreditBureauConfigurationAPI.java

**Comment by nikpawar89** [comment]
reponening

**Pull request closed without merging**
