### PR TITLE
Limit fineract-client to Java 8 not 11 (FINERACT-1214)

### PR DESCRIPTION
**Pull request by vorburger**
see discussion in FINERACT-1214

### CODE REVIEW

**Comment by vorburger** [comment]
@vidakovic as per our discussion on JIRA... LGTY like this? Merge?

**Review by vidakovic — APPROVED** [review]
Perfect :-)

**Comment by vorburger** [comment]
> Perfect :-)

OK, so... do you want to merge this? :smile:

**Comment by vorburger** [comment]
More generally, as a committer, please don't be shy to merge more PRs! Watch the Repo, jump on stuff - e.g. [those from renovate-bot - all yours if they LGTY](https://github.com/apache/fineract/pulls/renovate-bot)! :smile_cat: Likewise, if I tag you as the only Reviewer, if it's fine for you, and passed the build - just merge it! :smiling_imp:

**Comment by vidakovic** [comment]
Will do... here: just waited for the build to finish ;-)

**Pull request merged**
