### PR TITLE
FINERACT-470 (436) Fixed CWE582,CWE607 security issues in account and infrastructure modules

### PR DESCRIPTION
**Pull request by ThisuraThejith**
Completed the sonar fixes in FINERATC-436.
Plese refer the doc at https://docs.google.com/spreadsheets/d/1uLk3YPcjnXk7RqF8etsTzIuN59CDU6sgBxpZul__1V4/edit?usp=sharing for details.

This PR is connected with https://github.com/apache/fineract/pull/343

### CODE REVIEW

**Comment by nazeer1100126** [comment]
@ThisuraThejith Changes are OK.

**Comment by ThisuraThejith** [comment]
Thank you very much @nazeer1100126. Based on the feedback from Mark, it seems adding new constant classes isn't a problem at this stage. I am working on that at the moment. What is your idea about that?

**Comment by ThisuraThejith** [comment]
@nazeer1100126 I have updated the PR adding three new constant classes. Can you please review it.

**Comment by ThisuraThejith** [comment]
@nazeer1100126 There were few merge conflicts due to the commit f537bae699d51593d05fa43e52734e36d3568146. 

Could you please review this and merge?

**Comment by nazeer1100126** [comment]
@ThisuraThejith thank you. Please make sure to send PR with single commit from next time :-)

**Comment by ThisuraThejith** [comment]
@nazeer1100126 Thank you nazeer. Sure will do.

**Pull request merged**
