### PR TITLE
Notification sub-system

### PR DESCRIPTION
**Pull request by cnangeh**
Work done:

- [x] User subscription to topic on user creation
- [x] Topic creation on entity creation
- [x] Upgrade process of user notification
- [x] Migration script - topic, topic subscription models for new and already existing users and entities
- [x] Update user subscription on user transfer and/or update of user's permission
- [x] Update topic details when entity details updates
- [x] Update topic details when member type are updated at the system level
- [x] Unit test topic-subscriber model

### CODE REVIEW

**Comment by nazeer1100126** [comment]
@Anh3h Can you share me the requirements/use cases so that it will be helpful while reviewing the code.
It's better to create a jira issue and put all the details.

**Comment by cnangeh** [comment]
Ok. Will do that

On Sep 22, 2017 11:44 AM, "Shaik Nazeer Hussain" <notifications@github.com>
wrote:

@Anh3h <https://github.com/anh3h> Can you share me the requirements/use
cases so that it will be helpful while reviewing the code.
It's better to create a jira issue and put all the details.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apache/fineract/pull/405#issuecomment-331414438>, or mute
the thread

**Comment by cnangeh** [comment]
Hi @nazeer1100126 sorry for the delayed reply, my computer crashed so I needed some time to bring back to life :). Here is the issue I created https://issues.apache.org/jira/browse/FINERACT-527

**Comment by avikganguly01** [comment]
Hi @Anh3h , would it be possible for you to update Fineract-527 with detailed test cases so that it can be manually tested in absence of integration / e2e tests?

**Comment by cnangeh** [comment]
OKay

**Comment by cnangeh** [comment]
Hi @avikganguly01, to manually test the system,  you can follow the sample use case i stated. but the steps differ slightly for difference events like:

New Client Created
New Loan Created
New Loan Approved
New Share Account Created
New Share Account Approved
New Savings Account Created
New Savings Account Approved
New Fixed Deposit Account Created

**Pull request closed without merging**
