### PR TITLE
FINERACT-1322 - Add Support for a Bi Monthly Loan Product

### PR DESCRIPTION
**Pull request by xurror**
https://issues.apache.org/jira/browse/FINERACT-1322

There's also some published documents on the changes done here at:
http://research.muellners.org/implementing-a-bi-monthly-loan-product/
http://research.muellners.org/holiday-rescheduling/

There is also an extensive video documentation covering 18 test combinations of this module you can find on YouTube here:
https://www.youtube.com/playlist?list=PLeYrfyYpmjaR9TylGfvj6TpUO_fAhDXuN

### CODE REVIEW

**Comment by edcable** [comment]
@xurror great to see the contribution from the Muellners team. Thank you for thoroughly documenting the changes, how to use the new feature, and sharing the testing that was done. I'm going to reach out to one of our more experienced developers with deep knowledge of both the domain and the code base to do the review of the code. Do you have a demo server we could access to do some functional testing as well?

Have you opened up a pull request for the UI changes to the community app? you likely also haven't done this but when you have the time could you create the corresponding changes for the new web app UI. We are planning to release that soon as the community app will be phased out by mid year.

**Comment by xurror** [comment]
> @xurror great to see the contribution from the Muellners team. Thank you for thoroughly documenting the changes, how to use the new feature, and sharing the testing that was done. I'm going to reach out to one of our more experienced developers with deep knowledge of both the domain and the code base to do the review of the code. Do you have a demo server we could access to do some functional testing as well?

Thanks, Ankit will provide access to the demo server.

> Have you opened up a pull request for the UI changes to the community app? you likely also haven't done this but when you have the time could you create the corresponding changes for the new web app UI. We are planning to release that soon as the community app will be phased out by mid year.

The community app changes will be up soon like within the week.
As for the new web app, I'll try to bring up the changes there in the next couple of weeks at best.

**Comment by xurror** [comment]
Community-app PR: https://github.com/openMF/community-app/pull/3351

**Comment by bharathcgowda** [comment]
Hi @xurror  @edcable 
Very pleased to have this addition to our loan module as it had been one of the most asked configurations by MFIs and other organizations.

Did one round of high-level testing by taking the branch https://github.com/muellners/fineract/tree/rebase-semi
and was happy with the schedule for the 'same as repayment' configuration.

However, below are few observations that I found out, I hope it helps in improving this feature

1. Modify of loan account is not working  with 'semi month' configuration
ERROR:- " field is required Loan term frequency period type must match that of repayment frequency period type. -"

2. First date and last date tooltip is showing wrong info
- minor issue, but could be misleading for initial users during configuration

3. Loan creation fails when 'First' and 'Last dates' are not mentioned at the product level, However, those fields are not mandatory to add at the Product level.
- If we create the loan product without adding 'First' and 'Last dates', we cannot create a loan application

4. Validation for "Repaid Every" Number field. when 'Semi month' is selected
Right now we can select 1 semi month, 3 semi month etc, which intern affecting the logic of loan term and number of repayments

For example
If we set "loan term" as 10 months
and "repaid every" as 3 semi months
"No of repayments" will be set to 30 instalments.
Because of 'semi month' configuration, there would be 30 instalments for loan spread across 15 months.
So this breaks the existing logic of  "loan term"  = "No of repayments"/"repaid every" 

We understand that user should know that semi months constitutes to 2 instalments per month, hence the number field should be frozen to 2 of "repaid every" when "semi month" is selected.

5. System doesn't allow to create loans with disbursement date greater than the first date set at the loan product level
- for example, if we set the first date as 5th may 2021, the system doesn't allow to create a loan with disbursement date greater than 5th May 2021

6. The start date acts as a first repayment date, meaning even if we give the disbursement date as 1st Jan 2021, the system will still consider 5th may as the First repayment date(unless we specify the FRD while creating the loan application).
Ideally, the system should follow instalments as per the frequency set

7. No option to change 'first date' and 'last date' at the loan account level, 5th and 6th issues are only because of configuration present only at the product level.

8. Interest portion is all zero when we set the interest calculation to 'daily' or 'same as repayment' with' Calculate interest for exact days in partial period' enabled
- not sure if this is a bug or all the types have not been covered, as of now, system is not calculating interest when interest calculation to 'daily' or 'same as repayment' with' Calculate interest for exact days in partial period' enabled
Please feel free to reach out to me if you need any clarification on any point, I'll be happy to help in ggt
- 
image

**Comment by xurror** [comment]
Thanks for the very in-depth review @bharathcgowda.
I'll look into this as soon as possible and make the appropriate adjustments.

**Comment by awasum** [comment]
Hey....Is this something you can still adjust and make a PR for? @xurror  this is valuable work and if you can adjust abit...this can be merged soonest. Thanks...

**Comment by xurror** [comment]
This piece of work was taken over by developers at Muellners after I left the organisation and was no longer actively involved in its development. They have probably done some additional development to it.

I see they opened a new pull request here for it: https://github.com/apache/fineract/pull/1884

@ankit can you maybe provide additional feedback on the progress of this effort?

**Pull request closed without merging**
