### PR TITLE
make SimpleDateFormat use in ApiParameterError thread-safe [FINERACT-1063]

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-1063

### CODE REVIEW

**Comment by vorburger** [comment]
@ptuomola would you like to code review this PR? Make sense and actually fixes a potential concurrency issue - agreed?

**Comment by ptuomola** [comment]
@vorburger makes sense and definitely the right thing to do in my view...

**Comment by vorburger** [comment]
Test Failure just due to FINERACT-1016.

**Pull request merged**
