### PR TITLE
 un-static-ify SchedulerJobHelper

### PR DESCRIPTION
**Pull request by vorburger**
TODO Un-Draft and rebase once other issues in SchedulerJobHelper are solved, and tests un-ignored

re. FINERACT-922

### CODE REVIEW

**Comment by vorburger** [comment]
Most of this is now in #809 #811 #814 - I'll hold this, and rebase it once those are in.

**Comment by awasum** [comment]
Ok...It all looks good. Why is the other one #814  failing.... its just weird

**Comment by vorburger** [comment]
I've actually done most of what was in this PR was actually done in other PRs meanwwhile, but there were 2 very small changes left here after we re-base which we could still merge (very minor).

**Comment by vorburger** [comment]
Actually, what little is left here now (just removing x2 `static`) will contradict https://errorprone.info/bugpattern/MethodCanBeStatic which I'm assuming (hoping) @percyashu will shortly be adding, so let me abandon this PR instead of merging this.

**Pull request closed without merging**
