### PR TITLE
FINERACT-976 : Client date of birth can not be greater than the client submitted on date

### PR DESCRIPTION
**Pull request by kiran-vsm**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vorburger** [comment]
Checkstyle failed, you can run it locally and fix it.

**Comment by vorburger** [comment]
Dear first time contributor,

Welcome to Apache Fineract!!

Have you read https://github.com/apache/fineract/#pull-requests?

Already subscribed to our mailing list, by sending an (empty) email to dev-subscribe@fineract.apache.org?

Created your JIRA account on https://issues.apache.org/jira/projects/FINERACT/?

Played with our server at https://www.fineract.dev?

We're very excited to have you onboard contributing.

**Comment by awasum** [comment]
@kiran-vsm . Do you want to address the feedback given to your by fixing the issue and making Travis show green? Do you have a specific problem blocking you ? This will be a valuable contribution?

**Comment by kiran-vsm** [comment]
@vorburger: Thanks for your above guidelines.
Corrected Checkstyle issues and re-sent the PR. 
Please check it.

**Review by vorburger — APPROVED** [review]
LGTM

**Comment by vorburger** [comment]
@kiran-vsm please make more contributions!! :-)

**Pull request merged**
