### PR TITLE
re-activate unit tests (see FINERACT-776)

### PR DESCRIPTION
**Pull request by vorburger**
https://issues.apache.org/jira/browse/FINERACT-776

### CODE REVIEW

**Comment by vorburger** [comment]
@conradsp @vishwasbabu @ShruthiRajaram @awasum @Anh3h could anyone review and merge this one? Tx!

**Comment by vorburger** [comment]
@awasum want to review this one, and merge it if it seems fine to you? (There's always `git revert`.)

**Comment by awasum** [comment]
On it... @vorburger

**Comment by awasum** [comment]
LGTM..merging..

**Pull request merged**
