### PR TITLE
Add missing test coverage for Image 404 (FINERACT-1201)

### PR DESCRIPTION
**Pull request by vorburger**
This adds missing regression test coverage for what PR #1426 changes.

part of FINERACT-1201

### CODE REVIEW

**Comment by vorburger** [comment]
@vidakovic would you be willing to review this trivial PR from me, and merge it if you LGTM? Thank You!

**Comment by vidakovic** [comment]
@vorburger will do as soon as I'm back at my desk

**Review by ptuomola — APPROVED** [review]
LGTM

**Review by vidakovic — APPROVED** [review]
LGTM

**Pull request merged**
