### PR TITLE
Mustache template added to modify the generated code (FINERACT-1356)

### PR DESCRIPTION
**Pull request by danishjamal104**
## Description

Since the generated sdk uses custom services and utils file, the `http-logging` library is missing in` pom.xml` which is used in `FineractClient.java`, also `Parts,java` uses `4.9.0` version of `okhttp3` library where as open api generator uses older version throwing an error in `RequestBody.create()` function since its older version is now deprecated, hence their are two major changes in generated `build.gradle` and `pom.xml`. 
For default template file refer [build.gradle.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache) and [pom.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/pom.mustache)

Ignore if these details are present on the associated [FINERACT-1356](https://issues.apache.org/jira/browse/FINERACT-1356).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by danishjamal104** [comment]
I am working on it.

Regards,
Danish Jamal

**Comment by danishjamal104** [comment]
> This pull request seems to be stale. Are you still planning to work on it? We will automatically close it in 30 days.

I have send a PR, waiting for reviews.

**Review by iamsh4shank — APPROVED** [review]

**Comment by ptuomola** [comment]
LGTM... need to check why the build is failing and fix

**Comment by BLasan** [comment]
Hi @danishjamal104 , could you please resolve the issues in travis CI build?

```
1 warning
/home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/services/DocumentsApiFixed.java:36: error: duplicate class: org.apache.fineract.client.services.DocumentsApiFixed
public interface DocumentsApiFixed {
       ^
/home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/services/ImagesApi.java:37: error: duplicate class: org.apache.fineract.client.services.ImagesApi
public interface ImagesApi {
       ^
/home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/services/RunReportsApi.java:29: error: duplicate class: org.apache.fineract.client.services.RunReportsApi
public interface RunReportsApi {
       ^
/home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/FineractClient.java:151: error: duplicate class: org.apache.fineract.client.util.FineractClient
public final class FineractClient {
             ^
/home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/Calls.java:30: error: duplicate class: org.apache.fineract.client.util.Calls
public final class Calls {
             ^
/home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/JSON.java:48: error: duplicate class: org.apache.fineract.client.util.JSON
class JSON {
^
/home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/CallFailedRuntimeException.java:30: error: duplicate class: org.apache.fineract.client.util.CallFailedRuntimeException
public class CallFailedRuntimeException extends RuntimeException {
       ^
/home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/Parts.java:40: error: duplicate class: org.apache.fineract.client.util.Parts
public final class Parts {
             ^
/home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/auth/OAuthOkHttpClient.java:71: warning: [deprecation] create(MediaType,String) in RequestBody has been deprecated
        RequestBody body = request.getBody() != null ? RequestBody.create(mediaType, request.getBody()) : null;
                                                                  ^
8 errors
1 warning
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':fineract-client:rat'.
> A failure occurred while executing org.nosphere.apache.rat.RatWork
   > Apache Rat audit failure - 2 unapproved licenses
     	See file:///home/travis/build/apache/fineract/fineract-client/build/reports/rat/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':fineract-client:compileJava'.
> Compilation failed; see the compiler error output for details.
```

**Comment by danishjamal104** [comment]
> Hi @danishjamal104 , could you please resolve the issues in travis CI build?
> 
> ```
> 1 warning
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/services/DocumentsApiFixed.java:36: error: duplicate class: org.apache.fineract.client.services.DocumentsApiFixed
> public interface DocumentsApiFixed {
>        ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/services/ImagesApi.java:37: error: duplicate class: org.apache.fineract.client.services.ImagesApi
> public interface ImagesApi {
>        ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/services/RunReportsApi.java:29: error: duplicate class: org.apache.fineract.client.services.RunReportsApi
> public interface RunReportsApi {
>        ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/FineractClient.java:151: error: duplicate class: org.apache.fineract.client.util.FineractClient
> public final class FineractClient {
>              ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/Calls.java:30: error: duplicate class: org.apache.fineract.client.util.Calls
> public final class Calls {
>              ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/JSON.java:48: error: duplicate class: org.apache.fineract.client.util.JSON
> class JSON {
> ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/CallFailedRuntimeException.java:30: error: duplicate class: org.apache.fineract.client.util.CallFailedRuntimeException
> public class CallFailedRuntimeException extends RuntimeException {
>        ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/Parts.java:40: error: duplicate class: org.apache.fineract.client.util.Parts
> public final class Parts {
>              ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/auth/OAuthOkHttpClient.java:71: warning: [deprecation] create(MediaType,String) in RequestBody has been deprecated
>         RequestBody body = request.getBody() != null ? RequestBody.create(mediaType, request.getBody()) : null;
>                                                                   ^
> 8 errors
> 1 warning
> FAILURE: Build completed with 2 failures.
> 1: Task failed with an exception.
> -----------
> * What went wrong:
> Execution failed for task ':fineract-client:rat'.
> > A failure occurred while executing org.nosphere.apache.rat.RatWork
>    > Apache Rat audit failure - 2 unapproved licenses
>      	See file:///home/travis/build/apache/fineract/fineract-client/build/reports/rat/index.html
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> ==============================================================================
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> Execution failed for task ':fineract-client:compileJava'.
> > Compilation failed; see the compiler error output for details.
> ```

I have fixed the 'RAT' error which was due to licensing issue. But the present error is unavoidable since it is due to duplicate class. Because fineract client generates the SDK in build folder and some replaceable files are automatically moved in their which also reside in src folder of fineract-client.

**Comment by danishjamal104** [comment]
Ill add comment in `build.gradle`.

**Comment by danishjamal104** [comment]
> Hi @danishjamal104 , could you please resolve the issues in travis CI build?
> 
> ```
> 1 warning
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/services/DocumentsApiFixed.java:36: error: duplicate class: org.apache.fineract.client.services.DocumentsApiFixed
> public interface DocumentsApiFixed {
>        ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/services/ImagesApi.java:37: error: duplicate class: org.apache.fineract.client.services.ImagesApi
> public interface ImagesApi {
>        ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/services/RunReportsApi.java:29: error: duplicate class: org.apache.fineract.client.services.RunReportsApi
> public interface RunReportsApi {
>        ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/FineractClient.java:151: error: duplicate class: org.apache.fineract.client.util.FineractClient
> public final class FineractClient {
>              ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/Calls.java:30: error: duplicate class: org.apache.fineract.client.util.Calls
> public final class Calls {
>              ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/JSON.java:48: error: duplicate class: org.apache.fineract.client.util.JSON
> class JSON {
> ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/CallFailedRuntimeException.java:30: error: duplicate class: org.apache.fineract.client.util.CallFailedRuntimeException
> public class CallFailedRuntimeException extends RuntimeException {
>        ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/util/Parts.java:40: error: duplicate class: org.apache.fineract.client.util.Parts
> public final class Parts {
>              ^
> /home/travis/build/apache/fineract/fineract-client/build/generated/java/src/main/java/org/apache/fineract/client/auth/OAuthOkHttpClient.java:71: warning: [deprecation] create(MediaType,String) in RequestBody has been deprecated
>         RequestBody body = request.getBody() != null ? RequestBody.create(mediaType, request.getBody()) : null;
>                                                                   ^
> 8 errors
> 1 warning
> FAILURE: Build completed with 2 failures.
> 1: Task failed with an exception.
> -----------
> * What went wrong:
> Execution failed for task ':fineract-client:rat'.
> > A failure occurred while executing org.nosphere.apache.rat.RatWork
>    > Apache Rat audit failure - 2 unapproved licenses
>      	See file:///home/travis/build/apache/fineract/fineract-client/build/reports/rat/index.html
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> ==============================================================================
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> Execution failed for task ':fineract-client:compileJava'.
> > Compilation failed; see the compiler error output for details.
> ```

done please merge now. Thanks

**Review by BLasan — APPROVED** [review]
LGTM!

**Comment by BLasan** [comment]
@ptuomola Build is passing now

**Pull request merged**
