### PR TITLE
Transfer Funds from Savings to Share

### PR DESCRIPTION
**Pull request by BLasan**
## Description

See [Issue-791](https://issues.apache.org/jira/browse/FINERACT-791)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by BLasan** [comment]
@thesmallstar Please review :)

**Comment by BLasan** [comment]
@thesmallstar Please review

**Comment by BLasan** [comment]
> This pull request seems to be stale. Are you still planning to work on it? We will automatically close it in 30 days.

Need a review

**Review by ptuomola — APPROVED** [review]
LGTM

**Comment by ptuomola** [comment]
HI @BLasan  - code looks good, but there's a merge conflict and the build was failing. Would you be able to sort these out, and squash the commits please - and we can then merge this. Thanks!

**Comment by BLasan** [comment]
> HI @BLasan - code looks good, but there's a merge conflict and the build was failing. Would you be able to sort these out, and squash the commits please - and we can then merge this. Thanks!

I'll do the refinements. Thanks :) Will you be able to review the post dated checks PR as well?

**Comment by BLasan** [comment]
Hi @ptuomola, there's an issue related to the changes I've made. `Too many tables; MySQL can only use 61 tables in a join`. Only added an additional column to keep track of share account in transactions. Do we need to move that implementation to a separate table? Or do you have any suggestion to avoid that issue? I was not able to come up with an answer for that after doing numerous investigations.

**Comment by awasum** [comment]
Is there a unit test for this feature? Seems this has conflicts now...

**Comment by BLasan** [comment]
> Is there a unit test for this feature? Seems this has conflicts now...

I'll update the PR soon. Found a way to avoid this `mysql join` issue.

**Review by avikganguly01 — CHANGES_REQUESTED** [review]
PR looks good.
Please include an integration test. 
Unnecessary migration script renames are there.

**Comment by BLasan** [comment]
> PR looks good. Please include an integration test. Unnecessary migration script renames are there.

There's a `mysql join table issue (61 tables)` which is not allowed. This occurs when running the integration tests. Functional wise, it worked.

**Comment by BLasan** [comment]
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.authenticationManager': Cannot resolve reference to bean 'customAuthenticationProvider' while setting constructor argument with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customAuthenticationProvider' defined in URL [file:/home/benura/Desktop/fineract/fineract-provider/build/classes/java/main/META-INF/spring/securityContext.xml]: Cannot resolve reference to bean 'userDetailsService' while setting bean property 'userDetailsService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsService': Unsatisfied dependency expressed through field 'platformUserRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appUserRepository' defined in org.apache.fineract.useradministration.domain.AppUserRepository defined in : Cannot create inner bean '(inner bean)#a120b9' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#a120b9': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tenantDatabaseUpgradeService' defined in file [/home/benura/Desktop/fineract/fineract-provider/build/classes/java/main/org/apache/fineract/infrastructure/core/service/TenantDatabaseUpgradeService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdbcTenantDetailsService' defined in file [/home/benura/Desktop/fineract/fineract-provider/build/classes/java/main/org/apache/fineract/infrastructure/security/service/JdbcTenantDetailsService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hikariTenantDataSource' defined in URL [file:/home/benura/Desktop/fineract/fineract-provider/build/classes/java/main/META-INF/spring/hikariDataSource.xml]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Constructor threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect: Connection refused
```
I'm getting this error when running the PR now. Earlier it was working fine

**Comment by ptuomola** [comment]
Is your database up and working? The below suggests that the server can’t
connect to the database.

**Comment by ptuomola** [comment]
Seeing if I can retrigger the build to see if it passes...

**Pull request closed without merging**
