### PR TITLE
ignore StorageTest [FINERACT-828]

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-828

### CODE REVIEW

**Comment by vorburger** [comment]
@awasum @xurror merge? Unless you're motivated to fix `StorageTest`... I'm giving up on it! :smile:

**Comment by xurror** [comment]
I just don't get the thing with the storageTest. Seems to be some inconsistences only funny part is these inconsistences does not happen all the time.

**Comment by xurror** [comment]
I'm merging this

**Pull request merged**
