### PR TITLE
remove broken dev-dependencies.gradle (until FINERACT-939)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-939

### CODE REVIEW

**Comment by vorburger** [comment]
@nemux while you work on #828 how about this PR for now, does this LGTY, just to avoid confusion in the short term?

@awasum @xurror @ptuomola no objections from you I assume - OK to merge?

**Comment by xurror** [comment]
@vorburger, build is still failing here.

**Comment by vorburger** [comment]
> @vorburger, build is still failing here.

it's FINERACT-828 (StorageTest) again... I've self merged #858 and will rebase this one now.

**Comment by vorburger** [comment]
/rebase

_see FINERACT-829 re. `/rebase`_

**Comment by ptuomola** [comment]
Looks good to me!

**Pull request merged**
