### PR TITLE
Consolidating changes: Bulk import-fixing importhandler integration t…

### PR DESCRIPTION
**Pull request by wkk91193**
Opening a new PR  for #444 changes.

### CODE REVIEW

**Comment by vishwasbabu** [comment]
Looks good @wkk91193! Can you please remove the ignore annotation from all 4 test cases, so that Travis can confirm that they are passing ? (I had added the same earlier to get Travis to run, see https://github.com/apache/fineract/blob/c01b2770fba0f7f45709308e48d6993c7ba5ec63/fineract-provider/src/integrationTest/java/org/apache/fineract/integrationtests/bulkimport/importhandler/client/ClientEntityImportHandlerTest.java#L63 )

**Comment by wkk91193** [comment]
@vishwasbabu  Removed the Ignore annotation,code updated

**Review by vishwasbabu — CHANGES_REQUESTED** [review]
@wkk91193 : Integration tests on Travis are failing.

Related error logs

`[1m> Building 95% > :integrationTest > 171 tests completed, 8 skipped[22m[66D[0K01:14:58.826 [http-bio-8443-exec-123] INFO  o.a.f.i.s.f.TenantAwareBasicAuthenticationFilter - {"startTime":1550864698305,"totalTime":521,"method":"POST","url":"https://localhost:8443/fineract-provider/api/v1/savingsaccounts/uploadtemplate","parameters":{"legalFormType":[""],"tenantIdentifier":["default"]}}
[1m> Building 95% > :integrationTest > 171 tests completed, 8 skipped[22m[66D[0K01:14:58.903 [http-bio-8443-exec-137] INFO  o.a.f.i.s.f.TenantAwareBasicAuthenticationFilter - {"startTime":1550864698893,"totalTime":10,"method":"POST","url":"https://localhost:8443/fineract-provider/api/v1/authentication","parameters":{"username":["mifos"],"tenantIdentifier":["default"]}}
[1m> Building 95% > :integrationTest > 171 tests completed, 8 skipped[22m[66D[0K
[1m> Building 95% > :integrationTest > 171 tests completed, 8 skipped[22m[66D[0Korg.apache.fineract.integrationtests.bulkimport.importhandler.savings.SavingsImportHandlerTest > testSavingsImport 
[1m> Building 95% > :integrationTest > 171 tests completed, 8 skipped[22m[66D[0K[1A[115C[31mFAILED[39m
[1m> Building 95% > :integrationTest > 171 tests completed, 8 skipped[22m[66D[0K[1A[121C
[1m> Building 95% > :integrationTest > 171 tests completed, 8 skipped[22m[66D[0K    java.lang.AssertionError at SavingsImportHandlerTest.java:139`

and

`[1m> Building 95% > :integrationTest > 174 tests completed, 1 failed, 8 skipped[22m[76D[0Korg.apache.fineract.integrationtests.bulkimport.importhandler.loan.LoanImportHandlerTest > testLoanImport 
[1m> Building 95% > :integrationTest > 174 tests completed, 1 failed, 8 skipped[22m[76D[0K[1A[106C[31mFAILED[39m
[1m> Building 95% > :integrationTest > 174 tests completed, 1 failed, 8 skipped[22m[76D[0K[1A[112C
[1m> Building 95% > :integrationTest > 174 tests completed, 1 failed, 8 skipped[22m[76D[0K    java.lang.NullPointerException at LoanImportHandlerTest.java:126`

Please refer https://travis-ci.org/apache/fineract/builds/504533703?utm_source=github_status&utm_medium=notification for additional details

**Review by vishwasbabu — CHANGES_REQUESTED** [review]
@wkk91193 . The current failures on travis are

`
[1m> Building 95% > :integrationTest > 171 tests completed, 8 skipped[22m[66D[0K[1A[115C[31mFAILED[39m
[1m> Building 95% > :integrationTest > 171 tests completed, 8 skipped[22m[66D[0K[1A[121C
[1m> Building 95% > :integrationTest > 171 tests completed, 8 skipped[22m[66D[0K    java.lang.AssertionError at SavingsImportHandlerTest.java:139
`

and

`
[1m> Building 95% > :integrationTest > 174 tests completed, 1 failed, 8 skipped[22m[76D[0K
[1m> Building 95% > :integrationTest > 174 tests completed, 1 failed, 8 skipped[22m[76D[0Korg.apache.fineract.integrationtests.bulkimport.importhandler.loan.LoanImportHandlerTest > testLoanImport 
[1m> Building 95% > :integrationTest > 174 tests completed, 1 failed, 8 skipped[22m[76D[0K[1A[106C[31mFAILED[39m
[1m> Building 95% > :integrationTest > 174 tests completed, 1 failed, 8 skipped[22m[76D[0K[1A[112C
[1m> Building 95% > :integrationTest > 174 tests completed, 1 failed, 8 skipped[22m[76D[0K    java.lang.NullPointerException at LoanImportHandlerTest.java:126
`

**Comment by edcable** [comment]
@wkk91193 can you address the latest feedback that Vishwas provided?

**Comment by vorburger** [comment]
Let's close this now, just to have less open PRs; you can open a new PR with this when you resolved the feedback and conflicts.

**Pull request closed without merging**
