### PR TITLE
FINERACT-614: Rates Module

### PR DESCRIPTION
**Pull request by angelboxes**
## Description
This is a follow up for [Pull Request 465 ](https://github.com/apache/fineract/pull/465)

This pull requests add a new rates module which allows you to set an interest rate composed by multiple  existing rates. This feature is made to be used along with Mifos frontend and only available if rates module is enabled in configuration

This pull request also contains the changes requested for issues FINERACT-735, FINERACT-736, FINERACT-737.

Any feedback or suggestion regarding this issue is welcomed and I would appreciate your reviews.

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by awasum** [comment]
@vishwasbabu , @vorburger 

What needs to be done to merge this. I dont understand the use case.

Will there be a problem if @angelboxes  merges this?

@angelboxes  is there a UI or Doc for this which one can look and see how to use the feature and review?

**Comment by angelboxes** [comment]
> @vishwasbabu , @vorburger
> 
> What needs to be done to merge this. I dont understand the use case.
> 
> Will there be a problem if @angelboxes merges this?
> 
> @angelboxes is there a UI or Doc for this which one can look and see how to use the feature and review?

Hi @awasum I opened this pull request as a follow up for [Pull Request 465 ](https://github.com/apache/fineract/pull/465). You may get a bigger idea about this if you check that pull request. If you want a more detailed I may try to update it.

The general idea for the Rates Module is that rate amounts can be associated to a description and later be used to set the nominal interest rate used to create a loan.

For our business the nominal interest rate, is calculated by adding multiple rate previously defined, for example: let's say I have a specific rate for widowed people of 8%, a specific rate for college students of  7 % and a general rate for all of our clients of 6 % . When a widowed person comes and asks for a loan I may have choose the widowed rate and general rate to get the rate of  14%. These rates also help us restrict the interest amount that can be set when creating a new loan account beyond the min and max values.

This changes are mostly reflected in the Mifos UI because we didn't wanted to change a lot of how Fineract works actually. However the amount of files changed and added here may be overwhelming for some but all previous reviews have improved the idea we had initially about this module.

**Comment by vorburger** [comment]
@angelboxes I've just rebased this (merge commit), but unfortunately this now fails to build due to the recent Spring version upgrade ... That should be trivial to fix though, you will just need to replace `findOne()` with `findById(yourId).orElseThrow(() -> new SomeNotFoundException(YourId))`, see #653 and #642 for examples.

If you are still willing to do that, I'd be happy to merge this contribution ASAP (without further functional review). I'm sure you know what you are doing. Really sorry it took so long; as a community we should try to do better than this!

**Comment by angelboxes** [comment]
> @angelboxes I've just rebased this (merge commit), but unfortunately this now fails to build due to the recent Spring version upgrade ... That should be trivial to fix though, you will just need to replace `findOne()` with `findById(yourId).orElseThrow(() -> new SomeNotFoundException(YourId))`, see #653 and #642 for examples.
> 
> If you are still willing to do that, I'd be happy to merge this contribution ASAP (without further functional review). I'm sure you know what you are doing. Really sorry it took so long; as a community we should try to do better than this!

Ok, I will rebase the branch with dev. No problem

**Comment by vorburger** [comment]
> Ok, I will rebase the branch with dev. No problem

@angelboxes were you still planning to do that? Just asking. If not, would you like to close this one?

Once this doesn't have merge conflicts anymore and builds, we need to find someone who can do a functional verification. Could I suggest that you ask on the public mailing list asking who can review this for you?

**Comment by awasum** [comment]
@angelboxes , we now have spotbugs enabled for Fineract. So check to make sure your changes do not fail spotbug rules. See #670  #673 

Fineract has also been updated to use  recent spring boot version. So a few changes might be needed here too.

**Review by vorburger — APPROVED** [review]
While I am unable to fully review the "functional" aspect of this PR, it now LGTM from a more technical PoV - it now passed our build (thanks), includes an IT, and has nothing"shocking" in it me.

I'd like to finally merge this, unless anyone voices any objections. I'll post to the list about it, and give a 2 weeks deadline.

**Comment by vorburger** [comment]
Oh sh#% I should have squashed this before merging... it's "ugly" in the commit history, but too late; oh well, too bad, I'll remember next time. - Also I just noticed that this actually has a SpotBugs violation which now broke the build, but it's so trival I'll just go ahead and fix it in a new PR (instead of reverting).

**Pull request merged**
