### PR TITLE
Use environment variable for mysql server availability check in dockerfile entrypoint (FINERACT-1163)

### PR DESCRIPTION
**Pull request by phongnguyen-monex**
## Description
Get the database location from environment variable instead of using hardcoded values [FINERACT-1163](https://issues.apache.org/jira/browse/FINERACT-1163)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by ptuomola — APPROVED** [review]
LGTM

**Comment by ptuomola** [comment]
Change looks OK - let's see if integration test / build pass...

**Comment by IOhacker** [comment]
Hello, we got an issue in K8s while using the name of mysql in the script, I have removed this check in this PR   https://github.com/apache/fineract/pull/1944 delegating to Docker-Compose and K8s the control of the services

**Comment by phongnguyen-monex** [comment]
> Hello, we got an issue in K8s while using the name of mysql in the script, I have removed this check in this PR #1944 delegating to Docker-Compose and K8s the control of the services  

I think this is a better implementation, mine is just a quick fix. I'm closing this issue.

**Pull request closed without merging**
