### PR TITLE
Idempotency Support (FINERACT-1420)

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

This PR is being sent for the initial review of the proposal implementation documented in the FINERACT-1420 Jira Ticket. Only one class SavingsProductsApiResource.java has in the POST the proposed solution for accepting incoming x-idempotency-key headers.

I will be glad to hear for your opinions.

A more detailed information can be found here
https://docs.google.com/presentation/d/13lw2JqE9ujHVFwmynjJcVIUA3NfcDkbs729VLgadIXE/edit?usp=sharing

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [X] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [X] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by jdailey** [comment]
This looks like a good set of changes.  What is failing on the Travis CI?

**Comment by IOhacker** [comment]
Hello James,

It is queued, not running in TravisCI, waiting for the excution

https://app.travis-ci.com/github/apache/fineract/builds/241137906

**Comment by ptuomola** [comment]
There's a long execution queue in Apache's Travis account for the last
couple of days - so builds can take quite a while.

**Comment by awasum** [comment]
The commit history looks weird.. Seems you started implementing this change on a branch with was not upto date with Fineract upstream develop branch...

**Comment by awasum** [comment]
You will have to rebase this ontop of fineract develop and squash the commits..

**Comment by awasum** [comment]
I have seen something similar to this PR.. here: https://github.com/apache/fineract/pull/515
https://issues.apache.org/jira/browse/FINERACT-698, is there something we can learn from that ?

**Comment by ptuomola** [comment]
Rebased in #2000

**Pull request closed without merging**
