### PR TITLE
Update spring boot gradle plugin from v2.2.7 to v2.3.1.RELEASE

### PR DESCRIPTION
**Pull request by nnatarajan**
## Description
Extending #998

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by awasum** [comment]
@nnatarajan  you may want to look at this:

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#validation-starter-no-longer-included-in-web-starters
 https://github.com/spring-projects/spring-boot/issues/21465

Also assign this to yourself: https://jira.apache.org/jira/browse/FINERACT-1023

Keep up the good work.

**Comment by awasum** [comment]
From here: https://travis-ci.org/github/apache/fineract/builds/697503789

Looks like some unit tests are failing due to a bean not been created? I wonder what could be wrong here with this which was suppose to be a simple upgrade.

**Comment by nnatarajan** [comment]
@awasum , thank you for the feedback. I was discussing this one with Michael this morning. It does appears to require more research to resolve.

**Comment by awasum** [comment]
> @awasum , thank you for the feedback. I was discussing this one with Michael this morning. It does appears to require more research to resolve.

You are welcome. If possible bring back summaries which helps u solve this back here as comments so we can all learn from you all.

**Comment by nnatarajan** [comment]
@awasum , will do!

**Comment by awasum** [comment]
See: https://github.com/apache/fineract/pull/1146

**Pull request closed without merging**
