### PR TITLE
PRE_HOOK_TEST

### PR DESCRIPTION
**Pull request by maektwain**
## Description
This ensures a githook is installed while ./gradlew runs for the first time . This makes sure a pre-commit script to run integration and test tasks before we push , observing many PR failing not adhering the check style and test cases.

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by maektwain** [comment]
Pretty strange all tests were passing now it shows integration tests are failing.

**Comment by vorburger** [comment]
@maektwain following #764 and #761 this will pass the build (or not at least not fail because of integration tests) if you rebase this now.

**Comment by vorburger** [comment]
@maektwain  the (latest build of this) PR now fails due to https://issues.apache.org/jira/browse/FINERACT-899... do you know how we could fix that? A contribution from you for that would be really really really welcome!

This PR also has a weird Commit history... 12 commits, of which many which are already on develop now - I think something went wrong during your git rebase.. do you want to update this to have 1 clean commit only?

Once there is a clean diff, it will be easier to understand and review what this proposes. Would this cause EVERY git commit locally to run full integration tests? I'm not entirely sure yet if that is not too much. At least me I relatively often make small changes, and would want to be able to commit them without having to run full integration tests locally. I'm assuming that the problem you are trying to solve is the failing PRs on GitHub. But the reason for that, IMHO, isn't really that people don't run tests locally - I think they (mostly) do. What's really hurting us is are all the flaky test issues linked from https://issues.apache.org/jira/browse/FINERACT-850. If you really want to help and have an impact, we would love help to sort that out...

**Comment by maektwain** [comment]
I could add ignore which could be ignored for small tasks.

**Pull request closed without merging**
