### PR TITLE
FINERACT-2081: Update fineract.yml docker image ref

### PR DESCRIPTION
**Pull request by DavidLemayian**
## Description

Is this the correct image reference?

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by adamsaghy** [comment]
Hi

Would you mind to change the PR title and commit message to:
"FINERACT-2081: Update fineract.yml docker image ref" ?

Usually we are using this naming convention

**Comment by DavidLemayian** [comment]
Apologies, went into paternity leave and just got back. Will create a new pull request.

**Comment by adamsaghy** [comment]
> Apologies, went into paternity leave and just got back. Will create a new pull request.

Congratulations for the baby! :)

**Comment by DavidLemayian** [comment]
Thank you 😊

**Pull request closed without merging**
