### PR TITLE
FINERACT-1052 global configuration to enable or disable loan Over Pay…

### PR DESCRIPTION
**Pull request by francisguchie**
…ment

## Description
https://issues.apache.org/jira/browse/FINERACT-1052#

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by thesmallstar** [comment]
Failing due to spotless errors:
 Run './gradlew spotlessApply' to fix these violations.

**Comment by francisguchie** [comment]
@awasum  and @thesmallstar  

do i raise another PR for this ?  the failure is more than just the spotlessApply  i see non-used importations

**Comment by awasum** [comment]
Please clean up the commit history on this PR. Or better, jsut create a new fresh branch from latest develop branch and implement the solution from the start..so you have a clean history and not including commits which are already on develop branch. Do you understand me?

Have you tried to do a `git pull --rebase origin develop`, when you are on this feature branch? If the build on Travis is not green and git history is not clean, we cant even review the PR.

**Comment by francisguchie** [comment]
@awasum , i agree with you, but i will redo a new PR. I tried all the options you have suggested. let me close this PR and raise another one

**Comment by vorburger** [comment]
==> #1186

**Pull request closed without merging**
