### PR TITLE
FINERACT-1059 add payment Voucher and Description to PaymentDetails

### PR DESCRIPTION
**Pull request by francisguchie**
## Description
https://issues.apache.org/jira/browse/FINERACT-1059

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by awasum — CHANGES_REQUESTED** [review]
Run './gradlew :spotlessApply' to fix these violations. 

Also can we make these 2 new parameters optional?

Where is a voucherNumber coming from? Is it from an external system? or generated by Fineract?

**Comment by awasum** [comment]
@ptuomola and @vorburger , Will you like to also help review this? So that I dont miss something.

**Comment by awasum** [comment]
@francisguchie , Are you planning on implementing a corresponding UI for these changes?

**Comment by francisguchie** [comment]
> @francisguchie , Are you planning on implementing a corresponding UI for these changes?

Yes @awasum once it passes the fineract, i will definitely do that with no hesitation

**Comment by francisguchie** [comment]
> Run './gradlew :spotlessApply' to fix these violations.
> 
> Also can we make these 2 new parameters optional?
> 
> Where is a voucherNumber coming from? Is it from an external system? or generated by Fineract?

the voucher number and Payment description are coming from the users 
Not generated by the system

this can be the slip Number (deposit or withdraw or payment reciept) a good number of financial companies still maintian these slips for audit purposes

**Comment by ptuomola** [comment]
Just wondering: instead of adding new fields for these specific pieces of information (and then having to add more fields when there are other items that need to be captured) - would it make sense to use the Note API to add this information as a Note associated with the transaction? 

Looks like transactions on loans (and maybe savings?) already can have notes associated with them. But it should be trivial to support other types of transactions. And then the Notes could include any type of information...

**Comment by francisguchie** [comment]
> Just wondering: instead of adding new fields for these specific pieces of information (and then having to add more fields when there are other items that need to be captured) - would it make sense to use the Note API to add this information as a Note associated with the transaction?
> 
> Looks like transactions on loans (and maybe savings?) already can have notes associated with them. But it should be trivial to support other types of transactions. And then the Notes could include any type of information...

@ptuomola 
I like you comment this is a nice school of thought. 
However the Note is only on Loans at the moment. 
These are the areas where the voucher and description is needed. 
1- Client transactions
2- Savings Transactions
3- Fixed Deposits Transactions
4- Recurring Savings Transactions
I do buy the idea that we can use one filed for both the voucher and description like you suggested above. Most of the Mifos users i know are not using the Note field and thus it goes un-used in my case. What are the other users using this field for???

**Comment by francisguchie** [comment]
@awasum , @ptuomola  

i do think its better to use the Note as it is already available. and both the voucher and description can be placed in one entry. 

am pulling down this PR

**Comment by ptuomola** [comment]
Great! Always good to find more uses for existing APIs...

**Pull request closed without merging**
