### PR TITLE
EOY-Closure: FINERACT-38

### PR DESCRIPTION
**Pull request by ippezshelby**
@nazeer1100126 Could you please review this and @avikganguly01 or @edcable Could you please have the community-app side implementation for this or you could identify someone good at the front end implementation to have this done so that it could be shipped with the next release.

### CODE REVIEW

**Comment by ippezshelby** [comment]
I accidentally deleted my branch and didn't know it affects PR too but PR is re-opened so review can go on.

**Comment by avikganguly01** [comment]
@Ippezrobert : Can you fix the conflict and share the link regarding which ticket in JIRA this PR addresses?

**Comment by ippezshelby** [comment]
@avikganguly01 , Conflict Resolved so you can review and the ticket is https://issues.apache.org/jira/browse/FINERACT-38

**Review by raakeshtomarnew — COMMENTED** [review]
i will check

**Comment by ippezshelby** [comment]
@avikganguly01 , @ShruthiRajaram, @raakeshtomarnew, @nazeer1100126, Ed Cable and others, is it possible to review this and make it as part of the next release since people are nearing end of year where expenses and income have to be booked-off for beginning of year. The Front-end has not been developed so someone good at front-end dev can take on it. Thanks

**Comment by raakeshtomarnew** [comment]
yes
its useful.
Thanks

Rakesh Tomar

*Team Lead*

*8923306463*
*8859127643*
*EMail:-raakeshtomar@gmail.com <EMail%3A-raakeshtomar@gmail.com>*
*website:-www.bnkbiz.com <http://www.santoshfinlease.com>*

**Comment by vorburger** [comment]
@Ippezrobert thank you very much for your interest in Fineract/Mifos!  I'm an (old) volunteer who got reminded of Mifos/Fineract this week-end at the FOSDEM conference, and I'm taking a moment to help the project clean up some of it's old issues and pull requests etc.  

We were wondering whether you are still alive, and would be willing to rebase this PR and take any previous review feedback into account?  If we don't hear from you within 2 weeks, we will take the liberty to close this PR without merging it, to avoid confusion for future new contributors looking at this repository - hope you understand and that's fair.

/Cc FYI @apache/fineract-committers

**Comment by raakeshtomarnew** [comment]
SIR
I am very interested to use this feature
for this year end
please give some update before 31st march.

Thanks

Rakesh Tomar

*Team Lead*

*8923306463*
*8859127643*
*EMail:-raakeshtomar@gmail.com <EMail%3A-raakeshtomar@gmail.com>*
*website:-www.bnkbiz.com <http://www.santoshfinlease.com>*

**Comment by vorburger** [comment]
@raakeshtomarnew someone (not me..) needs to "own" this PR and rebase it - perhaps you want to?

**Comment by raakeshtomarnew** [comment]
yes
Thanks

Rakesh Tomar

*Team Lead*

*8923306463*
*8859127643*
*EMail:-raakeshtomar@gmail.com <EMail%3A-raakeshtomar@gmail.com>*
*website:-www.bnkbiz.com <http://www.santoshfinlease.com>*

**Review by raakeshtomarnew — COMMENTED** [review]
I will test this in this closing.

**Comment by badesemowo** [comment]
Hi, I thought to check if this was ever deployed to Fineract ?

**Comment by raakeshtomarnew** [comment]
yes
Thanks

Rakesh Tomar

*Team Lead*

*8923306463*
*8859127643*
*EMail:-raakeshtomar@gmail.com <EMail%3A-raakeshtomar@gmail.com>*
*website:-www.bnkbiz.com <http://www.santoshfinlease.com>*

**Comment by vorburger** [comment]
@Ippezrobert @badesemowo @raakeshtomarnew I'm currently doing a quick run of review on all open PRs, and was just wondering if you would still like to get this very old open one merged? 

If so, could you / someone who wants this please rebase it, so that we can see if it actually builds on Travis? (FYI when this PR was raised, this project did not have automated CI on Travis set up; but meanwhile it does.)

Without hearing back within let's say ... 1 month, I would be inclined to just close this (un-merged).

**Comment by raakeshtomarnew** [comment]
Sir
please not close
i m working on it.
Thanks

Rakesh Tomar

*Team Lead*

*8923306463*
*8859127643*
*EMail:-raakeshtomar@gmail.com <EMail%3A-raakeshtomar@gmail.com>*
*website:-www.bnkbiz.com <http://www.santoshfinlease.com>*

**Comment by vorburger** [comment]
Let's close this now, just to have less open PRs; you can open a new PR with this when you resolved the conflicts.

**Comment by MayaDuruva** [comment]
can you please any one tell me this changes working now?

Because this one is close now. But still fineract, mifos doesn't have this feature. I don't know how others using without EOY option. Because this one is mandatory for all.

**Comment by awasum** [comment]
> can you please any one tell me this changes working now?
> 
> Because this one is close now. But still fineract, mifos doesn't have this feature. I don't know how others using without EOY option. Because this one is mandatory for all.

It was closed and never merged..will you like to work on this @MayaDuruva ?  Then reopen this and fix the outstanding issues with it. Make sure Travis passes and comments above are resolved

**Comment by raakeshtomarnew** [comment]
i like to work on it.
Thanks

Rakesh Tomar

*Team Lead*

*8923306463*
*8859127643*
*EMail:-raakeshtomar@gmail.com <EMail%3A-raakeshtomar@gmail.com>*
*website:-www.bnkbiz.com <http://www.santoshfinlease.com>*

**Pull request closed without merging**
