### PR TITLE
FINERACT-910: Serving apiDocs as part of the fineract-provider

### PR DESCRIPTION
**Pull request by ptuomola**
## Description
Configured Spring Boot to serve /static and /public directories from the classpath, and moved apiDocs to /static directory so that it will be served. Removed existing serving of '/apps/**' from cwd as a) that did not seem to be used and b) could be a potential security risk. 

Updated pull request checklist template to reflect new location. 

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [X] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [X] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [X] Integration tests have been created/updated for verifying the changes made.

- [X] All Integrations tests are passing with the new commits.

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Review by vorburger — COMMENTED** [review]
@ptuomola Great, thanks! Small thing: Would you perhaps like to add a trivial new integration test here, doing GET /apiDocs/ asset 200 instead of 400, just to ensure future non-regression for this? Just a thought. 

PS: I'll review other PRs on coming days or weekend, when I have more time.

**Comment by ptuomola** [comment]
> @ptuomola Great, thanks! Small thing: Would you perhaps like to add a trivial new integration test here, doing GET /apiDocs/ asset 200 instead of 400, just to ensure future non-regression for this? Just a thought.

@vorburger Sounds good - will do this tomorrow!

**Comment by awasum** [comment]
Ping.. Whats left here maybe just the integration test otherwise everything looks great.

**Comment by ptuomola** [comment]
@awasum @vorburger I've added an integration test - so hopefully this is now good to go? Let me know if any other comments...

**Review by awasum — APPROVED** [review]
LGTM. @vorburger . Merge if it LGTY.

**Review by vorburger — APPROVED** [review]

**Pull request merged**
