### PR TITLE
clean up all whitespace issues in Java files (FINERACT-821)

### PR DESCRIPTION
**Pull request by vorburger**
1. convert all Java files from DOS to UNIX line ending:
     find . -type f -name "*.java" -exec dos2unix '{}' ';'

  2. replace Tabs with 4 Spaces:
     rpl -eRxjava "\t" "    " .

  3. remove all trailing spaces:
     find . -type f -name "*.java" -exec sed -i 's/ *$//' '{}' ';'

### CODE REVIEW

**Comment by vorburger** [comment]
This PR only make whitespace clean up changes, and nothing else.  This can be "proven" by locally doing a `git diff -w` on it, or inspecting https://github.com/apache/fineract/pull/688/files?w=1.

See https://issues.apache.org/jira/browse/FINERACT-821 for full background.

**Comment by vorburger** [comment]
@awasum I'll fix the Merge Conflicts on this one **AFTER** my other work in #684 and #685 has been reviewed and merged. (I expect it may be simplest & fastest to just completely "recreate" this PR, from scratch on HEAD, by running the commands shown above, instead of actually resolving conflicts individually.)

**Comment by awasum** [comment]
> @awasum I'll fix the Merge Conflicts on this one **AFTER** my other work in #684 and #685 has been reviewed and merged. (I expect it may be simplest & fastest to just completely "recreate" this PR, from scratch on HEAD, by running the commands shown above, instead of actually resolving conflicts individually.)

Makes sense. Go for it.

**Comment by vorburger** [comment]
> Makes sense. Go for it.

but I'm waiting for you to review and hopefully merge #684 and #685 ... :smiley:

**Comment by awasum** [comment]
> > Makes sense. Go for it.
> 
> but I'm waiting for you to review and hopefully merge #684 and #685 ...

I think you are all set. Both PRs have now been merged.

**Pull request merged**
