### PR TITLE
Upgrade JaCoco version to 0.8.7 for suporting JDK 17 

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

With the upgrade to JaCoco 0.8.7 the Fineract Code Base will be prepared to be tested with the new JDK 17 which extends the support until 2026 it is related to https://issues.apache.org/jira/browse/FINERACT-1407

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [X] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [X] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by ptuomola** [comment]
Hi - looks like the build is failing - can you check? Once done would be great if you could squash your commits. Thanks!

**Comment by IOhacker** [comment]
Hello,

It failed because Docker rate pulling issue. How can I run the Travis-CI
job again?

Community-app (openmf/community-app:latest)...

1372ERROR: toomanyrequests: You have reached your pull rate limit. You
may increase the limit by authenticating and upgrading:
https://www.docker.com/increase-rate-limit

**Comment by awasum** [comment]
Close the pr and reopen it. Travis will run again.

**Comment by IOhacker** [comment]
Closing the Pr for running again (no changes)

**Comment by IOhacker** [comment]
Opening the PR for running again (no changes)

**Comment by IOhacker** [comment]
I will execute it during the weekend, I tried but same error.

Regards

**Comment by BLasan** [comment]
@IOhacker Please try reopening again.

**Comment by awasum** [comment]
Reopening now wont solve the problem as we can have a max of 100 pulls from DockerHub within a 6 hour period.. See: https://www.docker.com/increase-rate-limits

So we have to wait tomorrow to close and reopen this PR.

**Comment by BLasan** [comment]
> Reopening now wont solve the problem as we can have a max of 100 pulls from DockerHub within a 6 hour period.. See: https://www.docker.com/increase-rate-limits
> 
> So we have to wait tomorrow to close and reopen this PR.

Yeah

**Comment by IOhacker** [comment]
Closing the PR for running again (no changes)

**Comment by IOhacker** [comment]
Opening the PR for running again (no changes)

**Comment by IOhacker** [comment]
It has passed all the tests. Can it be merged? I will continue to work on
JDK 17.

Regards

**Review by BLasan — APPROVED** [review]
LGTM!

**Comment by ptuomola** [comment]
Can you squash the commits to one (with appropriate description) please? I'll merge once done

**Pull request merged**
