### PR TITLE
ContentRepository.fetchImage() FileData not ImageData (FINERACT-1201)

### PR DESCRIPTION
**Pull request by vorburger**
This is an extension of #1425 for FINERACT-1201.

### CODE REVIEW

**Comment by vorburger** [comment]
Changing to _Draft_, because this currently fails like this:

```
DocumentTest > downloadFile() FAILED
    expected: 2080155
    but was : -1
        at org.apache.fineract.integrationtests.newstyle.DocumentTest.downloadFile(DocumentTest.java:87)
```

This is due to the test still running against https://www.fineract.dev - I REALLY need #1465 here to change it to run against `localhost`.

But let's first get #1425 reviewed and merged already.

**Comment by vorburger** [comment]
> need #1465 here to change it to run against `localhost`. But let's first get #1425 reviewed and merged already.

I'll continue working on this after #1494 is merged.

**Comment by vorburger** [comment]
@ptuomola @vidakovic @percyashu @xurror @fynmanoj @avikganguly01 @vincent-fuchs @awasum any of you willing to review this, for FINERACT-1201? Once this is in, a few more such refactoring may be proposed, and ultimately I will then work on FINERACT-955 some day.

I'm reasonable confident that this won't break break any :smiling_face_with_three_hearts: the documents and images features, because in FINERACT-1218 I have contributed [new test coverage for all this stuff](https://github.com/apache/fineract/tree/develop/integration-tests/src/test/java/org/apache/fineract/integrationtests/client) (and since FINERACT-1209 those new tests DO actually run in our CI!), but of course careful human code review is always still a good idea... :smiling_imp:

**Review by percyashu — APPROVED** [review]
LGTM!

**Pull request merged**
