### PR TITLE
FINERACT-1435: Fix running the Spring Boot JAR after Jersey 2 upgrade

### PR DESCRIPTION
**Pull request by ptuomola**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by awasum** [comment]
Just an unrelated question about GitHub Action builds.. Does it actually show the logs when the DB is being migrated? I cannot find it.. At what stage is it migrating? When the stacks are coming up? Just trying to understand the new CI way of doing it.

**Comment by ptuomola** [comment]
Hi - it works the same way as the Travis build: given the database is empty, the migration scripts are applied when the server comes up for the integration test

So far looks like the Travis and Github test are working the same way so as next step I think we can disable all the tests in Travis and just leave it to run SonarQube.

**Comment by ptuomola** [comment]
@vidakovic are you ok to merge this please? Otherwise the boot jar does not work

**Comment by vidakovic** [comment]
Looks great.

**Pull request merged**
