### PR TITLE
Fix ResultSet type(FINERACT-995)

### PR DESCRIPTION
**Pull request by xurror**
[FINERACT-995](https://issues.apache.org/jira/browse/FINERACT-995)

### CODE REVIEW

**Comment by xurror** [comment]
@vorburger, are you OK with this?
Can't tell for sure if it will fix our problem.
cc: @awasum @ptuomola

**Comment by ptuomola** [comment]
@xurror Unfortunately I doubt this will work: MySQL Connector does not support scrollable cursors, so setting ResultSet.TYPE_SCROLL_INSENSITIVE should have no impact. 

From MySQLConnector documentation: 
MySQL does not support SQL cursors, and the JDBC driver does not emulate them, so setCursorName() has no effect.

I think we need to look at the job that fails and see what could lead to this... and why does Spring throw a TransientDataAccessException - some concurrency issue? Underlying data was modified by another job at the same time?

**Comment by ptuomola** [comment]
@xurror @vorburger - I think I found the line that causes it - added the relevant code in JIRA as a comment

**Comment by vorburger** [comment]
@xurror would you be willing to retract this PR in favour of new @ptuomola #1024 ? (And can / would you like to help to co-review that new PR? Please don't merge before we have input from several people.)

**Review by vorburger — CHANGES_REQUESTED** [review]
@xurror would you be willing to retract this PR in favour of new @ptuomola #1024 ? (And can / would you like to help to co-review that new PR? Please don't merge before we have input from several people.)

**Comment by xurror** [comment]
No problem

**Pull request closed without merging**
