### PR TITLE
FinancialActivityData class bug fixed

### PR DESCRIPTION
**Pull request by SubhamKrGuptaDev**
Hi, I have seen FinancialActivityData This class doesn't have a constructor but 'convertToFinancialActivityData(final FinancialActivity type)' this method is try to inject value by constructor so I have created customer please merge this changes 
Thank you

### CODE REVIEW

**Review by adamsaghy — COMMENTED** [review]
@Data lombok annotation contains @RequiredArgsContructor which is equal with the constructor you have created, no?

**Comment by vidakovic** [comment]
@SubhamKrGuptaDev please provide the Fineract Jira ticket as a prefix in your PR title ("FINERACT-1234: ...")

**Comment by vidakovic** [comment]
@SubhamKrGuptaDev please look at the other PRs and follow the same pattern for the PR title... "FINERACT-XXXX: Title of the Jira ticket"

**Comment by vidakovic** [comment]
The code change seems to have no consequences (i. e. is not used anywhere). Note: we are already using Lombok annotations here; if we really wanted  an all args constructor we should use the Lombok annotation (one liner).

**Pull request closed without merging**
