### PR TITLE
FINERACT-1724 swagger fix

### PR DESCRIPTION
**Pull request by peter-kovacs-dpc**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by adamsaghy — APPROVED** [review]
LGTM

**Comment by reluxa** [comment]
It looks like that in the database we still store 4byte integers: 

image

image

**Comment by adamsaghy** [comment]
> It looks like that in the database we still store 4byte integers:
> 
> image
> 
> image

Nice catch!
@peter-kovacs-dpc Would you please make the changes regarding the order? (it should be integer, we dont really need long there...)

**Comment by peter-kovacs-dpc** [comment]
@adamsaghy the base of the changes I made was the `PaymentTypeData.java` class in which the position is Long
Should I chage that too?

**Comment by adamsaghy** [comment]
> @adamsaghy the base of the changes I made was the `PaymentTypeData.java` class in which the position is Long
> Should I chage that too?

Yes, please.

Also please check this failing test:

```  Test testSavingsAccountWithdrawalChargesOnPaymentTypes() FAILED

  java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
      at org.apache.fineract.integrationtests.ClientSavingsIntegrationTest.testSavingsAccountWithdrawalChargesOnPaymentTypes(ClientSavingsIntegrationTest.java:2642)

**Comment by adamsaghy** [comment]
@peter-kovacs-dpc Please check the below failing test:
```
  Test testSavingsAccountWithdrawalChargesOnPaymentTypes() FAILED

  java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
      at org.apache.fineract.integrationtests.ClientSavingsIntegrationTest.testSavingsAccountWithdrawalChargesOnPaymentTypes(ClientSavingsIntegrationTest.java:2642)

**Pull request merged**
