### PR TITLE
Improve error logging for failed user creation (FINERACT-1070)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-1070

### CODE REVIEW

**Comment by vorburger** [comment]
@thesmallstar this is a follow-up to #1541 (thanks for your review & merge!), as per FINERACT-1070; merge this if it LGTY?

**Review by thesmallstar — APPROVED** [review]
LGTM!
No functional changes, improved error handling.

**Comment by francisguchie** [comment]
@thesmallstar  & @vorburger  please see https://issues.apache.org/jira/browse/FINERACT-1070 i have done the tests

**Comment by francisguchie** [comment]
Functionally the messaging is greatly improved

**Pull request merged**
