### PR TITLE
FINERACT-821: Enable and enforce (!) Checkstyle in Fineract

### PR DESCRIPTION
**Pull request by Wandji69**
## Description
This was done from https://github.com/checkstyle/checkstyle/blob/56307daaf4921243c16a874b844757961618003b/src/main/resources/google_checks.xml. 
which is in respect to following the google coding convention used by fineract

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in the repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by thesmallstar** [comment]
You have uncommented the checkstyle modules, I think we need to uncomment them one by one, and enforce them so that the build wont fail.
Also, I suggest not adding new modules and currently focus on what were already decided by @vorburger 

What do you suggest?

**Comment by Wandji69** [comment]
> You have uncommented the checkstyle modules, I think we need to uncomment them one by one, and enforce them so that the build wont fail.
> Also, I suggest not adding new modules and currently focus on what were already decided by @vorburger
> 
> What do you suggest?

I Understand that, but the modules suggested by @vorburger are from https://github.com/opendaylight/odlparent/blob/master/checkstyle/src/main/resources/odl_checks.xml and while I was going through the checksytle docs I saw a usage example that meets the google coding conventions here https://github.com/checkstyle/checkstyle/blob/56307daaf4921243c16a874b844757961618003b/src/main/resources/google_checks.xml. 

I have just removed something's not need and added what was missing in some places

**Comment by Wandji69** [comment]
Both checkstyle examples are the same but one is a little more specific on what is to check that's what I went in for.

**Comment by vorburger** [comment]
Hello. I'll only review this PR if it passes the build checks. Thanks for understanding!

**Comment by thesmallstar** [comment]
@Wandji69 thank you for the explanation :D I got it now, on the other side, I have already laid a plan for implementing and enforcing "current check styles", We can definitely add more/make the current more specific, but I would prefer focusing on what we already have planned? What do you think? 
I like the idea of adding more/making them more specific. I will start implementing them from 14-15may(as a part of GSoC), after which you can take over to make them more specific to improve code quality even further(Which will be certainly great and needed) 

If you like my plan to make the codebase more beautiful, you can give me LGTM? 

FYI @vorburger 

-thanks 
Manthan

**Comment by awasum** [comment]
Wandji Collins. Pick something else from the backlog to work on. Manthan Surkar is claiming this one for this GSoC work. Next time Manthan Surkar , dont wait for someone to show interest on an issue before you self assign to yourself. Pick one or 2 issues at a time to work on and give room for others. You can go through the issue tracker and pick the issues you are interested in...so that people dont get confused. One person should own and work on a single issue in most cases.

**Comment by Wandji69** [comment]
Okay @awasum, I will close this issue now and let @thesmallstar take over.

**Comment by thesmallstar** [comment]
@Wandji69 okay, I will give you mention as soon as I am done so that you can execute your plan of google checks which will bring another huge improvement on our code base :D 

@awasum I will keep that in mind.
-Thanks
Manthan

**Comment by Wandji69** [comment]
Okay great.

**Pull request closed without merging**
