### PR TITLE
FINERACT-1107 month-end-dates-reschedule-issue-fix

### PR DESCRIPTION
**Pull request by fynmanoj**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

at https://issues.apache.org/jira/browse/FINERACT-1107. Originally detailed at https://mifosforge.jira.com/browse/AL-12
## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vorburger** [comment]
@fynmanoj would you be willing to create a JIRA issue on the ASF JIRA, instead of referencing an issue from an issue tracker that is now a downstream redistribution of Fineract?

**Comment by vorburger** [comment]
@avikganguly01 knowing that @fynmanoj works with you, and assuming that you are still an active committer to this project (are you?), I was wondering if you would like to engage on code review feedback and possible evental merge of PRs such as this one? (I don't want to be a bottleneck on this project, and won't have the spare time to help review changes like this. If there are other active commiters such as @awasum @ptuomola @xurror or others reading this who want to engage on this PR, please don't let me hold you up / wait for me - I'll ignore this one, and try to help on others.)

**Comment by edcable** [comment]
@vorburger I opened up tickets on JIRA for these pull requests and referenced them in the title of the PR. I tagged @avikganguly01 as a reviewer and assume he can do the needful in reviewing and merging the PRs as we are going to start testing this development branch with these pull requests merged on the user's test server.

**Comment by edcable** [comment]
@vorburger I opened up tickets on JIRA for these pull requests and referenced them in the title of the PR. I tagged @avikganguly01 as a reviewer and assume he can do the needful in reviewing and merging the PRs as we are going to start testing this development branch with these pull requests merged on the user's test server.

**Comment by vidakovic** [comment]
@avikganguly01 did you have a chance to review this PR? Just want to make sure we have enough time before the release next week to test everything in the develop branch

**Review by avikganguly01 — APPROVED** [review]

**Pull request merged**
