### PR TITLE
FINERACT-1541: Pentaho accounting reports converted to table format

### PR DESCRIPTION
**Pull request by sheminanto**
## Description

https://issues.apache.org/jira/browse/FINERACT-1541

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by galovics — CHANGES_REQUESTED** [review]
I see that the changelog includes only MySQL compatible select statements (backticks for example). Make sure to mark those only MySQL relevant changelogs with `context="mysql"` so they only run in that case and make sure to introduce the same statements for PostgreSQL too with `context="postgresql"`. You can find examples for that in the `0002_initial_data.xml` file.

Also, I'd love to see some test cases to verify that the reports work both for MySQL and PostgreSQL.

**Comment by sheminanto** [comment]
@galovics  The migration ran successfully with both mysql and posgres. So do we need to create separate changes for mysql and postgres ?

**Comment by galovics** [comment]
@sheminanto let's differentiate 2 things, the migration and the report execution. The migration is going to run successfully for sure since you're inserting some SQL strings into the report table. But when you try to execute the SQL statements you inserted into the report table - i.e. querying a report, it's going to fail.
For example the backtick (\`) is a specific character only used for MySQL to escape literals. That's going to fail with PostgreSQL. You can look at the existing migrations in `0001_initial_data.xml`. There's a separate changeset for MySQL and PostgreSQL.
Also, since this didn't fail the build, I'd appreacite if you could add some integration tests for each report you created.

**Comment by fynmanoj** [comment]
@sheminanto, rebase this PR

**Comment by fynmanoj** [comment]
@vidakovic  could you please include this in 1.7

**Comment by fynmanoj** [comment]
This  PR is raised again at https://github.com/apache/fineract/pull/2291  with rebase changes

**Pull request closed without merging**
