### PR TITLE
clean up XBRLBuilderTest (re. FINERACT-940)

### PR DESCRIPTION
**Pull request by vorburger**
This doe NOT actually fix FINERACT-940, it's a clean up, while I looked at that problem.

### CODE REVIEW

**Comment by vorburger** [comment]
@ptuomola would this LGTY (look good to you) ?

**Comment by vorburger** [comment]
@thesmallstar FYI and does this LGTY? (This is how you should clean up tests for FINERACT-942.)

**Comment by thesmallstar** [comment]
LGTM.
-thanks
Manthan

**Comment by ptuomola** [comment]
> @ptuomola would this LGTY (look good to you) ?

Looks good to me...

**Pull request merged**
