### PR TITLE
FINERACT-1336 add full Parameter List

### PR DESCRIPTION
**Pull request by francisguchie**
## Description

Please read here https://issues.apache.org/jira/browse/FINERACT-1336

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by thesmallstar** [comment]
The tests probably failed due to some network error..

**Comment by francisguchie** [comment]
@thesmallstar, sure thanks - I it has passed the test now

**Comment by josemakara2** [comment]
Hi @francisguchie Please see comments on Jira FINERACT-1338
Thanks

**Comment by francisguchie** [comment]
@josemakara2 I have seen your comments and you have done an extensive job in digging out the trend of the events. My biggest challenge is the way forward

**Comment by francisguchie** [comment]
@josemakara2  @thesmallstar  
After looking at comments here [FINERACT-1338](https://issues.apache.org/jira/browse/FINERACT-1338) 
I tested the PR #1671  

This renders this PR useless and thus i will close it thanks to @josemakara2

**Pull request closed without merging**
