### PR TITLE
FINERACT-959  make javac fail for rawtypes

### PR DESCRIPTION
**Pull request by percyashu**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by percyashu** [comment]
@awasum and @vorburger I will look into an appropriate fix for the HashMap rawtype warning wasn't sure which arguments it require . I notice some in some test it was it was suppressed along with unchecked warning.

**Comment by awasum** [comment]
> @awasum and @vorburger I will look into an appropriate fix for the HashMap rawtype warning wasn't sure which arguments it require . I notice some in some test it was it was suppressed along with unchecked warning.

Yes, use a debug breakpoint and look at what is returned to determine what type of variables to declare. When do you plan on doing this?

**Comment by awasum** [comment]
This may sound abit harsh but bare with me.

It looks like you did not run this on your local system or did not try to solve the Raw Types problem before sending a PR. Please, next time, test and make sure everything works locally before sending your PR. Run ./gradlew clean build and ./gradlew clean integrationTest locally and only when they fail before you send your PR. Except in cases where you want to show us something interesting for us to give you feedback, in which case you may send a draft PR like the others have been doing.
I see you are opening alot of PRs and not getting most of them merged. If handling many issues at same time is making you slow, then I will advice you take 1 issue at a time or at most 2. This way you make more progress.

**Comment by vorburger** [comment]
@percyashu will you pick this up and finish it? Or is this a lot of work and not worth it?

**Comment by percyashu** [comment]
@vorburger it is a lot of work and will surely look into it later.

**Pull request closed without merging**
