### PR TITLE
upgrade RestAssured version (FINERACT-809)

### PR DESCRIPTION
**Pull request by vorburger**
Co-authored-by: percyashu <percyayukashu@gmail.com>

### CODE REVIEW

**Comment by vorburger** [comment]
This is just a rebase of  #719 from @xurror and @percyashu and I'm just curious if this passes... I ran this locally x3 times, and it failed with https://issues.apache.org/jira/browse/FINERACT-855 every time - may be that is not just a flaky test, but really something that this PR breaks, for some (strange, yes) reason.

NB that other PRs passed today (e.g. #723 and #725) so if this still fails, perhaps the new RestAssured version is somehow changing some timing or something which causes IT test failures?!

**Comment by vorburger** [comment]
Now this failed due to yet another new IT failure, see [FINERACT-857](https://issues.apache.org/jira/browse/FINERACT-857)..

**Comment by awasum** [comment]
@percyashu or @xurror ..Please can we look into this?

**Comment by vorburger** [comment]
#719

**Pull request closed without merging**
