### PR TITLE
fix .travis.yml so that integrationTest does not run if test already failed

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by awasum** [comment]
Makes sense. preventing unnecessary execution.

This will really be used once a test fails.

Merge this?

**Comment by vorburger** [comment]
> Merge this?

yes, please! :smile_cat: Tx.

**Comment by vorburger** [comment]
actually wait a second - have you noticed that Travis hasn't run on this PR? That's weird...

**Comment by awasum** [comment]
Yeah... maybe leave this and instead merge #634  which contains this commit and one addition commit

**Comment by vorburger** [comment]
>  have you noticed that Travis hasn't run on this PR? That's weird...

so Travis runs just fine on #635 .. I think this as is originally is wrong - the `\` line break probably doesn't work - let me change this to be all on a single line instead.

**Comment by vorburger** [comment]
@awasum fixed it - looks good to you now - merge?

**Comment by awasum** [comment]
Yes.

**Pull request merged**
