### PR TITLE
Make repayments file download for bulk import tool

### PR DESCRIPTION
**Pull request by pwairuru**

### CODE REVIEW

**Review by ShruthiRajaram — CHANGES_REQUESTED** [review]
@pwairuru  kindly create a Jira (Fineract Jira) ticket if not present, with proper description and mention the issue number in the pull request.

**Comment by vorburger** [comment]
@pwairuru thank you very much for your interest in and contribution to Fineract/Mifos!  I'm an (old) volunteer who got reminded of Mifos/Fineract this week-end at the FOSDEM conference, and I'm taking a moment to help the project clean up some of it's old issues and pull requests etc.  

We were wondering whether you are still alive, and would be willing to `git rebase develop` this PR and take any previous review feedback into account?  If we don't hear from you within 2 weeks, we will take the liberty to close this PR without merging it, to avoid confusion for future new contributors looking at this repository - hope you understand and that's fair.

/Cc FYI @apache/fineract-committers

**Comment by vorburger** [comment]
Friendly service reminder: I will close this PR in 3 days to help this project have a clean list of active PRs.

**Comment by vishwasbabu** [comment]
@pwairuru : Since this is a simple fix. a jira ticket has been created at https://jira.apache.org/jira/browse/FINERACT-729 and the pr merged. Please update the same if you have anything to add

**Pull request merged**
