### PR TITLE
FINERACT-1054 fix Error at Loan Repayment -bad SQL Grammar

### PR DESCRIPTION
**Pull request by francisguchie**
## Description
https://issues.apache.org/jira/browse/FINERACT-1054

## Checklist
see https://github.com/apache/fineract/pull/1139

- [ ] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by awasum** [comment]
See: https://travis-ci.org/github/apache/fineract/builds/704910968

  Run './gradlew :spotlessApply' to fix these violations.

**Comment by awasum** [comment]
Your PR is failing Travis. We can only consider to merge PRs when they have passed Travis test and everything is green.

**Comment by francisguchie** [comment]
@awasum 
I am using a windows 10 PC - I have run the /gradlew :spotlessApply  and it was successful on my computer please see image below and advise. I would love to know how to solve this 

image

**Comment by awasum** [comment]
Make sure you have pulled from Fineract develop branch. latest changes.

**Comment by francisguchie** [comment]
Yes @awasum 
Please see how i pull from develop all the time 

image

**Comment by francisguchie** [comment]
i will close this and make another PR

**Comment by francisguchie** [comment]
re-opened let me observe the tests

**Comment by francisguchie** [comment]
@awasum 

followed the steps you provided. still PR failed

**Comment by thesmallstar** [comment]
@francisguchie  I made a video, it might help you: https://www.loom.com/share/d805d63a44014156a9955dd29b0ee4d5
Spotless took exceptionally 1 min(usually takes 10sec idk why, while making the video)

**Comment by thesmallstar** [comment]
@francisguchie the final change look like this: https://github.com/apache/fineract/compare/develop...thesmallstar:cur43?expand=1
And will make spotless happy :)

**Comment by francisguchie** [comment]
@thesmallstar  thanks alot

Since this PR is the same as the https://github.com/apache/fineract/pull/1154 i think this should be closed. Please advise

**Comment by thesmallstar** [comment]
If #1154  has the final version of what needs to be done, please close this one :) 
@awasum can merge the other PR as soon as we get it reviewed.

**Comment by francisguchie** [comment]
> If #1154 has the final version of what needs to be done, please close this one :)
> @awasum can merge the other PR as soon as we get it reviewed.

" Sir Yes Sir " 
Yes the #1154 has the final version 

am closing this one

**Pull request closed without merging**
