### PR TITLE
introduce Checkstyle, start enforcing whitespace related rules (FINERACT-821)

### PR DESCRIPTION
**Pull request by vorburger**
Once #688 which bulk cleans up all existing whitespace issues,

after a rebase and verification (or more PRs) that there are no other new issues,

this PR contributes an initial Checkstyle configuration which will fails builds/PR for new whitespace issues.

The initial Checkstyle XML configuration contributed here has many more rules, but all non whitespace related ones are still commented out for now; the idea being that we (myself or, hopefully, other contributors!) then gradually enable more of those rules, after fixing existing violations.

See https://issues.apache.org/jira/browse/FINERACT-821 for full background.

### CODE REVIEW

**Comment by vorburger** [comment]
@awasum FYI with me just having merged #688, this one is now ready! Would you do the honours of reviewing it (also to get familiar with it, in case you would consider make some further contributions based on this?), and merging ASAP?

PS: This build will most likely fail, because it's Sunday, due to [FINERACT-820](https://issues.apache.org/jira/browse/FINERACT-820) (what a PITA, is anyone ever going to fix that?). Perhaps you'd like to Close and Re-Open it tomorrow, before merging it to convince yourself that the Checkstyle really fully passes? (Which it does, I've of course tested this locally.)

**Comment by vorburger** [comment]
@awasum will you have a moment to review and (hopefully) merge this some time in the next few days?

**Comment by awasum** [comment]
> @awasum will you have a moment to review and (hopefully) merge this some time in the next few days?

@vorburger  Sorry, I have been so busy at work. Please, I will review this latest this weekend. Thanks for the opportunity and the reminder.

**Review by awasum — APPROVED** [review]
Actually, this is simple to review and merge.. doing it ASAP.

**Pull request merged**
