### PR TITLE
FINERACT-1410: Fix feature broken by PR1960

### PR DESCRIPTION
**Pull request by fynmanoj**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by fynmanoj** [comment]
@ptuomola, I had to override some changes you have pushed as it breaks the feature that is using the configurations. I understand that you have added these changes to fix the tests-execution issue.
I have added the same fix, without altering the migration scripts.   Kindly look at this and approve if this looks OK to you.

**Comment by ptuomola** [comment]
Thanks @fynmanoj. I assumed that the original PR 1918 was intending to set this variable as false, as that's the value that was given for it in the class GlobalConfigurationHelper.java of PR1918. 

If that was not the intention and this should have been true instead, then your PR looks good. I'll wait until the build passes and then will merge.

**Comment by fynmanoj** [comment]
Yes, @ptuomola, The configuration is supposed to be enabled. Thanks

**Comment by ptuomola** [comment]
Build and tests passed - so good to merge! 👍

**Pull request merged**
