### PR TITLE
FINERACT-1715: Introduce Lombok to cob module

### PR DESCRIPTION
**Pull request by hmg65**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [x] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [x] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by galovics** [comment]
PR conflicting.

**Comment by galovics** [comment]
PR conflicting.

**Comment by galovics** [comment]
PR conflicting still.

**Review by thesmallstar — APPROVED** [review]
As confirmed, this changes are done to make Lombok annotation uniform across code. 

@galovics Please merge if LGTY, 

as asked by @luckyman20 on our call, please add some set of guidelines for adding necessary lombok annotations (as discussed with aleks) so that other devs can follow the same.

**Comment by galovics** [comment]
@hmg65 PR is still conflicting.

**Comment by luckyman20** [comment]
@galovics I do not see any conflicts while merging with the base branch.

@hmg65 Please squash the commits.

**Pull request closed without merging**
