### PR TITLE
Log errors from cron jobs individually and with cause (FINERACT-858)

### PR DESCRIPTION
**Pull request by vorburger**
instead of current huge JobExecutionException message (without cause)

see https://issues.apache.org/jira/projects/FINERACT/issues/FINERACT-858

### CODE REVIEW

**Comment by vorburger** [comment]
@awasum want to review this one? See the JIRA for some background.

**Review by awasum — APPROVED** [review]
LGTM. Merging now. 

There is another, realted issue that uses a findbug SLF4J plugin to find bad usage of Loggers. Anyone reading can see: https://issues.apache.org/jira/browse/FINERACT-696
and https://github.com/apache/fineract/pull/716 if you wanted to help. This is not blocking us for merging this PR BTW.

**Comment by vorburger** [comment]
> LGTM. Merging now.

@awasum forgot to actually click the merge button? :smile:

**Comment by awasum** [comment]
> > LGTM. Merging now.
> 
> @awasum forgot to actually click the merge button?

Thanks. Was waiting for another merged PR to finish running the Post PR merge Travis task.

**Pull request merged**
