### PR TITLE
Support for SonarQube Analysis on ASF's SonarCloud

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

It adds support for SonarQube Analysis related to this ticket https://issues.apache.org/jira/browse/FINERACT-1409

After that the SonarQube Analysis results will be available at https://sonarcloud.io/project/configuration?id=apache_fineract  

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [X] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by IOhacker** [comment]
Closinf for running again

**Comment by IOhacker** [comment]
Opening for running again

**Comment by BLasan** [comment]
@IOhacker Please squash the commits

**Comment by BLasan** [comment]
PR looks ok to me !!

**Review by BLasan — APPROVED** [review]

**Pull request merged**
