### PR TITLE
FINERACT-821 Added FallThrough Checkstyle

### PR DESCRIPTION
**Pull request by thesmallstar**
Refer: https://issues.apache.org/jira/browse/FINERACT-821

### CODE REVIEW

**Comment by vorburger** [comment]
@thesmallstar resolve merge conflict?

**Comment by vorburger** [comment]
@thesmallstar resolve merge conflict and I'll merge this (trivial) one ASAP

PS What you could do to avoid this is to "cheat" a little bit and just add new lines a little "higher up", so that not all new checks appear in the same line to git diff, that way there won't be any conflicts - do you know what I mean?

**Comment by thesmallstar** [comment]
@vorburger understood! will do it from next time :)

**Comment by thesmallstar** [comment]
Build failed, looking into it.

**Review by vorburger — APPROVED** [review]
LGTM

**Pull request merged**
