### PR TITLE
FINERACT-805  Spring BOM version numbers rebase

### PR DESCRIPTION
**Pull request by percyashu**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket https://issues.apache.org/jira/browse/FINERACT-805

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [ ] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by percyashu** [comment]
@vorburger could you review this.
"junit-dep" was moved to "junit", see the notice in the header of https://mvnrepository.com/artifact/junit/junit-dept . So I removed it.
json-path breaks builds when version update. I think some methods from old version have been drop.

**Review by vorburger — APPROVED** [review]
This LGTM! Thanks. (Do send more PRs...)

To merge it, I'm just not clear if we (someone, who?) is about to cut a 1.4.0 release, and if it's still OK to merge this right now, or after branching? @awasum @santoshconflux @avikganguly010

@xurror just FYI (I thought this PR may interest you)

**Comment by vorburger** [comment]
Oh wait this is still building, right now.. obviously needs to be green, first.

**Comment by percyashu** [comment]
@vorburger when I run gradle clean build, the build is successful .I will have to recheck the changes

**Review by vorburger — CHANGES_REQUESTED** [review]
Looks like it failed due to:

com.googlecode.flyway.core.api.FlywayException: No value provided for placeholder expressions: ${currencyId}, ${currentUserHierarchy}, ${currentUserId}, ${endDate}, ${fundId}, ${loanOfficerId}, ${loanProductId}, ${loanPurposeId}, ${obligDateType}, ${officeId}, ${parType}, ${reportCategory}, ${reportListing}, ${startDate}.  Check your configuration!; for Tenant DB URL: jdbc:mysql:thin://localhost:3306/mifostenant-default, username: root

Try undoing the Flyway 2.2.1 version change from this PR. I suspect that will help. You could then investigate that one more separately.

PS: To test better locally, you'll want to not just build but actually run it, using tomcatRunWAR and then checking https://localhost:8443/fineract-provider/actuator/health, and/or running the integration tests, see README.

**Comment by vorburger** [comment]
@percyashu FYI you don't have to keep opening new PRs, just (force) push to your same branch, and your PR will update automatically... that's much easier, and less confusing, than closing un-merged PRs, and opening #666 #668.

**Pull request closed without merging**
