### PR TITLE
fix some 3rd-party versions in build.gradle (see FINERACT-805)

### PR DESCRIPTION
**Pull request by vorburger**
FINERACT-805

### CODE REVIEW

**Comment by vorburger** [comment]
@xurror @awasum how about this?

**Comment by vorburger** [comment]
@awasum @xurror how do you like this one?

@ptuomola @maektwain FYI if interested.

**Comment by awasum** [comment]
LGTM... 

Someone interested in this should also just update the Spring Boot and Spring versions along with Gradle Wrapper version so we dont forget. A GSoC Applicant reading might like to do this... @nnatarajan  will u be interested to do that? in a different(new) PR?

**Comment by vorburger** [comment]
I'm going to rebase this to resolve conflicts following related earlier #803 #802 #806.

I'll also awai @xurror review feedback on this one, as he introduced some of what I'm upgrading here.

@ptuomola hope this and earlier #803 #802 #806 wont' cause too much rebase conflict for your #807.

**Review by xurror — APPROVED** [review]
Looks a lot better this way. I think it's good to go

**Comment by nnatarajan** [comment]
> LGTM...
> 
> Someone interested in this should also just update the Spring Boot and Spring versions along with Gradle Wrapper version so we dont forget. A GSoC Applicant reading might like to do this... @nnatarajan will u be interested to do that? in a different(new) PR?

@awasum -- I can take on, I created FINERACT-968. Is update for most recent versions?

**Pull request merged**
