### PR TITLE
Make sure that using this pseudorandom number generator is safe (FINERACT-1415)

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

Make sure that using this pseudorandom number generator is safe (FINERACT-1415)

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [X] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [X] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by IOhacker** [comment]
@awasum this is the fix ready to merge.

**Comment by ptuomola** [comment]
@IOhacker please could you squash the commits in your PR so that there's only one commit. See https://github.com/apache/fineract#merge-strategy for explanation. Please don't merge your commit yourself - just squash the commits so that the PR is unmerged but only contains one commit. Hope this is ok?

**Comment by IOhacker** [comment]
I will check how to do that in my repo.

Regards

**Comment by fintecheando** [comment]
I have done this:

Fork the apache/fineract repository, then clone the fork in my local environment
1. Create a bug fix branch from develop
git checkout -b FIX_FINERACT_XXYY develop
2. Do the changes
3. Commit the changes to the bug fix branch (being careful with the -a parameter)
git commit -am "YOU COMMENT (FINERACT-XXYY)"
4. Commit the changes to my FORK repository
git push
5. Send the PR
6. After making the PR work with the checklist, I am squashing the fixes into development branch in my local repository
git checkout develop
git merge --squash FIX_FINERACT_XXYY develop
git commit -am "YOU COMMENT (FINERACT-XXYY)"
4. Commit the changes to my FORK repository
git push

**Comment by ptuomola** [comment]
Another option is to do the following on your PR branch - if you want to squash 3 commits to one, for example: 

	git rebase -i HEAD~x

(where x is the number of commits to include in the squash)

In the editor, mark as “f” in the first column for all the commits except the first one you want to retain

Save editor

Now if you do git log you should only see one commit

Then do “git push -f origin” to push the new history to Github

**Review by awasum — APPROVED** [review]
LGTM... @ptuomola  over to you. Lets wait for Petri to take a look.

**Review by ptuomola — APPROVED** [review]
LGTM

**Comment by ptuomola** [comment]
Change looks good and build passes. @IOhacker  did you work out how to squash the commits though - could you still do this please, and I can then merge?

**Comment by IOhacker** [comment]
@ptuomola there are two commits, one is from one merge and the other is the squash, I have done a previous failed squas (the one related to the Azul Zulu JDK 11) so I am afraid to make a wrong squashing action.

**Comment by ptuomola** [comment]
OK - thanks. I'll merge this as is to avoid any more problems with the squash.

**Comment by awasum** [comment]
JIRA issue has now been closed as this has been merged. https://issues.apache.org/jira/browse/FINERACT-1415

Thank you All.

**Pull request merged**
