### PR TITLE
FINERACT-1557-fix

### PR DESCRIPTION
**Pull request by fynmanoj**
## Description

Describe the changes made and why they were made.

Ignore if these details are present on the associated [Apache Fineract JIRA ticket](https://github.com/apache/fineract/pull/1284).

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [x] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [x] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Comment by vidakovic** [comment]
@fynmanoj the build is failing since this commit https://github.com/apache/fineract/commit/d5c611564f7b8c877136f3b3aca647bf7de15fe0 ... i. e. there is some correlation with EclipseLink. I have disabled the failing tests for now in my PR until we can further analyze this. I will create a Jira issue and add the 3 tests so that we solve this before the next release.

FYI

**Comment by fynmanoj** [comment]
@vidakovic This PR contains fix for an issue found in the stacktrace, so we may still need this

**Comment by vidakovic** [comment]
FYI: Victor is taking over to investigate this.

**Comment by vidakovic** [comment]
Closing this one to avoid confusion.

**Pull request closed without merging**
