### PR TITLE
FINERACT-1477: Change the logging level for InsufficientAccountBalanceException in batch job

### PR DESCRIPTION
**Pull request by GoyalRocks007**
Changed the logging level for InsufficientAccountBalanceException in batch job from error to warn.
Removed errors.add(e) to avoid abrupt stopping of batch job due to this exception.

### CODE REVIEW

**Comment by adamsaghy** [comment]
@bharathc27 When the `Transfer Interest To Savings` job running and one of the savings account throw `InsufficientAccountBalanceException`, should the whole job stop and marked as FAILED?

**Comment by bharathcgowda** [comment]
@adamsaghy  in that scenario the job should continue for the remaining loans and at the end should throw an error message only for the savings account that had the insufficient balance

**Comment by GoyalRocks007** [comment]
Hello @adamsaghy @bharathcgowda, I have made the required changes. Please check and let me know.
Thanks.

**Comment by adamsaghy** [comment]
@GoyalRocks007 Please squash your commits and make sure the commit message follows the same format as the PR title:
FINERACT-1477: Change the logging level for InsufficientAccountBalanceException in batch job

The rest looks okay

**Comment by GoyalRocks007** [comment]
Hello @adamsaghy, done as suggested.

**Pull request merged**
