### PR TITLE
Added Dockers Logo To Its Badge

### PR DESCRIPTION
**Pull request by atharwa-24**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [ ] API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm has been updated with details of any API changes.

- [ ] Integration tests have been created/updated for verifying the changes made.

- [ ] All Integrations tests are passing with the new commits.

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by atharwa-24** [comment]
Added Dockers Logo to the Repos Dockers Badge in README.md file
Removed the Github Version Release Badge

**Comment by atharwa-24** [comment]
as Told By @vorburger in PR #1233

**Comment by edcable** [comment]
@atharwa-24 Are you able to address your failing build?

**Comment by atharwa-24** [comment]
I guess its because this pull request contains 2 commits one for adding the version badge and other for its removal
@edcable

**Comment by atharwa-24** [comment]
apa
apache

**Comment by vorburger** [comment]
Unclear why the build failed here, as this only touches the README.md.

@atharwa-24 it took me moment to understand what you were proposing here... :smile: Then I figured that you are just adding `?logo=Docker` which makes e.g. https://img.shields.io/docker/pulls/apache/fineract.svg?logo=Docker have the "whale" which https://img.shields.io/docker/pulls/apache/fineract.svg does not - sweet! :tada:  Perhaps in future PRs you can describe this kind of thing more clearly like that, to make it more obvious for maintainers what you are proposing, and why.

Also, you should learn how to "squash" Git commits, so that we don't get 3 but only 1 final commit in a PR. I'll do it for you here while merging.

**Pull request merged**
