### PR TITLE
FINERACT-1821 Postgresql Support for Tellers ->Cashiers->Transactions

### PR DESCRIPTION
**Pull request by IOhacker**
## Description

Postgresql now is supported for getting the Tellers ->Cashiers->Transactions

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [X] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [X] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [X] Create/update unit or integration tests for verifying the changes made.

- [X] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [X] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/legacy-docs/apiLive.htm with details of any API changes

- [X] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by josehernandezfintecheandomx — APPROVED** [review]
LGTM

**Review by galovics — CHANGES_REQUESTED** [review]
Looks good but since this wasn't failing before yet we had an issue in the implementation, do you mind introducing new integration tests to cover this functionality? Thanks.

**Comment by IOhacker** [comment]
@galovics I will, I have found more TIME and DATE_ADD functions in the code related to Teller/Cashiers classes, seems that this functionality was not fully tested with Postgresql as DB.

**Comment by galovics** [comment]
> @galovics I will, I have found more TIME and DATE_ADD functions in the code related to Teller/Cashiers classes, seems that this functionality was not fully tested with Postgresql as DB.

Yep, that's why I asked you to please add new integration tests to cover this/these functionalities.

**Pull request closed without merging**
