### PR TITLE
FINERACT-893-fixed-deposit-rollover

### PR DESCRIPTION
**Pull request by fynmanoj**
## Description
Fixed deposit maturity instructions added. 1 reinvest maturity amount 2. reinvest principal 3. transfer to savings 4, withdraw 

FINERACT-893

### CODE REVIEW

**Comment by vorburger** [comment]
@fynmanoj re. build failure, please subscribe to and watch (or help fix??) #764 for [FINERACT-852](https://issues.apache.org/jira/browse/FINERACT-852)...

**Comment by vorburger** [comment]
@fynmanoj Following #764 and #761 this will pass the build (or not at least not fail because of integration tests) if you rebase this now.

**Comment by vorburger** [comment]
@fynmanoj now it failed due to https://issues.apache.org/jira/browse/FINERACT-899 .. can you help fix that one? (In a separate PR I mean, not as part of this.) That would be amazing. Those test failures are really a problem for this project.

**Comment by vorburger** [comment]
I just did a quick technical review of this PR, and there is nothing shocking here, and it includes an Integration Test - this would get LGTM from me, once it actually passes the build. - It's a functional Improvement which, ideally, someone with domain expertise should review more. If we don't find anyone interested, I propose we would give this a 2 weeks grace period, and then merge if no one voices any objections....

**Comment by vorburger** [comment]
@fynmanoj you have to yourself figure out how to get this to pass the build. See also #782. I'll have to let you do the require rebase, check build status, etc. The project maintainers cannot check each PR and close and re-open PRs etc.

**Comment by nikpawar89** [comment]
@fynmanoj Thank you for your PR. By looking at you test cases I assume this PR supports two feature: 
1) Reinvesting FD with Principal + interest 2) Reinvesting Just the Principal part of it. 

Would you be able to document Business Use cases, to explain this feature to community. This would help others to use your implemented feature and test it before we release it. 

Also I don't see any API changes- is this correct. If there are API changes can you document them or perhaps add to API documentation.

Lastly, do you intend to develop UI support for this feature?

**Comment by avikganguly01** [comment]
@Ippezrobert Can you explain the business use case  feature to the community by enhancing FINERACT-893?

@nikpawar : Yes, corresponding UI PR has been sent at link - https://github.com/openMF/community-app/pull/3194. It has a screenshot. 

I have reviewed the functionality and it's good to be merged from both functional and technical aspect. Disclosure : Manoj works with me.

**Comment by ippezshelby** [comment]
1. MFI has a max of 1 yr Deposit Term but a client would wish to fix for 2 yrs, so the MFI accepts this offer and manages the 2 yrs period in shifts internally. So after the 1 yr is done, the MFI would like the rollover to be managed automatically by the system since chances that a new FD will be created exactly on the same date of maturity is small since an officer can forget to check if this FD is matured or not yet a client would be counting when the two years would end. So there needs to be a job scheduler to check maturity date for FD and also rollover options so that it (system can take appropriate decisions (to reinvest of just close and transfer interest and principal to linked savings).
**To be discussed:** Will the system use the same account number or new one will be created????

2.  A client would like to reinvest FD voluntarily since he sees no use for his money for some time. He then has to decides what amount or portion to reinvest after the first maturity is expired. Option can include rollover of principal only, rollover of principal and interest, transfer of balance to another account (make linked account dynamic .ie ability to select loan, shares or savings account and also a GL Account), etc

**NB:**
- If the selected option involves rollover, a Rollover End Date should be entered i.e the date when you want the rollover transaction to stop.
- If the option selected in After Maturity does not involve the roll over of interest with the principal, the option of linked account is mandatory .ie account to which the transfer will be made at maturity. Like i said this can be a loan, share or savings account but should belong to this client or it can be GL Account.

Hope my explanation helps
Regards

**Comment by fynmanoj** [comment]
> 1. MFI has a max of 1 yr Deposit Term but a client would wish to fix for 2 yrs, so the MFI accepts this offer and manages the 2 yrs period in shifts internally. So after the 1 yr is done, the MFI would like the rollover to be managed automatically by the system since chances that a new FD will be created exactly on the same date of maturity is small since an officer can forget to check if this FD is matured or not yet a client would be counting when the two years would end. So there needs to be a job scheduler to check maturity date for FD and also rollover options so that it (system can take appropriate decisions (to reinvest of just close and transfer interest and principal to linked savings).
>    **To be discussed:** Will the system use the same account number or new one will be created????
> 2. A client would like to reinvest FD voluntarily since he sees no use for his money for some time. He then has to decides what amount or portion to reinvest after the first maturity is expired. Option can include rollover of principal only, rollover of principal and interest, transfer of balance to another account (make linked account dynamic .ie ability to select loan, shares or savings account and also a GL Account), etc
> 
> **NB:**
> 
> * If the selected option involves rollover, a Rollover End Date should be entered i.e the date when you want the rollover transaction to stop.
> * If the option selected in After Maturity does not involve the roll over of interest with the principal, the option of linked account is mandatory .ie account to which the transfer will be made at maturity. Like i said this can be a loan, share or savings account but should belong to this client or it can be GL Account.
> 
> Hope my explanation helps
> Regards

Thank you @Ippezrobert @avikganguly01  for your time

**Comment by fynmanoj** [comment]
@vorburger ,  kindly let me know how to proceed

**Comment by vorburger** [comment]
> @vorburger , kindly let me know how to proceed

@fynmanoj see https://github.com/apache/fineract#pull-requests Basically, do not wait for an active maintainer to come and help you re. build failures - it's your responsibility to get a green build. Have you checked the log, and done what the README suggests to do in such cases? :smiley_cat:

**Comment by awasum** [comment]
@fynmanoj ..Please fix merge conflicts as a result of other merged PRs.

**Comment by fynmanoj** [comment]
done!

**Comment by edcable** [comment]
@vorburger @fynmanoj Is there still a build fail that needs to be addressed before this can be merged?

**Comment by fynmanoj** [comment]
rebase done

**Comment by vorburger** [comment]
@fynmanoj OK, and it's still failing... you need to get it to pass! That's not something we can do for you, but your role. We recently explained the process better on https://github.com/apache/fineract#pull-requests. Have you actually investigate this problem locally? Hint: Just run `./gradlew bootRun` yourself, and you'll immediately see the problem... but to contribute to this project, you should figure this out yourself, not wait for 8 days. 

@edcable it's each contributors responsibility to get their PRs to build.

**Comment by fynmanoj** [comment]
As the local build was successful and the test cases I introduced were working fine. It was clear that the issue was external. As there were integration tests being ignored, I was expecting this issue to get fixed eventually.  
@vorburger , I totally got you.  Let me see to fix this from my end

**Comment by fynmanoj** [comment]
Fixed all the issues, Kindly merge this PR

**Review by vorburger — APPROVED** [review]
I just did a quick technical review of this PR, and there is nothing shocking here, and it includes an Integration Test - this would get LGTM from me, once it actually passes the build. - It's a functional Improvement which, ideally, someone with domain expertise should review more. If we don't find anyone interested, I propose we would give this a 2 weeks grace period, and then merge if no one voices any objections....

@avikganguly01 can you please give this PR a "functional" review and LGTM, based on your questions from 1 month ago - does this LGTY? Tx!

**Comment by avikganguly01** [comment]
Looks good to me. Functionality is addressed correctly based on maturity instruction requirements. 

@Ippezrobert 

> MFI has a max of 1 yr Deposit Term but a client would wish to fix for 2 yrs, so the MFI accepts this offer and manages the 2 yrs period in shifts internally. So after the 1 yr is done, the MFI would like the rollover to be managed automatically by the system since chances that a new FD will be created exactly on the same date of maturity is small since an officer can forget to check if this FD is matured or not yet a client would be counting when the two years would end. So there needs to be a job scheduler to check maturity date for FD and also rollover options so that it (system can take appropriate decisions (to reinvest of just close and transfer interest and principal to linked savings).

Correct.

> To be discussed: Will the system use the same account number or new one will be created????

System will create new FD account with new account no at the time of maturity.

> A client would like to reinvest FD voluntarily since he sees no use for his money for some time. He then has to decides what amount or portion to reinvest after the first maturity is expired. Option can include rollover of principal only, rollover of principal and interest, transfer of balance to another account (make linked account dynamic .ie ability to select loan, shares or savings account and also a GL Account), etc

Scope of this feature was to address maturity instructions. Voluntary reinvest feature can be enhanced separately. Only savings account can be linked - not loan, share or GL account. Principal, Interest & P&I are the options - partial amount support (flat/%?) wasn't communicated earlier as well.


> If the selected option involves rollover, a Rollover End Date should be entered i.e the date when you want the rollover transaction to stop.

This does seem to be a design flaw.  All of us missed this observation. Workaround can be manually closing the FD to prevent rollover instructions triggering for a 2nd time.

> If the option selected in After Maturity does not involve the roll over of interest with the principal, the option of linked account is mandatory .ie account to which the transfer will be made at maturity. 

Correct.

**Pull request merged**
