### PR TITLE
 Corrected all Swagger documents found in the Accounting module by ad…

### PR DESCRIPTION
**Pull request by kangbreder**
## Description
Describe the changes made and why they were made. Ignore if these details are present on the associated Jira ticket

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Commit message starts with the issue number from https://issues.apache.org/jira/projects/FINERACT/. Ex: FINERACT-646 Pockets API.

- [x] Coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions have been followed.

- [x] API documentation at https://github.com/apache/fineract/blob/develop/api-docs/apiLive.htm has been updated with details of any API changes.

- [x] Integration tests have been created/updated for verifying the changes made.

- [x] All Integrations tests are passing with the new commits.

- [x] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the list.)

Our guidelines for code reviews is at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide

### CODE REVIEW

**Comment by vishwasbabu** [comment]
@Sanyam96 : Can you please review this change ?

**Comment by Sanyam96** [comment]
@kangbreder 
Changes seems to be perfect on first glance.
I'll review your changes and we'll merge your PR with complete GSoC project as a single PR on fineract.

**Review by Sanyam96 — COMMENTED** [review]
changes look fine at first glance.
We'll merge this as a single PR for GSoC project 2019 into fineract.

**Comment by vorburger** [comment]
> changes look fine at first glance.
> We'll merge this as a single PR for GSoC project 2019 into fineract.

@Sanyam96 I'm doing a quick round of review of open PRs to help clean up the list of pending PRs (any help with that is very very welcome BTW!)... were you planning to merge this (when?), or should this be closed, perhaps superceded by another one of @kangbreder PRs? BTW, generally speaking, I personally would encourage to gradually merge GSoC contributions, and not wait for one single "big bang".

**Pull request merged**
