### PR TITLE
Add docker-compose non-regression test to Travis CI

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@conradsp I have a feeling you'll like this? :smile:  (If it works, let's see how Travis likes it...)

**Comment by conradsp** [comment]
> @conradsp I have a feeling you'll like this? 😄 (If it works, let's see how Travis likes it...)

It looks like port 3306 is already bound on the CI machine. I suppose we could use another port for running CI in docker.

**Comment by vorburger** [comment]
> It looks like port 3306 is already bound on the CI machine. 
> I suppose we could use another port for running CI in docker.

Yeah.. but that's not completely trivial, it will need [FINERACT-773](https://issues.apache.org/jira/browse/FINERACT-773), which actually I've started looking into (for another reason). But In the meantime, let me try if we could just `sudo service mysql stop` before `docker-compose` ...

**Comment by vorburger** [comment]
@conradsp there were actually a couple of more problems here, but I managed to get it all working nicely now... could you review and merge this one? Thanks!

**Comment by vorburger** [comment]
@awasum if you have time & interest, perhaps you'd also like to review this one?

**Pull request merged**
